### ISSUE TITLE
ExtractMetadataException when building project with 2.9.3

### ISSUE THREAD

**Issue by cameron-elliott** [dotnet/docfx#1049]
Hello,

I am using the  DocFx.msbuild nuget package (v2.9.3) on AppVeyor for the docfx-seed project, and I get the following error:

```
[00:00:21] Info: Config file docfx.json found, start generating metadata...
[00:00:31] Info: Completed executing in 8943.6833 milliseconds.
[00:00:31] Error: System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"obj/api":["C:/projects/limevideosdk/docfx_project/src/SampleClass1/SampleClass1.sln"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"ShouldSkipMarkup":false,"UseCompatibilityFileName":false}: Unable to generate spec reference for !:CounterSampleCalculator ---> Microsoft.DocAsCode.Exceptions.DocfxException: Unable to generate spec reference for !:CounterSampleCalculator ---> System.NullReferenceException: Object reference not set to an instance of an object.
[00:00:31]    at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitNamedType(INamedTypeSymbol symbol)
[00:00:31]    at Microsoft.DocAsCode.Metadata.ManagedReference.NameVisitorCreator.GetName(ISymbol symbol)
[00:00:31]    at Microsoft.DocAsCode.Metadata.ManagedReference.CSReferenceItemVisitor.AddLinkItems(INamedTypeSymbol symbol, Boolean 
```

**Comment by qinezh** [comment]
Hi @cameron-elliott  There's no docfx.msbuild package (v2.9.3) exists in [nuget.org](https://www.nuget.org/packages/docfx.msbuild/). And docfx.msbuild has been dereprecated for a long time, please try docfx.console instead.

**Comment by cameron-elliott** [comment]
I apologize, I am actually using docfx.console 2.9.3
Any ideas why this error would occur?

**Comment by qinezh** [comment]
@cameron-elliott I just can't repro it. Is there any extra step? 

And it's a little weird that DocFX installed from chocolatey is the same with DocFX downloaded from `docfx.console`, but from another issue, I found you build docfx-seed with DocFX installed from chocolatey successfully...

**Comment by cameron-elliott** [comment]
I will close this to see if I can provide a better example
