### ISSUE TITLE
Support for file URI scheme?

### ISSUE THREAD

**Issue by kazyx** [dotnet/docfx#1287]
### Title
Support for file URI scheme?

### Functional impact
Generated document does not support local file browsing with `file://` URI with the following error in JS.

```
Uncaught DOMException: Failed to construct 'Worker': Script at 'file:///D:/workspace/docprj/_site/styles/search-worker.js' cannot be accessed from origin 'null'.
    at searchFactory (file:///D:/workspace/docprj/_site/styles/docfx.js:100:20)
    at file:///D:/workspace/docprj/_site/styles/docfx.js:93:18
    at HTMLDocument.<anonymous> (file:///D:/workspace/docprj/_site/styles/docfx.js:270:5)
    at j (file:///D:/workspace/docprj/_site/styles/docfx.vendor.js:2:26925)
    at Object.fireWith [as resolveWith] (file:///D:/workspace/docprj/_site/styles/docfx.vendor.js:2:27738)
    at Function.ready (file:///D:/workspace/docprj/_site/styles/docfx.vendor.js:2:29532)
    at HTMLDocument.I (file:///D:/workspace/docprj/_site/styles/docfx.vendor.js:2:29723)
```

### Minimal repro steps

1. Generate API document.
1. Open index.html file locally with WebBrowser.

### Expected result

Document index should be created by some fallback way when it is opened with `file://` URI.

### Actual result

DocFX fails to create worker and stops creating index.

**Comment by vicancy** [comment]
Exception catched in https://github.com/dotnet/docfx/pull/1509
You can use `template: [default, statictoc]` so that the pages can be viewed in file system directly

**Comment by kazyx** [comment]
@vicancy 
Thanks, documents are successfully rendered in file system when `"template": ["statictoc"]` is set.
