### ISSUE TITLE
Task cancelled exception when running DocFX

### ISSUE THREAD

**Issue by petertiedemann** [dotnet/docfx#1345]
### Title
Running DocFx on a set of projects fails with a lot of task cancelled exceptions.

### Functional impact
Failure to generate docs.

### Minimal repro steps
I would very much like to provide repro steps, but when i isolate the project that failed, then it no longer fails. The full set of projects is unfortunately proprietary code that i cannot share.  Having this project as the only one in src.files is however enough to cause the failure.

What can i do to provide more information?

### Expected result
The documentation to be generated

### Actual result
```
Error: System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"obj/api":["C:/Users/pt/git/core/src/Solve/Solve.csproj"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"ShouldSkipMarkup":false,"UseCompatibilityFileName":false}: Error extracting metadata for project "C:/Users/pt/git/core/src/Solve/Solve.csproj": A task was canceled. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for project "C:/Users/pt/git/core/src/Solve/Solve.csproj": A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetProjectCompilationAsync>d__35.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetProjectCompilationAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"obj/api":["C:/Users/pt/git/core/src/Solve/Solve.csproj"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"ShouldSkipMarkup":false,"UseCompatibilityFileName":false}: Error extracting metadata for project "C:/Users/pt/git/core/src/Solve/Solve.csproj": A task was canceled. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for project "C:/Users/pt/git/core/src/Solve/Solve.csproj": A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetProjectCompilationAsync>d__35.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetProjectCompilationAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__19.MoveNext()<---



Build failed.
Error: System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"obj/api":["C:/Users/pt/git/core/src/Solve/Solve.csproj"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"ShouldSkipMarkup":false,"UseCompatibilityFileName":false}: Error extracting metadata for project "C:/Users/pt/git/core/src/Solve/Solve.csproj": A task was canceled. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for project "C:/Users/pt/git/core/src/Solve/Solve.csproj": A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetProjectCompilationAsync>d__35.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetProjectCompilationAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"obj/api":["C:/Users/pt/git/core/src/Solve/Solve.csproj"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"ShouldSkipMarkup":false,"UseCompatibilityFileName":false}: Error extracting metadata for project "C:/Users/pt/git/core/src/Solve/Solve.csproj": A task was canceled. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for project "C:/Users/pt/git/core/src/Solve/Solve.csproj": A task was canceled. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetProjectCompilationAsync>d__35.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetProjectCompilationAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__19.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__19.MoveNext()<---
```
### Further technical details
The projects are generated by VS2015, most are 4.6.1 C# projects, with a single F# 4.0 project.

**Comment by vicancy** [comment]
Is the project very large? Or is the project locked? Looks like `docfx` fails to open the project with `GetProjectCompilationAsync`

**Comment by petertiedemann** [comment]
@vicancy What do you consider a very large project? The solution has ~25 lib projects and about the same number of test projects. I have opened much larger projects than that with Roslyn previously (such as the whole coreclr :)

PS: Sorry for the slow reply, i was sick.

**Comment by vicancy** [comment]
Take care Peter. Is it possible to repro the error?

**Comment by petertiedemann** [comment]
@vicancy I have not found a simple repro. I had a quick try at debugging and ended up in `GetProjectCompilationAsync` as you suspected. When i get a bit of spare time i will try to debug it standalone using just Roslyn to see if it is a roslyn issue.

**Comment by simplicbe** [comment]
I've got the same issue with a quite larger project (~project files) .Net framework 4.5 / c#. Are there any solutions right now?

**Comment by superyyrrzz** [comment]
@simplicbe There are various type of errors behind this error message. Can you provide repro steps?

**Comment by vicancy** [comment]
Hi @petertiedemann This can happen when the project is large. Could you try build the project first, and then use the assembly generated to `docfx metadata`? assemblies like `A.dll` is also supported now.

**Comment by vwxyzh** [comment]
#1670
