### ISSUE TITLE
Building from sources fails

### ISSUE THREAD

**Issue by atifaziz** [dotnet/docfx#151]
I cloned the repo, checked out tag [1.4.2](https://github.com/dotnet/docfx/releases/tag/1.4.2) (latest release at the time of reporting this issue) and ran `build.cmd` from a regular Windows 10 Command Prompt. This was more or less per the instructions laid out in the “[Build from source code](http://dotnet.github.io/docfx/tutorial/docfx_getting_started.html#3-2-build-from-source-code)” section of your documentation but it failed with many warnings & errors.

See [buildlog.txt](https://github.com/dotnet/docfx/files/120762/buildlog.txt) for the complete build details.

**Comment by vwxyzh** [comment]
It looks like: running `build.cmd` with opening solution by `Visual Studio`.
`Visual Studio` will lock some files, e.g. `project.lock.json`.

**Comment by atifaziz** [comment]
@vwxyzh I never had VS open. I tried again with a `git clean -dxf` followed by `build.cmd` (all from the command-line) and got the same errors.

**Comment by vicancy** [comment]
According to the log,
```
  NotFound https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.workspaces.common/index.json 351ms
  NotFound https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.visualbasic.workspaces/index.json 368ms
  NotFound https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.csharp.workspaces/index.json 363ms
  NotFound https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.visualbasic/index.json 386ms
```
These packages are not restored correctly.
Could you remove `https://www.myget.org/F/raboof/api/v3/flatcontainer` from your nuget.config temporarily, close you VS, delete all `project.lock.json` file and have a retry?

**Comment by atifaziz** [comment]
@vicancy If I search the log for `microsoft.codeanalysis.workspaces.common` using…

    findstr /i microsoft.codeanalysis.workspaces.common buildlog.txt

…then I see that it does get restored eventually over another feed…

```
  GET https://www.myget.org/F/aspnetrelease/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  GET https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.workspaces.common/index.json
  GET https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  GET https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  GET https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  OK https://www.myget.org/F/aspnetrelease/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common' 544ms
  NotFound https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.workspaces.common/index.json 648ms
  OK https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common' 657ms
  OK https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common' 1207ms
  OK https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common' 3866ms
  CACHE https://www.myget.org/F/aspnetrelease/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  GET https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.workspaces.common/index.json
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  CACHE https://www.postsharp.net/nuget/packages/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  NotFound https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.workspaces.common/index.json 351ms
Restoring NuGet package Microsoft.CodeAnalysis.Workspaces.Common.1.1.0-rc1-20151109-01.
Adding package 'Microsoft.CodeAnalysis.Workspaces.Common.1.1.0-rc1-20151109-01' to folder 'A:\docfx\packages'
Added package 'Microsoft.CodeAnalysis.Workspaces.Common.1.1.0-rc1-20151109-01' to folder 'A:\docfx\packages'
Restoring NuGet package Microsoft.CodeAnalysis.Workspaces.Common.1.1.0.
Adding package 'Microsoft.CodeAnalysis.Workspaces.Common.1.1.0' to folder 'A:\docfx\packages'
Added package 'Microsoft.CodeAnalysis.Workspaces.Common.1.1.0' to folder 'A:\docfx\packages'
  NotFound https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.workspaces.common/index.json 2637ms
  NotFound https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.workspaces.common/index.json 2637ms
  NotFound https://www.myget.org/F/raboof/api/v3/flatcontainer/microsoft.codeanalysis.workspaces.common/index.json 2780ms
    Using Package dependency Microsoft.CodeAnalysis.Workspaces.Common 1.1.0
      Source: C:\Users\Atif\.dnx\packages\Microsoft.CodeAnalysis.Workspaces.Common\1.1.0
```

Also, after doing a `git clean -dxf`, there are no `project.lock.json` files to be found. That is, doing `dir *.lock.json /s/b` returns nothing. However, building still continues to fail.

**Comment by vicancy** [comment]
Build log says `A:\docfx\src\Microsoft.DocAsCode.YamlSerialization\project.lock.json(1): error NU1006: . Please run "dnu restore" to generate a new lock file. [A:\docfx\src\Microsoft.DocAsCode.YamlSerialization\Microsoft.DocAsCode.YamlSerialization.xproj]`.
If you go to `A:\docfx\src\Microsoft.DocAsCode.YamlSerialization`, run:
`dnu restore`
`dnu build`
Can it succeed?

**Comment by atifaziz** [comment]
@vicancy The `dnu restore` succeeded:

```
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231

  CACHE https://nuget.org/api/v2/curated-feeds/dotnetframework/
  CACHE https://www.myget.org/F/mannex/api/v2/
  CACHE https://www.myget.org/F/raboof/api/v2/
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/
  CACHE https://www.nuget.org/api/v2/
  CACHE https://dotnet.myget.org/F/dotnet-core/
Restoring packages for A:\docfx\src\Microsoft.DocAsCode.YamlSerialization\project.json
Writing lock file A:\docfx\src\Microsoft.DocAsCode.YamlSerialization\project.lock.json
Restore complete, 351ms elapsed

NuGet Config files used:
    C:\ProgramData\NuGet\Config\nuget-postsharp.config
    C:\Users\Atif\AppData\Roaming\NuGet\nuget.config
    A:\docfx\nuget.config

Feeds used:
    https://www.myget.org/F/aspnetrelease/api/v2/
    C:\ved\nuget.org
    https://www.myget.org/F/raboof/api/v3/flatcontainer/
    https://www.myget.org/F/aspnetmaster/api/v2/
    https://www.nuget.org/api/v2/
    https://www.postsharp.net/nuget/packages/
```

And so did `dnu build`:

```
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231


Building Microsoft.DocAsCode.YamlSerialization for .NETFramework,Version=v4.5
  Using Project dependency Microsoft.DocAsCode.YamlSerialization 1.0.0
    Source: A:\docfx\src\Microsoft.DocAsCode.YamlSerialization\project.json

  Using Package dependency YamlDotNet.Signed 3.7.0
    Source: C:\Users\Atif\.dnx\packages\YamlDotNet.Signed\3.7.0
    File: lib\net35\YamlDotNet.dll

  Using Assembly dependency fx/System.Core 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll

  Using Assembly dependency fx/mscorlib 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll

  Using Assembly dependency fx/System 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll

  Using Assembly dependency fx/Microsoft.CSharp 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll


Building Microsoft.DocAsCode.YamlSerialization for .NETCore,Version=v4.5
  Using Project dependency Microsoft.DocAsCode.YamlSerialization 1.0.0
    Source: A:\docfx\src\Microsoft.DocAsCode.YamlSerialization\project.json

  Using Package dependency System.IO 4.0.0
    Source: C:\Users\Atif\.dnx\packages\System.IO\4.0.0
    File: ref\dotnet\System.IO.dll

  Using Package dependency System.Reflection 4.0.0
    Source: C:\Users\Atif\.dnx\packages\System.Reflection\4.0.0
    File: ref\dotnet\System.Reflection.dll

  Using Package dependency System.Reflection.Emit.ILGeneration 4.0.0
    Source: C:\Users\Atif\.dnx\packages\System.Reflection.Emit.ILGeneration\4.0.0
    File: ref\dotnet\System.Reflection.Emit.ILGeneration.dll

  Using Package dependency System.Reflection.Emit.Lightweight 4.0.0
    Source: C:\Users\Atif\.dnx\packages\System.Reflection.Emit.Lightweight\4.0.0
    File: ref\dotnet\System.Reflection.Emit.Lightweight.dll

  Using Package dependency System.Reflection.Primitives 4.0.0
    Source: C:\Users\Atif\.dnx\packages\System.Reflection.Primitives\4.0.0
    File: ref\dotnet\System.Reflection.Primitives.dll

  Using Package dependency System.Runtime 4.0.0
    Source: C:\Users\Atif\.dnx\packages\System.Runtime\4.0.0
    File: ref\dotnet\System.Runtime.dll

  Using Package dependency System.Text.Encoding 4.0.0
    Source: C:\Users\Atif\.dnx\packages\System.Text.Encoding\4.0.0
    File: ref\dotnet\System.Text.Encoding.dll

  Using Package dependency System.Threading.Tasks 4.0.0
    Source: C:\Users\Atif\.dnx\packages\System.Threading.Tasks\4.0.0
    File: ref\dotnet\System.Threading.Tasks.dll

  Using Package dependency YamlDotNet.Signed 3.7.0
    Source: C:\Users\Atif\.dnx\packages\YamlDotNet.Signed\3.7.0
    File: lib\portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1\YamlDotNet.dll

  Using Assembly dependency fx/System 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.dll

  Using Assembly dependency fx/System.Core 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Core.dll

  Using Assembly dependency fx/System.Collections 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Collections.dll

  Using Assembly dependency fx/System.Collections.Concurrent 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Collections.Concurrent.dll

  Using Assembly dependency fx/System.Dynamic.Runtime 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Dynamic.Runtime.dll

  Using Assembly dependency fx/System.Globalization 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Globalization.dll

  Using Assembly dependency fx/System.IO 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.IO.dll

  Using Assembly dependency fx/System.Linq 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Linq.dll

  Using Assembly dependency fx/System.Net 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Net.dll

  Using Assembly dependency fx/System.Reflection 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Reflection.dll

  Using Assembly dependency fx/System.Reflection.Extensions 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Reflection.Extensions.dll

  Using Assembly dependency fx/System.Reflection.Primitives 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Reflection.Primitives.dll

  Using Assembly dependency fx/System.Runtime 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Runtime.dll

  Using Assembly dependency fx/System.Runtime.Extensions 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Runtime.Extensions.dll

  Using Assembly dependency fx/System.Runtime.Serialization.Primitives 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Runtime.Serialization.Primitives.dll

  Using Assembly dependency fx/System.Text.RegularExpressions 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETCore\v4.5\System.Text.RegularExpressions.dll


Building Microsoft.DocAsCode.YamlSerialization for DNX,Version=v4.5.1
  Using Project dependency Microsoft.DocAsCode.YamlSerialization 1.0.0
    Source: A:\docfx\src\Microsoft.DocAsCode.YamlSerialization\project.json

  Using Package dependency YamlDotNet.Signed 3.7.0
    Source: C:\Users\Atif\.dnx\packages\YamlDotNet.Signed\3.7.0
    File: lib\net35\YamlDotNet.dll

  Using Assembly dependency fx/System.Core 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Core.dll

  Using Assembly dependency fx/mscorlib 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\mscorlib.dll

  Using Assembly dependency fx/System 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.dll

  Using Assembly dependency fx/Microsoft.CSharp 4.0.0
    Source: C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Microsoft.CSharp.dll


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time elapsed 00:00:00.8812080
Total build time elapsed: 00:00:00.8860008
Total projects built: 1
```

Anything else I can do or test to help shed more light on the issue?

**Comment by vicancy** [comment]
Could you do this for all the failed projects and rerun build.cmd to see if it succeeds?

**Comment by atifaziz** [comment]
@vicancy I have tried everything you've suggested so far and building still fails with the same issues as originally reported. Running `dnu restore && dnu build` on individual projects based on `xproj` succeeds but then running `build.cmd` as a whole still fails. I even tried removing [the `--parallel` switch on `dnu restore`](https://github.com/dotnet/docfx/blob/dev/build.cmd#L99) in case there was a race condition but it didn't help.

**Comment by atifaziz** [comment]
@vicancy I also did a CI setup on AppVeyor using the following settings or YAML config:

```yaml
version: 1.0.{build}
os: Visual Studio 2015
build_script:
- cmd: build.cmd
```

and it's failing there too…[see build 1.0.1](https://ci.appveyor.com/project/raboof/docfx/build/1.0.1).

So I don't think it's a question of my machine configuration being uniquely setup.

**Comment by vicancy** [comment]
Thank you @atifaziz for all the effort! The info is really helpful. I will look into it.

**Comment by vicancy** [comment]
Turns out the build failure is caused by some version of nuget.... 
https://ci.appveyor.com/project/vicancy/docfx/build/1.0.11 it passes build in appveyor with the latest fix.

**Comment by atifaziz** [comment]
@vicancy I see that and it's building now on [my AppVeyor setup for DocFX](https://ci.appveyor.com/project/raboof/docfx/build/1.0.2) as well so that's certainly out of the way. :+1: Unfortunately, it looks like afff742bf640b49d06568af67beac7ef1ca8f694 still hasn't fixed it on my local end and I continue to see those errors I originally reported. I might have some more info shortly and hopefully it can help to get down to the root of this. Can we re-open the issue meanwhile?

**Comment by atifaziz** [comment]
So here's something new. I ran `git clean -xdf` following by `build.cmd`. This produced all those `project.lock.json` errors we've been discussion so far. The funny this is that doing a `dir project.lock.json /s /b` shows that all the `project.lock.json` files were indeed written:

```
A:\DocFX\src\docfx\project.lock.json
A:\DocFX\src\Microsoft.CodeAnalysis.Workspaces.Dnx\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.AzureMarkdownRewriters\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.Common\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.Dfm\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.EntityModel\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.Glob\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.MarkdownLite\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.MetadataSchemata\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.Plugins\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.Utility\project.lock.json
A:\DocFX\src\Microsoft.DocAsCode.YamlSerialization\project.lock.json
A:\DocFX\tools\MergeDeveloperComments\project.lock.json
A:\DocFX\tools\MergeSourceInfo\project.lock.json
```

Since [we discovered earlier](https://github.com/dotnet/docfx/issues/151#issuecomment-188147575) `dnu restore && dnu build` was working for individual projects, I decided to do that after the failing build on `src\docfx`. It succeeded and then I did a diff on the `project.lock.json` *before* and *after* (see [project.lock.json.zip](https://github.com/dotnet/docfx/files/147008/project.lock.json.zip)) and results were interesting. It seems that the `project.lock.json` is being produced in two different formats. Initially in v1 format (when it initially fails) and then in v2 (when it subsequently succeeds). I've [published the diff online](https://gist.github.com/atifaziz/d00dd68db3c089cde131).

I wonder if this can shed any more light? At the moment, I haven't quite dug into how the same `dnu restore` can produce `project.lock.json` in two different formats. It seems as if running as part of `build.cmd`, it's producing v1 format and then when I run it straight from the command-line, it produces a v2 format then then `dnu build` is happy with.

**Comment by atifaziz** [comment]
@vicancy I managed to make the build work! Looks like the issue is [indeed linked to the NuGet version getting defaulted](https://github.com/dotnet/docfx/issues/151#issuecomment-188842279). The build works with 2.8 but incompatible with 3.3 & I'm reckon the the two work with different `project.lock.json` formats.

On the two boxes I had been trying, 3.3 was always the one being picked up but when I forced 2.8, it worked like a charm. I'm guessing that I already had a [cached version](https://github.com/dotnet/docfx/blob/afff742bf640b49d06568af67beac7ef1ca8f694/build.cmd#L35)  that was at 3.3 or that while [downloading the latest from `https://www.nuget.org/nuget.exe`](https://github.com/dotnet/docfx/blob/afff742bf640b49d06568af67beac7ef1ca8f694/build.cmd#L109) does grab & cache 2.8, it didn't make a difference because it's [the last in priority in the system path](https://github.com/dotnet/docfx/blob/afff742bf640b49d06568af67beac7ef1ca8f694/build.cmd#L38). I don't see how afff742bf640b49d06568af67beac7ef1ca8f694 fixes the issue by forcing NuGet 2.8 in a deterministic manner.

**Comment by vicancy** [comment]
@atifaziz afff742bf640b49d06568af67beac7ef1ca8f694 forces using the one under %LocalAppData%\NuGet\NuGet.exe. It can fix the issue for a clean machine, but if you already has a 3.3 version of nuget under %LocalAppData%\NuGet, build still fails. I will add a version check to build.cmd.

**Comment by atifaziz** [comment]
20d8d97958e44df214a07c66832bd006a40bcbd4 did the trick! :tada:

Thank you for working through to the bottom of this!

**Comment by evil-shrike** [comment]
I can't build docfx project as well.
First of all the README.md is not fully correct - it says that it's enough:
* `dnvm install 1.0.0-rc1-final`
* Run `build.cmd` under DocFX code repo

For me build.cmd was telling that dnvm isn't configured till I updated dnx to the latest rc1-update1 (I had 1.0.0-rc1-final already with default flag indeed).

After I updated to rc1-update build.cmd starts building. But it produces a ton of errors in console. So I opened all.sln in VS2015 and there I can see errors of restoring packages:
```
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Sergei Dorogin\.dnx\packages\System.Linq\4.0.0\System.Linq.4.0.0.nupkg.sha512'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.Dnx.Tooling.Utils.LockFileUtils.CreateLockFilePackageLibrary(LockFilePackageLibrary previousLibrary, IPackagePathResolver resolver, IPackage package, String correctedPackageName)
   at Microsoft.Dnx.Tooling.RestoreCommand.WriteLockFile(LockFile previousLockFile, String projectLockFilePath, Project project, List`1 graphItems, PackageRepository repository, IProjectResolver projectResolver, IEnumerable`1 contexts)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
Could not find a part of the path 'C:\Users\Sergei Dorogin\.dnx\packages\System.Linq\4.0.0\System.Linq.4.0.0.nupkg.sha512'.
Restoring packages for D:\Work\R-n-D\XFW3\Sources\Foundation\Repo\Doc\docfx_src\src\Microsoft.DocAsCode.Utility\project.json
Writing lock file D:\Work\R-n-D\XFW3\Sources\Foundation\Repo\Doc\docfx_src\src\Microsoft.DocAsCode.Utility\project.lock.json
----------
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Sergei Dorogin\.dnx\packages\System.Linq\4.0.0\System.Linq.4.0.0.nupkg.sha512'.
```

Any ideas what can be wrong?

**Comment by vicancy** [comment]
Hi @evil-shrike , could you provide the build.log after running build.cmd?

**Comment by evil-shrike** [comment]
Hi @vicancy ! Where can I find it? There're no *.log files in the folder where I run build.cmd nor in UserHome.

**Comment by vicancy** [comment]
It is `msbuild.log` and it should be in the same folder with your `build.cmd`.

**Comment by evil-shrike** [comment]
Found it. There're a lot of error there as restore was not successful (I think it'd make sense to not even try compiling if restore failed).
So I run `dnu restore` separately and it shows an error:
```
D:\...\R-n-D\XFW3\Sources\Foundation\Repo\Doc\docfx_src>dnu restore
Microsoft .NET Development Utility Clr-x86-1.0.0-rc1-16231

  CACHE https://www.myget.org/F/aspnetmaster/api/v2/
  CACHE https://www.nuget.org/api/v2/
  CACHE https://dotnet.myget.org/F/dotnet-core/
Restoring packages for D:\Work\R-n-D\XFW3\Sources\Foundation\Repo\Doc\docfx_src\src\docfx\project.json
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Common'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Common'
  CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.CodeAnalysis.Common'
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.VisualBasic'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.VisualBasic'
  CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.CodeAnalysis.VisualBasic'
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.VisualBasic.Workspaces'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.VisualBasic.Workspaces'
  CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.CodeAnalysis.VisualBasic.Workspaces'
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.CSharp'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.CSharp'
  CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.CodeAnalysis.CSharp'
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.CSharp.Workspaces'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.CSharp.Workspaces'
  CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.CodeAnalysis.CSharp.Workspaces'
  CACHE https://www.myget.org/F/aspnetmaster/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  CACHE https://www.nuget.org/api/v2/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
  CACHE https://dotnet.myget.org/F/dotnet-core/FindPackagesById()?id='Microsoft.CodeAnalysis.Workspaces.Common'
Writing lock file D:\Work\R-n-D\XFW3\Sources\Foundation\Repo\Doc\docfx_src\src\docfx\project.lock.json
----------
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Sergei Dorogin\.dnx\packages\System.Linq\4.0.0\System.Linq.4.0.0.nupkg.sha512'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.Dnx.Tooling.Utils.LockFileUtils.CreateLockFilePackageLibrary(LockFilePackageLibrary previousLibrary, IPackagePathResolver resolver, IPackage package, String correctedPackageName)
   at Microsoft.Dnx.Tooling.RestoreCommand.WriteLockFile(LockFile previousLockFile, String projectLockFilePath, Project project, List`1 graphItems, PackageRepository repository, IProjectResolver projectResolver, IEnumerable`1 contexts)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
Could not find a part of the path 'C:\Users\Sergei Dorogin\.dnx\packages\System.Linq\4.0.0\System.Linq.4.0.0.nupkg.sha512'.

NuGet Config files used:
    C:\Users\Sergei Dorogin\AppData\Roaming\NuGet\nuget.config
    D:\Work\R-n-D\XFW3\Sources\Foundation\Repo\Doc\docfx_src\nuget.config

Feeds used:
    https://www.myget.org/F/aspnetmaster/api/v2/
    https://www.nuget.org/api/v2/
    https://dotnet.myget.org/F/dotnet-core/
```
There's no such folder "\.dnx\packages\System.Linq\4.0.0\". I had only these ones:
4.0.0-beta-22605
4.0.0-beta-22816
4.0.0-beta-22913
4.0.0.0
I removed the whole folder `.dnx\packages\System.Linq` and rerun restore. It succeeded.


Then I run build.cmd again. Here's the log.
[docfx_msbuild.zip](https://github.com/dotnet/docfx/files/183916/docfx_msbuild.zip)

It seems that it can't find YamlDotNet. 

In console I can see a problem after dnu restore completes (before building):
```
'C:\Users\Sergei' is not recognized as an internal or external command,
operable program or batch file.
ERROR: Error when restoring packages for D:\Work\R-n-D\XFW3\Sources\Foundation\Repo\Doc\docfx_src\All.sln
```
