### ISSUE TITLE
Do I have to put my projects in the docfx_project directory?

### ISSUE THREAD

**Issue by mgregory22** [dotnet/docfx#1517]
This is just a question.  I'm confused by the tutorial and I'm not sure where to ask.

I have a couple of projects that I've made all my doc comments in and I want to generate some html docs.  I use GhostDoc a little bit at work, but I don't want to pay for it, and I wanted to see if docfx is better.

I already have a system for organizing my files and I feel like it's a lot to ask for an app to make me move my project folders around.  It actually seems more sensible to me to put the documentation in the project directory rather than the other way around.  Please help me understand.

I tried making a directory junction link to my project folder, but I get this error when I try to generate:

```
[17-04-02 04:15:56.563]Error:System.IO.PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesFromSubfolder>d__2.MoveNext()
   at Microsoft.DocAsCode.Glob.FileGlob.<GetFilesCore>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.DocAsCode.GlobUtility.ExpandFileMapping(String baseDirectory, FileMapping fileMapping)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.ConvertToInputModel(MetadataJsonItemConfig configModel)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.<GetInputModels>d__11.MoveNext()
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
```

**Comment by superyyrrzz** [comment]
Can you provide the docfx.json you use?

**Comment by superyyrrzz** [comment]
DocFX's own document has the similar issue, with document in `/Documentation` and source code in `/src`. In docfx.json, we use `"src": "../src"` to link to the source code folder: https://github.com/dotnet/docfx/blob/master/Documentation/docfx.json#L8

**Comment by mgregory22** [comment]
I just want to know how to incorporate docfx into an existing project.

I have a class library called MSG in C:\...\Lib\MSG\MSG, so I cd into there and run docfx init -q.

It tells me to run 'docfx "C:\...\Lib\MSG\MSG\docfx_project\docfx.json" --serve', which I do and it works fine, but there's nothing in the site.

So now the only thing I can find for help is the "Part II: Adding API Documentation to the Website", which talks about creating a new class library project in C:\...\Lib\MSG\MSG\docfx_project\src, which doesn't apply to me because I've already made my class library project in C:\...\Lib\MSG\MSG, and I want the documentation to be part of the MSG project, so I can just add it to a subdirectory in the existing GitHub repo.

What should I do?

**Comment by mgregory22** [comment]
Ah, thank you.  That worked!  I didn't realize the error message was saying that there is another "src" option nested in the "src" option.
