### ISSUE TITLE
ArgumentNullException on metadata generation if class explicitly implements a member with EditorBrowsableAttribute with EditorBrowsableState.Never value

### ISSUE THREAD

**Issue by Skudnoff** [dotnet/docfx#1825]
### Title
ArgumentNullException on metadata generation if class explicitly implements a member with EditorBrowsableAttribute with EditorBrowsableState.Never value

### Functional impact
Metadata can't be generated

### Minimal repro steps
1. Create default .NET console application
2. Replace Program.cs code with 
```csharp
    class Program {
        static void Main(string[] args) { }
    }
    public interface IInterface1 {
        [EditorBrowsable(EditorBrowsableState.Never)]
        bool InterfaceProperty1 { get; }
    }
    public class Class1 : IInterface1 {
        bool IInterface1.InterfaceProperty1 {
            get { return true; }
        }
    }
```
3. Run docfx metadata

### Expected result
Metadata is successfully generated

### Actual result
ArgumentNullException is raised and metadata is not generated

### Further technical details

1. Problem exists in docfx 2.17.7 and 2.19.2
2. If class member has same attribute with same value the exception is not raised
```csharp
    public class Class1 : IInterface1 {
        [EditorBrowsable(EditorBrowsableState.Never)]
        bool IInterface1.InterfaceProperty1 {
            get { return true; }
        }
    }
```

3. This is docfx output
```
[17-07-03 08:50:10.250]Info:Completed executing in 3300.9152 milliseconds.
[17-07-03 08:50:10.261]Error:System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for D:/tests/ConsoleApp3/ConsoleApp3.sln: Value cannot be null.
Parameter name: text ---> System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.CodeAnalysis.Text.SourceText.From(String text, Encoding encoding, SourceHashAlgorithm checksumAlgorithm)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MakeLexer(String text, Int32 offset, CSharpParseOptions options)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseName(String text, Int32 offset, Boolean consumeFullText)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetPropertySyntax(IPropertySymbol symbol, IFilterVisitor filterVisitor)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SimpleYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitProperty(IPropertySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.ExecCore()
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for D:/tests/ConsoleApp3/ConsoleApp3.sln: Value cannot be null.
Parameter name: text ---> System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.CodeAnalysis.Text.SourceText.From(String text, Encoding encoding, SourceHashAlgorithm checksumAlgorithm)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MakeLexer(String text, Int32 offset, CSharpParseOptions options)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseName(String text, Int32 offset, Boolean consumeFullText)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetPropertySyntax(IPropertySymbol symbol, IFilterVisitor filterVisitor)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SimpleYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitProperty(IPropertySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()<---



Build failed.
[17-07-03 08:50:10.283]Error:System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for D:/tests/ConsoleApp3/ConsoleApp3.sln: Value cannot be null.
Parameter name: text ---> System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.CodeAnalysis.Text.SourceText.From(String text, Encoding encoding, SourceHashAlgorithm checksumAlgorithm)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MakeLexer(String text, Int32 offset, CSharpParseOptions options)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseName(String text, Int32 offset, Boolean consumeFullText)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetPropertySyntax(IPropertySymbol symbol, IFilterVisitor filterVisitor)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SimpleYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitProperty(IPropertySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.ExecCore()
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for D:/tests/ConsoleApp3/ConsoleApp3.sln: Value cannot be null.
Parameter name: text ---> System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.CodeAnalysis.Text.SourceText.From(String text, Encoding encoding, SourceHashAlgorithm checksumAlgorithm)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MakeLexer(String text, Int32 offset, CSharpParseOptions options)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseName(String text, Int32 offset, Boolean consumeFullText)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetPropertySyntax(IPropertySymbol symbol, IFilterVisitor filterVisitor)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SimpleYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitProperty(IPropertySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__27`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__12.MoveNext()<---

	0 Warning(s)
	1 Error(s)
```

**Comment by hellosnow** [comment]
`EditorBrowsableState.Never` is excluded by default filter configuration, therefore for `IInterface1`, `InterfaceProperty1` is filtered out. But for the interface implementation `Class1`, *explicit interface implementation* `IInterface1.InterfaceProperty1` should be filtered out as well, instead of throwing this exception. Will investigate further how to fix it.
