### ISSUE TITLE
Error while creating a sample project in a Windows 7 machine.

### ISSUE THREAD

**Issue by scirneanu** [dotnet/docfx#1990]
I encountered the below error while creating a sample project(docfx init -q) in a Windows 7 machine:

Error:Microsoft.DocAsCode.Exceptions.DocfxInitException: Error with init docfx project under "" : Method not found: '!!0[] System.Array.Empty()'. ---> System.MissingMethodException: Method not found: '!!0[] System.Array.Empty()'.
at Microsoft.DocAsCode.SubCommands.InitCommand.<>c.<.cctor>b__32_7(Boolean s, DefaultConfigModel m, QuestionContext c)
at Microsoft.DocAsCode.SubCommands.InitCommand.Exec(SubCommandRunningContext context)
--- End of inner exception stack trace ---
at Microsoft.DocAsCode.SubCommands.InitCommand.Exec(SubCommandRunningContext context)
at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args).

In order to install DocFX, I downloaded docfx.zip from https://github.com/dotnet/docfx/releases, extracted it to a local folder and added it to PATH.

**Comment by vicancy** [comment]
As per https://stackoverflow.com/questions/31253747/method-not-found-0-system-array-empty-asapp-bundleconfig-registerbundl, do you have .NET framework 46 installed in your machine?

**Comment by scirneanu** [comment]
No. I had 4.5.2. Now I installed 4.6 and everything is fine. Thank you!
