### ISSUE TITLE
Error extracting metadata for project : An item with the same key has already been added

### ISSUE THREAD

**Issue by darylrobbins** [dotnet/docfx#2532]
**DocFX Version Used**: 2.33

**Template used**: `default`

**Steps to Reproduce**:

Paths have been anonymized to protect the innocent.

1. Execute `docfx metadata C:\Users\someuser\Code\SomeProject\Module\SomeLibrary.Shared\SomeLibrary.Shared.vbproj -f`

**Expected Behavior**:
Successfully generates metadata

**Actual Behavior**:
Metadata generation fails with the following error:
```
[18-03-19 07:58:56.263]Info:[ExtractMetadata]Generating metadata for each project... 
[18-03-19 07:59:04.842]Error:Error extracting metadata for C:\Users\someuser\Code\SomeProject\Module\SomeLibrary.Shared\SomeLibrary.Shared.vbproj: Error extracting metadata for project "C:\Users\someuser\Code\SomeProject\Module\SomeLibrary.Shared\SomeLibrary.Shared.vbproj": An item with the same key has already been added.
```

**Notes:**
This is the first time trying to run docfx on our project. I saw the same error on other VB projects. I tried earlier versions and saw similar/additional errors.

**Comment by vicancy** [comment]
Hi @darylrobbins Could you share a minimum project that can repro the issue to us?

**Comment by michaelp** [comment]
I have the same issue with version 2.35.4 
_Is it possible to increase verbosity and get the docfx log ?_

**Comment by vicancy** [comment]
Hi @michaelp Yes good suggestion. Meanwhile, could you provide some minimum project for us to repro the issue? Is there duplicate references in the project?

**Comment by JulienM28** [comment]
Hello,
I just got the same issue with 2.3.5 version.

Impossible to build the documentation.

Projects are using .Net Framework 4.5.2.

**Comment by michaelp** [comment]
problem happens with the tests projects 
The following snippet of code is the source of the issue. It happens on 6th projectis getting into the dictionary
checking if there is anything special about those projects. 

```csharp
private static async Task<ConcurrentDictionary<string, AbstractCompilation>> GetProjectCompilationAsync(ConcurrentDictionary<string, AbstractProject> projectCache)
        {
            var compilations = new ConcurrentDictionary<string, AbstractCompilation>();
            var sb = new StringBuilder();
            foreach (var project in projectCache)
            {
                try
                {
                    var compilation = await project.Value.GetCompilationAsync();
                    compilations.TryAdd(project.Key, compilation);
                }
                catch (Exception e)
                {
                    if (sb.Length > 0)
                    {
                        sb.AppendLine();
                    }
                    sb.Append($"Error extracting metadata for project \"{project.Key}\": {e.Message}");
                }
            }
            if (sb.Length > 0)
            {
                throw new ExtractMetadataException(sb.ToString());
            }
            return compilations;
        }
```

**Comment by michaelp** [comment]
```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildCompilationInfoFromScratchAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildCompilationInfoFromScratchAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetMetadataReferenceAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<FinalizeCompilationAsync>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<BuildCompilationInfoFromScratchAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetOrBuildCompilationInfoAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.CodeAnalysis.SolutionState.CompilationTracker.<GetCompilationSlowAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.DocAsCode.Metadata.ManagedReference.RoslynProject.<GetCompilationAsync>d__12.MoveNext() in C:\Users\michael.pavlovsky\Projects\docfx\src\Microsoft.DocAsCode.Metadata.ManagedReference.Roslyn\ExtractMetadata\Project\RoslynProject.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetProjectCompilationAsync>d__15.MoveNext() in C:\Users\michael.pavlovsky\Projects\docfx\src\Microsoft.DocAsCode.Metadata.ManagedReference\ExtractMetadataWorker.cs:line 432
```

**Comment by michaelp** [comment]
```csharp
 private async Task<SolutionState.CompilationTracker.CompilationInfo> FinalizeCompilationAsync(SolutionState solution, Compilation compilation, CancellationToken cancellationToken)
      {
        SolutionState.CompilationTracker.CompilationInfo compilationInfo;
        try
        {
          bool hasSuccessfullyLoaded = this.ProjectState.HasAllInformation;
          List<MetadataReference> newReferences = new List<MetadataReference>();
          Dictionary<MetadataReference, ProjectId> metadataReferenceToProjectId = new Dictionary<MetadataReference, ProjectId>();
          newReferences.AddRange((IEnumerable<MetadataReference>) this.ProjectState.MetadataReferences);
          foreach (ProjectReference projectReference1 in (IEnumerable<ProjectReference>) this.ProjectState.ProjectReferences)
          {
            ProjectReference projectReference = projectReference1;
            ProjectState projectState = solution.GetProjectState(projectReference.ProjectId);
            if (projectState != null)
            {
              if (projectState.IsSubmission)
              {
                compilation = compilation.WithScriptCompilationInfo(compilation.ScriptCompilationInfo.WithPreviousScriptCompilation(await solution.GetCompilationAsync(projectReference.ProjectId, cancellationToken).ConfigureAwait(false)));
              }
              else
              {
                MetadataReference key = await solution.GetMetadataReferenceAsync(projectReference, this.ProjectState, cancellationToken).ConfigureAwait(false);
                if (key != null)
                {
                  newReferences.Add(key);
                  metadataReferenceToProjectId.Add(key, projectReference.ProjectId);
                }
                else
                  hasSuccessfullyLoaded = false;
              }
            }
            projectReference = (ProjectReference) null;
          }
          compilation = this.UpdateCompilationWithNewReferencesAndRecordAssemblySymbols(compilation, newReferences, metadataReferenceToProjectId);
          this.WriteState((SolutionState.CompilationTracker.State) new SolutionState.CompilationTracker.FinalState(SolutionState.CompilationTracker.State.CreateValueSource(compilation, solution.Services), hasSuccessfullyLoaded), solution);
          compilationInfo = new SolutionState.CompilationTracker.CompilationInfo(compilation, hasSuccessfullyLoaded);
        }
        catch (Exception ex) when (Microsoft.CodeAnalysis.ErrorReporting.FatalError.ReportUnlessCanceled(ex))
        {
          throw ExceptionUtilities.Unreachable;
        }
        return compilationInfo;
      }
```

**Comment by rbbb** [comment]
To reproduce the issue, add a subtle double link to a reference project.

For example, go into a .csproj and copy paste a ProjectReference three times.

Or go into a .csproj and add a  reference to the project and the dll.

Or go into a .csproj and add a second reference to a project through an equivalent but different path, with an incorrect name and guid.

Roslyn needs clearer error reporting of those cases.

Hth, raph  (sgcib/far)

**Comment by vicancy** [comment]
@superyyrrzz Looks like a duplicate ProjectReference issue

**Comment by skini82** [comment]
Didn't worked for me :( Any other idea?
I'm on docfx 2.42.3.0

**Comment by superyyrrzz** [comment]
@skini82 We have a test case to generate document for a [sample csproj with duplicate project reference](https://github.com/dotnet/docfx/blob/a932308152152250273243968f1f5d161c23c0bd/test/docfx.Tests/Assets/test.csproj.sample.1#L37-L46), and it works fine. So now it is hard to reproduce this issue. Could you share your project?

**Comment by scott-ainsworth** [comment]
I have been chasing this issue trying to generate combined documentation for closely related projects. Finally tracked down the issue. One of the projects/assemblies ("P1") is intended to be used only by other assemblies within the same solution. So, all of its classes are internal and the other assemblies are allowed access via InternalsVisibleTo attributes.

Since there are no public classes in P1, All of its namespaces are discarded by the SymbolVisitorAdapter class. None of the namespaces make it into `allMembers` (`YamlMetadataResolver.ResolveMetadata()`), and thus are not included in `namespaces` (`YamlMetadataResolver.GenerateToc()` line 51). However, `namespaces` is ultimately source for namespaces. Ultimately, this leads to an attempt to add a namespace to `allReferences` when it is already there.

**Comment by filzrev** [comment]
>  all of its classes are internal and the other assemblies are allowed access via InternalsVisibleTo attributes.

I have tried to reproduce the problem with the latest version of docfx.
But I can't reproduce the problem.

@scott-ainsworth
Is it able to provide minimal project files that can reproduce problems?

**Comment by scott-ainsworth** [comment]
@filzrev, After much chopping, and whittling, I have a minimal version that reproduces the problem. Clone my [github DocFxUndefinedReferenceBugDemo repo](https://github.com/scott-ainsworth/DocFxUndefinedReferenceBugDemo) and run `build.ps1` from the repo root to demonstrate.

While some of what I wrote in my post above was a bit imprecise and rambling, it seems to come down to having a reference to a namespace without a corresponding definition. In my demo, it all happens in the single C# file below. The interface summary comment references `Datastore`, for which the compiler emits a "N:Root.Datastore" reference in the XML. However, nothing is defined in `Root.Datastore` (the interface is a child namespace). Thus, `Root.Datastore` makes it into `AllReferences` but without a definition in `Root.Datastore`, when `allMembers` is processed, the code that "walks up" the namespace tree attempts to add `Root.Datastore` to `AllReferences` again.


```[C#]
namespace Root.Datastore.Configuration;

/// <summary>
///   This interface defines an interface to inject the parameters required by
///   the <see cref="Datastore"/> module.
/// </summary>
public interface IDatastoreParameters {

	/// <summary>
	///   The database name.
	/// </summary>
	public string DatabaseName { get; }
}
```

**Comment by filzrev** [comment]
Thanks for detailed reports.

It seems exception occurred when following 3-conditions met.
1. Referencing **empty namespace** with `<see cref="">` tag.  
2. Using `"namespaceLayout": "nested"`
3. Using `"outputFormat": "mref"`

I'll try to create PR to fix this issue later.

**Comment by scott-ainsworth** [comment]
Glad I could help chase this one down.
