### ISSUE TITLE
docfx download throws exception

### ISSUE THREAD

**Issue by bitbonk** [dotnet/docfx#2805]
**DocFX Version Used**: 
docfx 2.35.4.0

**Steps to Reproduce**:

1. run `docfx download -x https://docs.microsoft.com/dotnet/xrefmap.yml`

**Expected Behavior**:
The xrefmap is downloaded so I can build my API documentation even when the internet is broken

**Actual Behavior**:
```
[18-05-22 09:39:30.415]Error:System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Phase name cannot be null or white space.
Parameter name: fileName
   at Microsoft.DocAsCode.Common.LoggerFileScope..ctor(String fileName)
   at Microsoft.DocAsCode.Build.Engine.XRefArchiveBuilder.<DownloadAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DocAsCode.SubCommands.DownloadCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) System.ArgumentException: Phase name cannot be null or white space.
Parameter name: fileName
   at Microsoft.DocAsCode.Common.LoggerFileScope..ctor(String fileName)
   at Microsoft.DocAsCode.Build.Engine.XRefArchiveBuilder.<DownloadAsync>d__3.MoveNext()<---

[18-05-22 09:39:30.424]Info:Completed in 46,1122 milliseconds


Build failed.
[18-05-22 09:39:30.431]Error:System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Phase name cannot be null or white space.
Parameter name: fileName
   at Microsoft.DocAsCode.Common.LoggerFileScope..ctor(String fileName)
   at Microsoft.DocAsCode.Build.Engine.XRefArchiveBuilder.<DownloadAsync>d__3.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DocAsCode.SubCommands.DownloadCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) System.ArgumentException: Phase name cannot be null or white space.
Parameter name: fileName
   at Microsoft.DocAsCode.Common.LoggerFileScope..ctor(String fileName)
   at Microsoft.DocAsCode.Build.Engine.XRefArchiveBuilder.<DownloadAsync>d__3.MoveNext()<---

        0 Warning(s)
        1 Error(s)
```

**Comment by superyyrrzz** [comment]
try this: `docfx download -x https://docs.microsoft.com/dotnet/xrefmap.yml xrefmap.zip`

I agree the error message should be improved...

**Comment by bitbonk** [comment]
`docfx download -x https://docs.microsoft.com/dotnet/xrefmap.yml xrefmap.zip` worked.

But it seems that docfx cannot handle this file when building.

I renamed that file to `docs.microsoft.com.20180530.zip` and put it on out local help server.
this is now in my docfx,json
```json
"xref": [
      "http://our.intranet.local/help/SomeLib/xrefmap.yml",
      "http://our.intranet.local/help/xrefmaps/docs.microsoft.com.20180530.zip"
```

When I build it I using 

`docfx -p 93200 --serve`

I get the following error:

> [18-05-30 01:38:21.429]Warning:[BuildCommand]Unable to download xref map file from "http://our.intranet.local/help/xrefmaps/docs.microsoft.com.20180530.zip", details: (Line: 1, Col: 6, Idx: 5) - (Line: 1, Col: 7, Idx: 6): While scanning for the next token, find character that cannot start any token.

**Comment by vwxyzh** [comment]
@bitbonk currently zip files are only supported in local.
