### ISSUE TITLE
Having an attribute with doulbe.MaxValue leads to System.OverflowException

### ISSUE THREAD

**Issue by jpelouse** [dotnet/docfx#288]
### Functional impact
The docfx-build step fails.

### Minimal repro steps
Having an attribute like `[RangeValidator(0.0, RangeBoundaryType.Inclusive, double.MaxValue, RangeBoundaryType.Inclusive)]` within the code.

### Expected result
Successfull documentation build step.

### Actual result
Exception occured and documentation build step failed:
```
Error: System.AggregateException: One or more errors occurred. ---> YamlDotNet.Core.YamlException: (Line: 85, Col: 14, Idx: 3360) - (Line: 85, Col: 35, Idx: 3381): Exception during deserialization ---> System.OverflowException: Value was either too large or too small for a Double.
 at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
 at YamlDotNet.Serialization.NodeDeserializers.ScalarNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 --- End of inner exception stack trace ---
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.DeserializeHelper[TItem](EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, ICollection`1 result)
 at (EventReader , Type , Func`3 , Object )
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.DeserializeHelper[TItem](EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, ICollection`1 result)
 at (EventReader , Type , Func`3 , Object )
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.DeserializeHelper[TItem](EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, ICollection`1 result)
 at (EventReader , Type , Func`3 , Object )
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.EmitGenericCollectionNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.<>c__DisplayClass2.<DeserializeValue>b__0(EventReader r, Type t)
 at Microsoft.DocAsCode.YamlSerialization.NodeDeserializers.ExtensibleObjectNodeDeserializer.YamlDotNet.Serialization.INodeDeserializer.Deserialize(EventReader reader, Type expectedType, Func`3 nestedObjectDeserializer, Object& value)
 at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(EventReader reader, Type type, IValueDeserializer deserializer)
 at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input, IValueDeserializer deserializer)
 at Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
 at Microsoft.DocAsCode.Build.ManagedReference.ManagedReferenceDocumentProcessor.Load(FileAndType file, ImmutableDictionary`2 metadata)
 at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Load(IDocumentProcessor processor, ImmutableDictionary`2 metadata, FileMetadata fileMetadata, FileAndType file)
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
 at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
 at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
 at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
 at System.Collections.Immutable.ImmutableList`1.FillFromEmpty(IEnumerable`1 items)
 at Microsoft.DocAsCode.Build.Engine.HostService.LoadCore(IEnumerable`1 models)
 at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.<>c__DisplayClass27_0.<GetInnerContexts>b__11(IGrouping`2 item)
 at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
 at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
 at System.Linq.Parallel.SpoolingTaskBase.Work()
 at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
 at System.Threading.Tasks.Task.Execute()
 --- End of inner exception stack trace ---
 at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
 at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
 at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(DocumentBuildParameters parameters)
 at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory)
 at Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
 at Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
 at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
```

**Comment by vwxyzh** [comment]
https://github.com/aaubry/YamlDotNet/issues/177

**Comment by vwxyzh** [comment]
The fix will release in v2,3
