### ISSUE TITLE
Incomplete restore crashes docfx

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3023]
# docfx crash report: System.NullReferenceException

docfx: `1.0.0`
cmd: `D:\docfx\src\docfx\bin\Release\netcoreapp2.1\docfx.dll restore D:\docs\azure-docs-pr`
cwd: `D:\docfx\src\docfx\bin\Release\netcoreapp2.1`
git: `git version 2.17.1.windows.2`

## repro steps

1. restore _azure-docs-pr_
2. close _cmd_ during the restore
3. restore _azure-docs-pr_ again

## callstack

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value)
   at Microsoft.Docs.Build.Restore.RestoreDependentRepo(String href, CommandLineOptions options, Action`1 restoreChild, HashSet`1 restoredDirs) in D:\docfx\src\docfx\restore\Restore.cs:line 58
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass2_0`1.<<ForEach>g__Run|0>d.MoveNext() in D:\docfx\src\docfx\lib\ParallelUtility.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Docs.Build.Program.Run(String[] args) in D:\docfx\src\docfx\cli\Program.cs:line 55
   at Microsoft.Docs.Build.Program.Main(String[] args) in D:\docfx\src\docfx\cli\Program.cs:line 21
```

## dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.0.4 [C:\Program Files\dotnet\sdk]
  1.1.0 [C:\Program Files\dotnet\sdk]
  2.0.0-preview2-006497 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.0.3 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.4 [C:\Program Files\dotnet\sdk]
  2.1.101 [C:\Program Files\dotnet\sdk]
  2.1.102 [C:\Program Files\dotnet\sdk]
  2.1.103 [C:\Program Files\dotnet\sdk]
  2.1.104 [C:\Program Files\dotnet\sdk]
  2.1.200 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0-preview2-25407-01 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by OsmondJiang** [comment]
this concurrency issue should be fixed,  but if the restored stopped in the half way and the restore repo is dirty, we just throw git error to end user, i believe it's acceptable.
