### ISSUE TITLE
TestConfigWithArrayFileMetadata randomly fail

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3056]
Test Name:	TestConfigWithArrayFileMetadata
Test FullName:	Microsoft.Docs.Build.ConfigTest.TestConfigWithArrayFileMetadata
Test Source:	D:\DevEnlists\Source\docfx\test\docfx.Test\config\ConfigTest.cs : line 52
Test Outcome:	Failed
Test Duration:	0:00:00.135

Result StackTrace:	
at Microsoft.Docs.Build.ConfigTest.AssertObjectEqual(Object expected, Object actual) in D:\DevEnlists\Source\docfx\test\docfx.Test\config\ConfigTest.cs:line 88
   at Microsoft.Docs.Build.ConfigTest.TestConfigWithArrayFileMetadata() in D:\DevEnlists\Source\docfx\test\docfx.Test\config\ConfigTest.cs:line 75
Result Message:	
Assert.Equal() Failure
                                 ↓ (pos 95)
Expected: ···:"value1"},"isGlob":true},{"include":["folder21/**","folder22···
Actual:   ···:"value1"},"isGlob":false},{"include":["folder21/**","folder2···
                                 ↑ (pos 95)

**Comment by superyyrrzz** [comment]
This may be caused by some test conflicts, but still can't reproduce this on my machine, and can't find the root cause in the current implementation.

**Comment by live1206** [comment]
I got this failure locally from time to time as well
