### ISSUE TITLE
Impact CI failure caused by too big size of azure-docs-pr outputs

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#3134]
as title

**Comment by OsmondJiang** [comment]
I have changed the CI to avoid to init azure-docs-pr submodule, reduce the size. So the CI is not blocking right now, seems we need build our own CI machine to run azure impact test

**Comment by OsmondJiang** [comment]
JINT failed.

# docfx crash report: System.AggregateException

docfx: `1.0.0`
cmd: `D:\DevEnlists\Source\docfx\src\docfx\bin\Release\netcoreapp2.1\docfx.dll build D:\DevEnlists\Source\docfx-impact\source\edge-developer -o D:\DevEnlists\Source\docfx-impact\source\edge-developer.output --legacy`
cwd: `D:\DevEnlists\Source\docfx\src\docfx`
git: `git version 2.17.1.windows.2`

## repro steps

## callstack

```
System.AggregateException: One or more errors occurred. (value is undefined) ---> Jint.Runtime.JavaScriptException: value is undefined
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Microsoft.Docs.Build.Jint.<>c__DisplayClass4_0.<LoadTransform>b__0(JObject model) in D:\DevEnlists\Source\docfx\src\docfx\build\legacy\metadata\Jint.cs:line 43
   at Microsoft.Docs.Build.LegacyMarkdown.Convert(Docset docset, Context context, Document doc, LegacyManifestOutput legacyManifestOutput, TableOfContentsMap tocMap) in D:\DevEnlists\Source\docfx\src\docfx\build\legacy\files\LegacyMarkdown.cs:line 19
   at Microsoft.Docs.Build.LegacyOutput.<>c__DisplayClass0_0.<Convert>b__0(ValueTuple`2 file) in D:\DevEnlists\Source\docfx\src\docfx\build\legacy\files\LegacyOutput.cs:line 31
   at System.Threading.Tasks.Parallel.<>c__DisplayClass33_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.Docs.Build.LegacyOutput.Convert(Docset docset, Context context, List`1 files, TableOfContentsMap tocMap) in D:\DevEnlists\Source\docfx\src\docfx\build\legacy\files\LegacyOutput.cs:line 32
   at Microsoft.Docs.Build.Legacy.ConvertToLegacyModel(Docset docset, Context context, List`1 documents, DependencyMap dependencyMap, TableOfContentsMap tocMap) in D:\DevEnlists\Source\docfx\src\docfx\build\legacy\Legacy.cs:line 26
   at Microsoft.Docs.Build.Build.Run(String docsetPath, CommandLineOptions options, Report report) in D:\DevEnlists\Source\docfx\src\docfx\build\Build.cs:line 35
   at Microsoft.Docs.Build.Program.Run(String[] args) in D:\DevEnlists\Source\docfx\src\docfx\cli\Program.cs:line 60
   at Microsoft.Docs.Build.Program.Main(String[] args) in D:\DevEnlists\Source\docfx\src\docfx\cli\Program.cs:line 22
---> (Inner Exception #0) TypeError: value is undefined<---

```

## dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.300
 Commit:    adab45bf0c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17134
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.300\

Host (useful for support):
  Version: 2.1.0
  Commit:  caa7b7e2ba

.NET Core SDKs installed:
  1.0.3 [C:\Program Files\dotnet\sdk]
  1.0.4 [C:\Program Files\dotnet\sdk]
  2.0.0 [C:\Program Files\dotnet\sdk]
  2.0.2 [C:\Program Files\dotnet\sdk]
  2.1.2 [C:\Program Files\dotnet\sdk]
  2.1.201 [C:\Program Files\dotnet\sdk]
  2.1.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.0.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by OsmondJiang** [comment]
@superyyrrzz  is working on the JINT.
