### ISSUE TITLE
docfx crushed while running impact test

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#3210]
## repro steps
npm run impact azure-docs-pr

## callstack

```
System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.String'.) ---> System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.String'.
   at Microsoft.Docs.Build.LegacyMarkdown.Convert(Docset docset, Context context, Document doc, LegacyManifestOutput legacyManifestOutput, TableOfContentsMap tocMap) in C:\src\docfx\src\docfx\build\legacy\files\LegacyMarkdown.cs:line 19
   at Microsoft.Docs.Build.LegacyOutput.<>c__DisplayClass0_0.<Convert>b__3(ValueTuple`2 file) in C:\src\docfx\src\docfx\build\legacy\files\LegacyOutput.cs:line 23
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.Docs.Build.LegacyOutput.Convert(Docset docset, Context context, List`1 files, TableOfContentsMap tocMap) in C:\src\docfx\src\docfx\build\legacy\files\LegacyOutput.cs:line 23
   at Microsoft.Docs.Build.Legacy.ConvertToLegacyModel(Docset docset, Context context, List`1 documents, DependencyMap dependencyMap, TableOfContentsMap tocMap) in C:\src\docfx\src\docfx\build\legacy\Legacy.cs:line 26
   at Microsoft.Docs.Build.Build.Run(String docsetPath, CommandLineOptions options, Report report) in C:\src\docfx\src\docfx\build\Build.cs:line 35
   at Microsoft.Docs.Build.Program.Run(String[] args) in C:\src\docfx\src\docfx\cli\Program.cs:line 60
   at Microsoft.Docs.Build.Program.Main(String[] args) in C:\src\docfx\src\docfx\cli\Program.cs:line 22
---> (Inner Exception #0) System.InvalidCastException: Unable to cast object of type 'Newtonsoft.Json.Linq.JObject' to type 'System.String'.
   at Microsoft.Docs.Build.LegacyMarkdown.Convert(Docset docset, Context context, Document doc, LegacyManifestOutput legacyManifestOutput, TableOfContentsMap tocMap) in C:\src\docfx\src\docfx\build\legacy\files\LegacyMarkdown.cs:line 19
   at Microsoft.Docs.Build.LegacyOutput.<>c__DisplayClass0_0.<Convert>b__3(ValueTuple`2 file) in C:\src\docfx\src\docfx\build\legacy\files\LegacyOutput.cs:line 23
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

**Comment by live1206** [comment]
After consolidation of SDP and markdown #3113  , we got this issue while converting legacy markdown.
@yufeih could you help take a look?
