### ISSUE TITLE
Error extracting metadata from a generic type attribute

### ISSUE THREAD

**Issue by xen2** [dotnet/docfx#3819]
I have some issues with docfx running on our project (Xenko).
The issue seems to be due to a symbol having trouble to resolve `ErrorType ValueTuple<?>` which fail due to ErrorInfo `error CS0246: The type or namespace name 'ValueTuple<>' could not be found (are you missing a using directive or an assembly reference?)`.

I can avoid the issue by changing in `NameVisitor.cs` (2 occurences):
`if (!symbol.ContainingNamespace.IsGlobalNamespace)`
to 
`if (symbol.ContainingNamespace != null && !symbol.ContainingNamespace.IsGlobalNamespace)`

Not sure yet if due to our custom build system or something specific missing in assembly/type resolution.
Note: it also hits some Debug.Assert later.

Might be related to another issue I previously filled: #268

**DocFX Version Used**:  2.40.6

**Steps to Reproduce**:

Sorry I couldn't repro it in a smaller project, so here we go:

1.  Checkout https://github.com/xenko3d/xenko
2.  Checkout https://github.com/xenko3d/xenko-docs
Note: they should be side-by-side (a top folder contains both `xenko` and `xenko-docs`)
3. Go in `xenko-docs` folder
4. Run `docfx metadata en/docfx.json` (please use official docfx or run docfx from source to debug, using working directory `xenko-docs` and parameters `metadata en/docfx.json`)
note: `deps\docfx\docfx` is already patched with the fix previously mentionned.

**Expected Behavior**:

docfx works without error

**Actual Behavior**:

```
[18-12-25 09:20:06.171]Error:Error extracting metadata for C:/DEV/xenko/sources/assets/Xenko.Core.Assets/Xenko.Core.Assets.csproj,C:/DEV/xenko/sources/core/Xenko.Core/Xenko.Core.csproj,C:/DEV/xenko/sources/core/Xenko.Core.IO/Xenko.Core.IO.csproj,C:/DEV/xenko/sources/core/Xenko.Core.Mathematics/Xenko.Core.Mathematics.csproj,C:/DEV/xenko/sources/core/Xenko.Core.MicroThreading/Xenko.Core.MicroThreading.csproj,C:/DEV/xenko/sources/core/Xenko.Core.Serialization/Xenko.Core.Serialization.csproj,C:/DEV/xenko/sources/engine/Xenko/Xenko.csproj,C:/DEV/xenko/sources/engine/Xenko.Audio/Xenko.Audio.csproj,C:/DEV/xenko/sources/engine/Xenko.Engine/Xenko.Engine.csproj,C:/DEV/xenko/sources/engine/Xenko.Games/Xenko.Games.csproj,C:/DEV/xenko/sources/engine/Xenko.Graphics/Xenko.Graphics.csproj,C:/DEV/xenko/sources/engine/Xenko.Input/Xenko.Input.csproj,C:/DEV/xenko/sources/engine/Xenko.Navigation/Xenko.Navigation.csproj,C:/DEV/xenko/sources/engine/Xenko.Particles/Xenko.Particles.csproj,C:/DEV/xenko/sources/engine/Xenko.Physics/Xenko.Physics.csproj,C:/DEV/xenko/sources/engine/Xenko.Shaders/Xenko.Shaders.csproj,C:/DEV/xenko/sources/engine/Xenko.UI/Xenko.UI.csproj,C:/DEV/xenko/sources/engine/Xenko.VirtualReality/Xenko.VirtualReality.csproj: Microsoft.DocAsCode.Exceptions.DocfxException: Unable to generate spec reference for !:ValueTuple{} ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.NameVisitorCreator.GetName(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSReferenceItemVisitor.AddLinkItems(INamedTypeSymbol symbol, Boolean withGenericeParameter)
```

**Comment by superyyrrzz** [comment]
DocFX supports `ValueTuple` since 2.39.0. Is your issue resolved after upgrading from 2.37.2 to 2.40.6?

**Comment by xen2** [comment]
Yes sorry, I had the bug with 2.40.6
Please use the official release or build from source, I replaced with a patched one in `xenko-docs` for now

**Comment by xen2** [comment]
Sorry if not clear, I meant yes I still had the bug with 2.40.6.
Issue is **not** resolved with 2.40.6.

**Comment by superyyrrzz** [comment]
@xen2 Sorry for misunderstanding. I just reopen it.

**Comment by herohua** [comment]
@xen2 , sorry I cannot repro with latest DocFX built from `dev` branch - although I see many warnings running against your repos.

`        544 Warning(s)
         0 Error(s)`

Is it possible for you to try it again with 2.40.7 or the latest one built from `dev` branch?
