### ISSUE TITLE
Docfx crash when running on linux using NuGet package

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3867]
install using `dotnet tool install -g` failed with:

```
The settings file in the tool's NuGet package is invalid: Failed to retrieve tool configuration: Could not find a part of the path '/root/.dotnet/tools/.store/docfx/3.0.0-alpha-head-00560-33f03166e/docfx/3.0.0-alpha-HEAD-00560-33f03166e/tools/netcoreapp2.1/any/DotnetToolSettings.xml'.
Tool 'docfx' failed to install. Please contact the tool author for assistance.
```

use `dotnet run` failed with:

```
System.TypeInitializationException: The type initializer for 'Microsoft.Docs.Build.LibGit2' threw an exception. ---> System.DllNotFoundException: Unable to load shared library 'git2-8e0b172' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-8e0b172: cannot open shared object file: No such file or directory
   at Microsoft.Docs.Build.LibGit2.git_libgit2_init()
   at Microsoft.Docs.Build.LibGit2..cctor() in D:\work\1\s\src\docfx\lib\git\LibGit2.cs:line 20
   --- End of inner exception stack trace ---
   at Microsoft.Docs.Build.LibGit2.git_repository_open(IntPtr& repo, String path)
   at Microsoft.Docs.Build.GitUtility.GetRepoInfo(String repoPath) in D:\work\1\s\src\docfx\lib\git\GitUtility.cs:line 67
   at Microsoft.Docs.Build.Repository.Create(String path) in D:\work\1\s\src\docfx\docset\Repository.cs:line 36
   at Microsoft.Docs.Build.LocalizationConvention.TryGetSourceRepository(String docsetPath, String& sourceRemote, String& sourceBranch, String& locale) in D:\work\1\s\src\docfx\localization\LocalizationConvention.cs:line 114
   at Microsoft.Docs.Build.LocalizationConvention.GetBuildLocale(String docset, CommandLineOptions options) in D:\work\1\s\src\docfx\localization\LocalizationConvention.cs:line 350
   at Microsoft.Docs.Build.Restore.Run(String docsetPath, CommandLineOptions options, Report report, Boolean implicit) in D:\work\1\s\src\docfx\restore\Restore.cs:line 24
   at Microsoft.Docs.Build.Program.Run(String[] args) in D:\work\1\s\src\docfx\cli\Program.cs:line 56
   at Microsoft.Docs.Build.Program.Main(String[] args) in D:\work\1\s\src\docfx\cli\Program.cs:line 22
```

**Comment by yufeih** [comment]
This seems to only occur in ubuntu on Windows

**Comment by yufeih** [comment]
Close this as it does not occur on the linux container we want to support.
