### ISSUE TITLE
Docfx crash when run on linux container

### ISSUE THREAD

**Issue by wumingcp** [dotnet/docfx#3895]
# docfx crash report: System.AggregateException

docfx: `3.0.0-beta-00576-7290eb9b5`
x64: `True`
cmd: `/root/.dotnet/tools/.store/docfx/3.0.0-beta-00576-7290eb9b5/docfx/3.0.0-beta-00576-7290eb9b5/tools/netcoreapp2.1/any/docfx.dll build --legacy .`
cwd: `/agent/azure-docs-pr`
git: `git version 2.11.0`
DOCFX_GLOBAL_CONFIG_PATH: `/agent/Authorization.json`

## callstack

```
System.AggregateException: One or more errors occurred. (obj is null) ---> Jint.Runtime.JavaScriptException: obj is null
   at Jint.Native.Function.ScriptFunctionInstance.Call(JsValue thisArg, JsValue[] arguments)
   at Microsoft.Docs.Build.JavaScript.<>c__DisplayClass5_0.<LoadTransform>b__0(JObject model) in D:\work\1\s\src\docfx\build\legacy\template\Javascript.cs:line 45
   at Microsoft.Docs.Build.LegacyMetadata.GenerateLegacyRawMetadata(PageModel pageModel, String content, Document file, String group) in D:\work\1\s\src\docfx\build\legacy\metadata\LegacyMetadata.cs:line 71
   at Microsoft.Docs.Build.LegacyPage.Convert(Docset docset, Context context, Document doc, LegacyManifestItem legacyManifestItem)
   at Microsoft.Docs.Build.LegacyOutput.<>c__DisplayClass0_0.<Convert>b__3(ValueTuple`3 file) in D:\work\1\s\src\docfx\build\legacy\files\LegacyOutput.cs:line 27
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 32
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.Docs.Build.ParallelUtility.ForEach[T](IEnumerable`1 source, Action`1 action, Action`2 progress) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 34
   at Microsoft.Docs.Build.LegacyOutput.Convert(Docset docset, Context context, List`1 files) in D:\work\1\s\src\docfx\build\legacy\files\LegacyOutput.cs:line 25
   at Microsoft.Docs.Build.Legacy.ConvertToLegacyModel(Docset docset, Context context, Dictionary`2 fileManifests, DependencyMap dependencyMap, TableOfContentsMap tocMap) in D:\work\1\s\src\docfx\build\legacy\Legacy.cs:line 25
   at Microsoft.Docs.Build.Build.Run(String docsetPath, CommandLineOptions options, Report report) in D:\work\1\s\src\docfx\build\Build.cs:line 47
   at Microsoft.Docs.Build.Program.Run(String[] args) in D:\work\1\s\src\docfx\cli\Program.cs:line 61
   at Microsoft.Docs.Build.Program.Main(String[] args) in D:\work\1\s\src\docfx\cli\Program.cs:line 22
---> (Inner Exception #0) TypeError: obj is null<---

```

## dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.102
 Commit:    96ff75a873

Runtime Environment:
 OS Name:     debian
 OS Version:  9
 OS Platform: Linux
 RID:         debian.9-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.102/

Host (useful for support):
  Version: 2.2.1
  Commit:  878dd11e62

.NET Core SDKs installed:
  2.2.102 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by yufeih** [comment]
js callstack

```
TypeError: obj is null
 at getContribInfo(model) @ C:\Users\yufeih\.docfx\git\github.com+Microsoft+template..ocs.msft+95403dd1\master-eb0a1917-d574be0a358498d5693fd41529441756ec70ea24\ContentTemplate\conceptual.mta.json.js 1:42
```

**Comment by yufeih** [comment]
Jint bug fixed.
