### ISSUE TITLE
git clone failed without any detail info

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#3921]
https://ceapex.visualstudio.com/Engineering/_build/results?buildId=34692

```
2019-01-15T04:10:23.6905395Z Failed   Microsoft.Docs.Build.E2ETest.Run(name: "restore/11. Restored repo should be always retriev"...)
2019-01-15T04:10:23.7734028Z Error Message:
2019-01-15T04:10:23.7762116Z  ["error","git-clone-failed","Cloning git repository 'https://docs.com/restore/x' ('child', 'child-a') failed."]
2019-01-15T04:10:23.8504326Z 
2019-01-15T04:10:23.9030198Z Expected: True
2019-01-15T04:10:23.9030375Z Actual:   False
2019-01-15T04:10:23.9030988Z Stack Trace:
2019-01-15T04:10:23.9031447Z    at Microsoft.Docs.Build.E2ETest.RunCore(String docsetPath, E2ESpec spec) in D:\a\1\s\test\docfx.Test\e2e\E2ETest.cs:line 107
2019-01-15T04:10:23.9031532Z    at Microsoft.Docs.Build.E2ETest.Run(String name) in D:\a\1\s\test\docfx.Test\e2e\E2ETest.cs:line 68
2019-01-15T04:10:23.9031617Z --- End of stack trace from previous location where exception was thrown ---
```

**Comment by OsmondJiang** [comment]
https://ceapex.visualstudio.com/Engineering/_build/results?buildId=36745
