### ISSUE TITLE
legacy test failing on CI

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#3965]
Failed   Microsoft.Docs.Build.E2ETest.Run(name: "legacy/00. Build with --legacy")
2019-01-23T10:18:33.3067410Z Error Message:
2019-01-23T10:18:33.3068030Z  System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
2019-01-23T10:18:33.3069220Z ---- System.NullReferenceException : Object reference not set to an instance of an object.
2019-01-23T10:18:33.3069960Z Stack Trace:
2019-01-23T10:18:33.3070430Z    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
2019-01-23T10:18:33.3070920Z    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
2019-01-23T10:18:33.3072080Z --- End of stack trace from previous location where exception was thrown ---
2019-01-23T10:18:33.3072430Z    at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
2019-01-23T10:18:33.3072740Z    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
2019-01-23T10:18:33.3073320Z    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
2019-01-23T10:18:33.3073590Z    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
2019-01-23T10:18:33.3073950Z    at Microsoft.Docs.Build.ParallelUtility.ForEach[T](IEnumerable`1 source, Action`1 action, Action`2 progress)
2019-01-23T10:18:33.3074480Z    at Microsoft.Docs.Build.LegacyOutput.Convert(Docset docset, Context context, List`1 files)
2019-01-23T10:18:33.3074780Z    at Microsoft.Docs.Build.Legacy.ConvertToLegacyModel(Docset docset, Context context, Dictionary`2 fileManifests, DependencyMap dependencyMap, TableOfContentsMap tocMap)
2019-01-23T10:18:33.3075260Z    at Microsoft.Docs.Build.Build.Run(String docsetPath, CommandLineOptions options, Report report)
2019-01-23T10:18:33.3075690Z    at Microsoft.Docs.Build.Program.Run(String[] args)
2019-01-23T10:18:33.3076010Z    at Microsoft.Docs.Build.E2ETest.RunCore(String docsetPath, E2ESpec spec) in /Users/vsts/agent/2.144.0/work/1/s/test/docfx.Test/e2e/E2ETest.cs:line 87
2019-01-23T10:18:33.3076540Z    at Microsoft.Docs.Build.E2ETest.Run(String name) in /Users/vsts/agent/2.144.0/work/1/s/test/docfx.Test/e2e/E2ETest.cs:line 68
2019-01-23T10:18:33.3077790Z --- End of stack trace from previous location where exception was thrown ---
2019-01-23T10:18:33.3078540Z ----- Inner Stack Trace -----
2019-01-23T10:18:33.3078660Z    at Microsoft.Docs.Build.LegacyMetadata.GenerateLegacyRawMetadata(PageModel pageModel, Document file)
2019-01-23T10:18:33.3078920Z    at Microsoft.Docs.Build.LegacyPage.Convert(Docset docset, Context context, Document doc, LegacyManifestItem legacyManifestItem)
2019-01-23T10:18:33.3079520Z    at Microsoft.Docs.Build.LegacyOutput.<>c__DisplayClass0_0.<Convert>b__3(ValueTuple`3 file)
2019-01-23T10:18:33.3079870Z    at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item)
2019-01-23T10:18:33.3080240Z    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
2019-01-23T10:18:33.3081390Z --- End of stack trace from previous location where exception was thrown ---
2019-01-23T10:18:33.3082570Z    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
2019-01-23T10:18:33.3083490Z    at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
2019-01-23T10:18:33.3084040Z    at System.Threading.Tasks.TaskReplicator.Replica.Execute()

**Comment by live1206** [comment]
https://ceapex.visualstudio.com/Engineering/_build/results?buildId=36394
