### ISSUE TITLE
calling docfx build on my DLL fails with System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Chris3606** [dotnet/docfx#4107]
**DocFX Version Used**: 2.40.11.0

**Template used**: `default`

**Steps to Reproduce**:
DLL, xml documentation file, and corresponding pdb file, as well as the project's docfx configuration are in the attached zip file.

1. In the GoRogue.Docs folder contained within the attached .zip file, run docfx --build

**Expected Behavior**: Docfx will generate API documentation using the dll and xml file in the src directory

**Actual Behavior**: A System.NullReferenceException is encountered:
```
[19-03-05 01:54:27.461]Info:Config file docfx.json found, start generating metadata...
[19-03-05 01:54:27.724]Info:[MetadataCommand.ExtractMetadata]Environment variable VSINSTALLDIR is set to C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\, it is used as the inner compiler.
[19-03-05 01:54:28.273]Info:[MetadataCommand.ExtractMetadata]Loading projects...
[19-03-05 01:54:28.292]Info:[MetadataCommand.ExtractMetadata]Generating metadata for each project...
[19-03-05 01:54:31.040]Info:[MetadataCommand]Completed Scope:MetadataCommand in 3326.0107 milliseconds.
[19-03-05 01:54:31.044]Error:Error extracting metadata for D:/Zip/Extracted/Path/GoRogue.Docs/src/GoRogue.dll: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitMethod(IMethodSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.NameVisitorCreator.GetName(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.DefaultVisit(ISymbol symbol, MetadataItem item, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.DefaultVisit(ISymbol symbol, MetadataItem item, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.DefaultVisit(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.GetYamlItem(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitMethod(IMethodSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.RoslynMetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.GetMetadataFromProjectLevelCache(IBuildController controller, IInputParameters key)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
[19-03-05 01:54:31.057]Info:Completed in 3349.9376 milliseconds


Build failed.
[19-03-05 01:54:31.067]Error:Error extracting metadata for D:/Zip/Extracted/Path/GoRogue.Docs/src/GoRogue.dll: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitMethod(IMethodSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.NameVisitorCreator.GetName(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.DefaultVisit(ISymbol symbol, MetadataItem item, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.DefaultVisit(ISymbol symbol, MetadataItem item, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.DefaultVisit(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.GetYamlItem(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitMethod(IMethodSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.RoslynMetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.GetMetadataFromProjectLevelCache(IBuildController controller, IInputParameters key)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
        0 Warning(s)
        1 Error(s)
```

[GoRogue.Docs.zip](https://github.com/dotnet/docfx/files/2928959/GoRogue.Docs.zip)

**Comment by superyyrrzz** [comment]
@Chris3606 Thank you for detailed repro steps. I created #4482 to fix this.

This may be the same with #3177. You can nuget restore first to resolve this issue. #3228 also provide a config to reference a dependent DLL in the `references` section.
