### ISSUE TITLE
Duplicate param/@name in XML causes NullReferenceException

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [dotnet/docfx#4165]
**Operation System**: Windows

**DocFX Version Used**: 2.40.12.0

**Template used**: `default`

**Steps to Reproduce**:

1. Extract the files from the attached [docfx_project.zip](https://github.com/dotnet/docfx/files/2967276/docfx_project.zip), in which the important part is this `bin/DuplicateParam.xml`:
   ```xml
   <?xml version="1.0"?>
   <doc>
       <assembly>
           <name>DuplicateParam</name>
       </assembly>
       <members>
           <member name="T:DuplicateParam.Program">
               <summary>Probes error handling in DocFX.</summary>
           </member>
           <member name="M:DuplicateParam.Program.Main(System.String[])">
               <param name="args">Command-line arguments.</param>
               <param name="args">Duplicate documentation for the same parameter.</param>
           </member>
       </members>
   </doc>
   ````
2. Run `docfx metadata`.

**Expected Behavior**:

Metadata extraction succeeds, possibly with a warning about the duplicate param element.

**Actual Behavior**:

NullReferenceException is thrown:

```
[19-03-14 03.45.10.324]Info:Config file docfx.json found, start generating metadata...
[19-03-14 03.45.10.544]Info:[ExtractMetadata]Environment variable VSINSTALLDIR is set to C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\, it is used as the inner compiler.
[19-03-14 03.45.10.802]Info:[ExtractMetadata]Loading projects...
[19-03-14 03.45.10.816]Info:[ExtractMetadata]Generating metadata for each project...
[19-03-14 03.45.12.131]Info:[ExtractMetadata]Loading developer comments from file: C:/Projects/Kalle/duplicate_param/docfx_project/bin/DuplicateParam.xml
[19-03-14 03.45.12.198]Error:Error extracting metadata for C:/Projects/Kalle/duplicate_param/docfx_project/bin/DuplicateParam.exe: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.GetListContent(XPathNavigator navigator, String xpath, String contentType, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel..ctor(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.CreateModel(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MergeCommentsHelper.PatchViewModel(MetadataItem item, String comment)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MergeCommentsHelper.PatchMetadataItem(MetadataItem assembly, IEnumerable`1 list)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MergeCommentsHelper.MergeComments(MetadataItem item, IEnumerable`1 commentFiles)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
[19-03-14 03.45.12.204]Info:Completed in 1670,0582 milliseconds


Build failed.
[19-03-14 03.45.12.214]Error:Error extracting metadata for C:/Projects/Kalle/duplicate_param/docfx_project/bin/DuplicateParam.exe: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.GetListContent(XPathNavigator navigator, String xpath, String contentType, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel..ctor(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.CreateModel(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MergeCommentsHelper.PatchViewModel(MetadataItem item, String comment)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MergeCommentsHelper.PatchMetadataItem(MetadataItem assembly, IEnumerable`1 list)
   at Microsoft.DocAsCode.Metadata.ManagedReference.MergeCommentsHelper.MergeComments(MetadataItem item, IEnumerable`1 commentFiles)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
        0 Warning(s)
        1 Error(s)
```

**Comment by KalleOlaviNiemitalo** [comment]
One of our projects actually hit this error, and the cause of the NullReferenceException was not easy to find.

**Comment by KalleOlaviNiemitalo** [comment]
I debugged this several weeks ago and I think the problem was that, when [`TripleSlashCommentModel.GetListContent` evaluated `context.Source.Remote`](https://github.com/dotnet/docfx/blob/v2.40.12/src/Microsoft.DocAsCode.Metadata.ManagedReference.Common/Parsers/TripleSlashCommentModel.cs#L406) to log a warning about the duplicate `param` element,  `context.Source` was `null` because DocFX had not read the `param` element from a C# source file. My memory may be wrong, though.

**Comment by agent00jackson** [comment]
I also encountered this issue. Would not have figured out the cause of the exception if it wasn't for this issue.
