### ISSUE TITLE
Flaky test: "restore/14. restore with azure repo dependency loc"

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4204]
```
Starting test execution, please wait...
[xUnit.net 00:00:09.45]     Microsoft.Docs.Build.E2ETest.Run(name: "restore/14. restore with azure repo dependency loc"...) [FAIL]
Failed   Microsoft.Docs.Build.E2ETest.Run(name: "restore/14. restore with azure repo dependency loc"...)
Error Message:
 Assert.Equal() Failure
                                     (pos 55)
Expected: ···3333\n</p>\n<p>\n  2333\n</p>\n
Actual:   ···3333\n</p>\n<p>\n  233333\n</p>\n
                                     (pos 55)
Stack Trace:
   at Microsoft.Docs.Build.TestUtility.VerifyJsonContainEquals(JToken expected, JToken actual, String parentKey) in D:\docfx\test\docfx.Test\common\TestUtility.cs:line 52
   at Microsoft.Docs.Build.TestUtility.VerifyJsonContainEquals(JToken expected, JToken actual, String parentKey) in D:\docfx\test\docfx.Test\common\TestUtility.cs:line 40
   at Microsoft.Docs.Build.E2ETest.VerifyFile(String file, String content) in D:\docfx\test\docfx.Test\e2e\E2ETest.cs:line 384
   at Microsoft.Docs.Build.E2ETest.RunCore(String docsetPath, E2ESpec spec) in D:\docfx\test\docfx.Test\e2e\E2ETest.cs:line 141
   at Microsoft.Docs.Build.E2ETest.Run(String name) in D:\docfx\test\docfx.Test\e2e\E2ETest.cs:line 82
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by OsmondJiang** [comment]
local run or CI run, @yufeih ?
