### ISSUE TITLE
docfx crashed when metadata(yaml header) is not valid

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4325]
Help us improve by creating an issue at https://github.com/dotnet/docfx:
    
    
    # docfx crash report: System.AggregateException
    
    docfx: `3.0.0-beta-00794-e906e139a`
    x64: `True`
    cmd: `W:\uur4-s\.optemp\packages\docfx.3.0.0-beta-00794-e906e139a\tools\netcoreapp2.2\any\docfx.dll build W:\uur4-s -o W:\uur4-o-a44b0aa7 --legacy --verbose`
    cwd: `E:\approot\build`
    git: `git version 2.19.2.windows.1`
    DOCFX_APPDATA_PATH: `T:\appdata`
    DOCFX_GLOBAL_CONFIG_PATH: `T:\znw12ppa.eef.json`
    DOCFX_REPOSITORY_BRANCH: `docfx-v3-e2e-test-sxs`
    DOCFX_REPOSITORY_URL: `https://github.com/OPS-E2E-PPE/azure-docs-pr.cs-cz`
    
    ## repro steps
    
    ## callstack
    
    ```
    System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.Docs.Build.XrefMap.Load(Context context, ConcurrentDictionary`2 xrefsByUid, Document file) in D:\work\1\s\src\docfx\build\xref\XrefMap.cs:line 295
       at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 32
       at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
       at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
       at System.Threading.Tasks.TaskReplicator.Replica.Execute()
       --- End of inner exception stack trace ---
       at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
       at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
       at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
       at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
       at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
       at Microsoft.Docs.Build.ParallelUtility.ForEach[T](IEnumerable`1 source, Action`1 action, Action`2 progress) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 34
       at Microsoft.Docs.Build.XrefMap.CreateInternalXrefMap(Context context, IEnumerable`1 files) in D:\work\1\s\src\docfx\build\xref\XrefMap.cs:line 267
       at Microsoft.Docs.Build.XrefMap.Create(Context context, Docset docset) in D:\work\1\s\src\docfx\build\xref\XrefMap.cs:line 156
       at Microsoft.Docs.Build.Build.Run(String docsetPath, Repository repository, String locale, CommandLineOptions options, Report report, DependencyLockModel dependencyLock, RestoreMap restoreMap) in D:\work\1\s\src\docfx\build\Build.cs:line 51
       at Microsoft.Docs.Build.Build.Run(String docsetPath, CommandLineOptions options, Report report) in D:\work\1\s\src\docfx\build\Build.cs:line 27
       at Microsoft.Docs.Build.Program.Run(String[] args) in D:\work\1\s\src\docfx\cli\Program.cs:line 76
       at Microsoft.Docs.Build.Program.Main(String[] args) in D:\work\1\s\src\docfx\cli\Program.cs:line 22
    ---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
       at Microsoft.Docs.Build.XrefMap.Load(Context context, ConcurrentDictionary`2 xrefsByUid, Document file) in D:\work\1\s\src\docfx\build\xref\XrefMap.cs:line 295
       at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 32
       at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
       at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
       at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
    
    ```

Page Content: https://github.com/OPS-E2E-PPE/azure-docs-pr.cs-cz/blob/docfx-v3-e2e-test-sxs/articles/virtual-network/virtual-network-tcpip-performance-tuning.md

**Comment by OsmondJiang** [comment]
It's related to the error handling for SourceInfoJsonConverter, @live1206  @yufeih
