### ISSUE TITLE
Docfx restore crashed when dependency repo doesn't exist

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4400]
We should not crashed, just return -1 and report errors in build report.

**Comment by OsmondJiang** [comment]
```
[2019-04-17 06:48:35.133533Z]: Use docfx v3 to restore
    [2019-04-17 06:48:35.133533Z]: Executing C:\Resources\directory\c9e3f57272734f7a8397544e96a6f7fd.V3WorkerRole2.NetCoreInstall\dotnet\dotnet.exe W:\yuh3-s\.optemp\packages\docfx.3.0.0-beta-00813-5625fea19\tools\netcoreapp2.2\any\docfx.dll restore W:\yuh3-s --verbose
    Using docfx 3.0.0-beta-00813-5625fea19
    Restore dependencies...
Restore dependencies done in 1.61s
    Microsoft.Docs.Build.DocfxException: Cloning git repository 'https://github.com/OPS-E2E-PPE/IntuneEDU-docfxv3' ('master') failed. ---> System.InvalidOperationException: '"git" -c http.https://github.com.extraheader="Authorization: basic NGI3YTY0YWNkZDU1MTI4ZGRlNWMyMWRhZjA2Yjk0NDE1YTg0YzMyMA==" fetch --tags --progress --update-head-ok --prune --depth 9999999999 "https://github.com/OPS-E2E-PPE/IntuneEDU-docfxv3" +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/*' failed in directory 'T:\appdata\git2\github.com+OPS-E2E-PPE+IntuneED..-docfxv3+bef4fb42\.git' with exit code 128: 
    STDOUT:''
       at Microsoft.Docs.Build.ProcessUtility.Execute(String fileName, String commandLineArgs, String cwd, Boolean stdout) in D:\work\1\s\src\docfx\lib\ProcessUtility.cs:line 202
       at Microsoft.Docs.Build.GitUtility.Execute(String cwd, String commandLineArgs, Boolean stdout) in D:\work\1\s\src\docfx\lib\git\GitUtility.cs:line 346
       at Microsoft.Docs.Build.GitUtility.ExecuteNonQuery(String cwd, String commandLineArgs) in D:\work\1\s\src\docfx\lib\git\GitUtility.cs:line 335
       at Microsoft.Docs.Build.GitUtility.CloneOrUpdate(String path, String url, IEnumerable`1 committishes, Boolean bare, Boolean depthOne, Boolean prune, Config config) in D:\work\1\s\src\docfx\lib\git\GitUtility.cs:line 328
       at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_1.<Restore>b__6() in D:\work\1\s\src\docfx\restore\RestoreGit.cs:line 111
       --- End of inner exception stack trace ---
       at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_1.<Restore>b__6() in D:\work\1\s\src\docfx\restore\RestoreGit.cs:line 115
       at Microsoft.Docs.Build.ProcessUtility.RunInsideMutex(String mutexName, Action action) in D:\work\1\s\src\docfx\lib\ProcessUtility.cs:line 314
       at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_0.<Restore>g__RestoreGitRepo|3(IGrouping`2 group) in D:\work\1\s\src\docfx\restore\RestoreGit.cs:line 121
       at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_0.<Restore>b__2(IGrouping`2 group) in D:\work\1\s\src\docfx\restore\RestoreGit.cs:line 45
       at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 32
       at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
    --- End of stack trace from previous location where exception was thrown ---
       at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
       at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
       at System.Threading.Tasks.TaskReplicator.Replica.Execute()
    Error: dotnet run docfx restore returns exit code: 1
    .

**Comment by OsmondJiang** [comment]
Actually docfx restore return -1 and output build.log file, doesn't crash for this case
