### ISSUE TITLE
restore crashed due to git worktree and index.json out of sync

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4443]
Exception (first time):

```
Using docfx 3.0.0-beta-00833-20832f903
Using existing repository 'C:\Users\yufeih\AppData\Local\Temp\appdata\git2\github.com+Microsoft+template..ocs.msft+95403dd1\.git' for 'https://github.com/Microsoft/templates.docs.msft'
remote: Enumerating objects: 90, done.
remote: Counting objects: 100% (83/83), done.
remote: Compressing objects: 100% (27/27), done.
remote: Total 44 (delta 26), reused 25 (delta 14), pack-reused 0
Unpacking objects: 100% (44/44), done.
From https://github.com/Microsoft/templates.docs.msft
 + 1825ec8...f615a60 master     -> master  (forced update)
fatal: 'C:/Users/yufeih/AppData/Local/Temp/appdata/git2/github.com+Microsoft+template..ocs.msft+95403dd1/1' already exists
Preparing worktree (detached HEAD f615a60)
Restore dependencies done in 5.57s
Microsoft.Docs.Build.DocfxException: Cloning git repository 'https://github.com/Microsoft/templates.docs.msft' ('master') failed. ---> System.InvalidOperationException: '"git" -c core.longpaths=true worktree add C:/Users/yufeih/AppData/Local/Temp/appdata/git2/github.com+Microsoft+template..ocs.msft+95403dd1/1 f615a60861b2393d84323892167657235cb1f5d1 --force' failed in directory 'C:\Users\yufeih\AppData\Local\Temp\appdata\git2\github.com+Microsoft+template..ocs.msft+95403dd1\.git' with exit code 128:
STDOUT:''
   at Microsoft.Docs.Build.ProcessUtility.Execute(String fileName, String commandLineArgs, String cwd, Boolean stdout) in D:\work\1\s\src\docfx\lib\ProcessUtility.cs:line 202
   at Microsoft.Docs.Build.GitUtility.Execute(String cwd, String commandLineArgs, Boolean stdout) in D:\work\1\s\src\docfx\lib\git\GitUtility.cs:line 346
   at Microsoft.Docs.Build.GitUtility.AddWorkTree(String cwd, String committish, String path) in D:\work\1\s\src\docfx\lib\git\GitUtility.cs:line 181
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_2.<Restore>b__8(String branch) in D:\work\1\s\src\docfx\restore\RestoreGit.cs:line 155
   --- End of inner exception stack trace ---
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_2.<Restore>b__8(String branch) in D:\work\1\s\src\docfx\restore\RestoreGit.cs:line 159
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 32
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
git-clone-failed (0,0): Cloning git repository 'https://github.com/Microsoft/templates.docs.msft' ('master') failed.
Error: dotnet run docfx restore returns exit code: 1
```

Exception (second time):

```
Using docfx 3.0.0-beta-00833-20832f903
remote: Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
fatal: 'C:/Users/yufeih/AppData/Local/Temp/appdata/git2/github.com+Microsoft+template..ocs.msft+95403dd1/2' already exists
Preparing worktree (detached HEAD f615a60)
Restore dependencies done in 4.38s
Microsoft.Docs.Build.DocfxException: Cloning git repository 'https://github.com/Microsoft/templates.docs.msft' ('master') failed. ---> System.InvalidOperationException: '"git" -c core.longpaths=true worktree add C:/Users/yufeih/AppData/Local/Temp/appdata/git2/github.com+Microsoft+template..ocs.msft+95403dd1/2 f615a60861b2393d84323892167657235cb1f5d1 --force' failed in directory 'C:\Users\yufeih\AppData\Local\Temp\appdata\git2\github.com+Microsoft+template..ocs.msft+95403dd1\.git' with exit code 128:
STDOUT:''
   at Microsoft.Docs.Build.ProcessUtility.Execute(String fileName, String commandLineArgs, String cwd, Boolean stdout) in D:\work\1\s\src\docfx\lib\ProcessUtility.cs:line 202
   at Microsoft.Docs.Build.GitUtility.Execute(String cwd, String commandLineArgs, Boolean stdout) in D:\work\1\s\src\docfx\lib\git\GitUtility.cs:line 346
   at Microsoft.Docs.Build.GitUtility.AddWorkTree(String cwd, String committish, String path) in D:\work\1\s\src\docfx\lib\git\GitUtility.cs:line 181
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_2.<Restore>b__8(String branch) in D:\work\1\s\src\docfx\restore\RestoreGit.cs:line 155
   --- End of inner exception stack trace ---
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_2.<Restore>b__8(String branch) in D:\work\1\s\src\docfx\restore\RestoreGit.cs:line 159
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 32
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
git-clone-failed (0,0): Cloning git repository 'https://github.com/Microsoft/templates.docs.msft' ('master') failed.
Error: dotnet run docfx restore returns exit code: 1
```

git worktree list:

```
C:/Users/yufeih/AppData/Local/Temp/appdata/git2/github.com+Microsoft+template..ocs.msft+95403dd1/.git  (bare)
C:/Users/yufeih/AppData/Local/Temp/appdata/git2/github.com+Microsoft+template..ocs.msft+95403dd1/6     1825ec8 (detached HEAD)
```

index.json:
```json
{
    "slots": [
        {
            "commit": "f615a60861b2393d84323892167657235cb1f5d1",
            "branch": "master",
            "id": "1",
            "lastAccessDate": "2019-04-29T05:32:59.9032061Z",
            "restored": false
        },
        {
            "commit": "f615a60861b2393d84323892167657235cb1f5d1",
            "branch": "master",
            "id": "2",
            "lastAccessDate": "2019-04-29T05:36:02.8311232Z",
            "restored": false
        },
        {
            "commit": "1825ec886eb26ad904d6d304050bc76cd5e18aab",
            "branch": "master",
            "id": "3",
            "lastAccessDate": "2019-04-24T06:42:52.2916969Z",
            "restored": true
        },
        {
            "commit": "1825ec886eb26ad904d6d304050bc76cd5e18aab",
            "branch": "master",
            "id": "4",
            "lastAccessDate": "2019-04-24T06:47:32.6422883Z",
            "restored": true
        },
        {
            "commit": "1825ec886eb26ad904d6d304050bc76cd5e18aab",
            "branch": "master",
            "id": "5",
            "lastAccessDate": "2019-04-24T06:49:06.4535901Z",
            "restored": true
        },
        {
            "commit": "1825ec886eb26ad904d6d304050bc76cd5e18aab",
            "branch": "master",
            "id": "6",
            "lastAccessDate": "2019-04-24T06:51:14.2127656Z",
            "restored": true
        }
    ]
}
```

ls:
```
Directory: C:\Users\yufeih\AppData\Local\Temp\appdata\git2\github.com+Microsoft+template..ocs.msft+95403dd1


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        4/29/2019   1:36 PM                .git
d-----        4/24/2019   6:07 PM                1
d-----        4/24/2019   6:07 PM                2
d-----        4/25/2019   6:11 PM                3
d-----        4/25/2019   6:11 PM                4
d-----        4/25/2019   6:11 PM                5
d-----        4/24/2019   2:51 PM                6
-a----        4/29/2019   1:36 PM            883 index.json
```

**Comment by yufeih** [comment]
This is still not resolved, it currently failed at:

```
---> System.ArgumentNullException: Value cannot be null
at Microsoft.Docs.Build.Repository..ctor(String remote, String branch, String commit, String path) in D:\docfx\src\docfx\docset\Repository.cs:line 23
at Microsoft.Docs.Build.Repository.Create(String path, String branch, String repoUrl) in D:\docfx\src\docfx\docset\Repository.cs:line 54
at Microsoft.Docs.Build.Docset..ctor(Report report, String docsetPath, String locale, Config config, CommandLineOptions options, RestoreMap restoreMap, Repository repository, Docset fallbackDocset, Docset localizedDocset) in D:\docfx\src\docfx\docset\Docset.cs:line 170
at Microsoft.Docs.Build.Docset..ctor(Report report, String docsetPath, String locale, Config config, CommandLineOptions options, RestoreMap restoreMap, Repository repository, Repository fallbackRepo, Docset localizedDocset, Docset fallbackDocset, Boolean isDependency) in D:\docfx\src\docfx\docset\Docset.cs:line 128
```

Because worktree is in a weird status:

```
PS C:\Users\yufeih\.docfx\git2\github.com+Azure-Samples+multicon..ordpress+6ead59c2\.git> git worktree list
C:/Users/yufeih/.docfx/git2/github.com+Azure-Samples+multicon..ordpress+6ead59c2/.git  (bare)
C:/Users/yufeih/.docfx/git2/github.com+Azure-Samples+multicon..ordpress+6ead59c2/1     0000000 [c42eec065ab5b4018116d4c466509ee575694596]
```

```
PS C:\Users\yufeih\.docfx\git2\github.com+Azure-Samples+multicon..ordpress+6ead59c2\1> git status
On branch c42eec065ab5b4018116d4c466509ee575694596

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)

        new file:   .github/ISSUE_TEMPLATE.md
        new file:   .github/PULL_REQUEST_TEMPLATE.md
        new file:   .gitignore
        new file:   CONTRIBUTING.md
        new file:   Dockerfile
        new file:   LICENSE.md
        new file:   README.md
        new file:   compose-wordpress.yml
        new file:   docker-compose-wordpress.yml
        new file:   docker-entrypoint.sh
        new file:   kubernetes-wordpress.yml

PS C:\Users\yufeih\.docfx\git2\github.com+Azure-Samples+multicon..ordpress+6ead59c2\1> git log
fatal: your current branch 'c42eec065ab5b4018116d4c466509ee575694596' does not have any commits yet
```

**Comment by OsmondJiang** [comment]
It's mostly was caused by you cancel the restore whiling it's checking out file. We all can met this problem when you close your console while cloning a repo half on the way, especially whiling it's checking out files.

There are two ways to handling this:
- Give an error to let user to clean the working tree manually
- Delete this un-clean work tree before reusing it.

cc @yufeih  @herohua  @live1206  @mingwli  @928PJY

**Comment by OsmondJiang** [comment]
Below is the assuming steps:
1. Restore and cancel, work tree checkout failed, but work tree folder has been created
2. Restore again and found the wok tree folder, skip work tree add, mark as complete
3. Build failed while using an dirty work tree folder.

cc @yufeih
