### ISSUE TITLE
NRE in dependency slot pool

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4458]
# docfx crash report: System.AggregateException

docfx: `1.0.0`
x64: `True`
cmd: `D:\docfx\src\docfx\bin\Release\netcoreapp2.2\docfx.dll restore D:\docfx-impact\source\azure-docs-pr --verbose`
cwd: `D:\docfx\src\docfx`
git: `git version 2.21.0.windows.1`

## callstack

```
System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)) ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Docs.Build.DependencySlotPool`1.<>c__DisplayClass3_0.<AcquireSlot>b__0() in D:\docfx\src\docfx\restore\index\DependencySlotPool.cs:line 138
   at Microsoft.Docs.Build.ProcessUtility.RunInsideMutex(String mutexName, Action action) in D:\docfx\src\docfx\lib\ProcessUtility.cs:line 314
   at Microsoft.Docs.Build.DependencySlotPool`1.AcquireSlot(String url, LockType type, Func`2 updateExistingSlot, Func`2 matchExistingSlot) in D:\docfx\src\docfx\restore\index\DependencySlotPool.cs:line 102
   at Microsoft.Docs.Build.RestoreMap.AcquireGit(String remote, String branch, String commit, LockType type) in D:\docfx\src\docfx\restore\RestoreMap.cs:line 247
   at Microsoft.Docs.Build.RestoreMap.AcquireExclusiveGit(String remote, String branch, String commit) in D:\docfx\src\docfx\restore\RestoreMap.cs:line 231
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_2.<Restore>b__8(String branch) in D:\docfx\src\docfx\restore\RestoreGit.cs:line 145
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\docfx\src\docfx\lib\ParallelUtility.cs:line 31
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.Docs.Build.ParallelUtility.ForEach[T](IEnumerable`1 source, Action`1 action, Action`2 progress) in D:\docfx\src\docfx\lib\ParallelUtility.cs:line 34
   at Microsoft.Docs.Build.ProcessUtility.RunInsideMutex(String mutexName, Action action) in D:\docfx\src\docfx\lib\ProcessUtility.cs:line 314
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_0.<Restore>g__RestoreGitRepo|3(IGrouping`2 group) in D:\docfx\src\docfx\restore\RestoreGit.cs:line 122
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_0.<Restore>b__2(IGrouping`2 group) in D:\docfx\src\docfx\restore\RestoreGit.cs:line 45
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\docfx\src\docfx\lib\ParallelUtility.cs:line 32
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.Docs.Build.ParallelUtility.ForEach[T](IEnumerable`1 source, Action`1 action, Action`2 progress) in D:\docfx\src\docfx\lib\ParallelUtility.cs:line 34
   at Microsoft.Docs.Build.RestoreGit.Restore(Config config, Func`3 restoreChild, String locale, Boolean implicit, Repository rootRepository, DependencyLockModel dependencyLock) in D:\docfx\src\docfx\restore\RestoreGit.cs:line 53
   at Microsoft.Docs.Build.Restore.<>c__DisplayClass0_0.<<Run>g__RestoreOneDocset|0>d.MoveNext() in D:\docfx\src\docfx\restore\Restore.cs:line 84
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Docs.Build.Restore.<>c__DisplayClass0_2.<<Run>b__2>d.MoveNext() in D:\docfx\src\docfx\restore\Restore.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Docs.Build.Restore.Run(String docsetPath, CommandLineOptions options, Report report, Boolean implicit) in D:\docfx\src\docfx\restore\Restore.cs:line 30
   at Microsoft.Docs.Build.Program.Run(String[] args) in D:\docfx\src\docfx\cli\Program.cs:line 71
   at Microsoft.Docs.Build.Program.Main(String[] args) in D:\docfx\src\docfx\cli\Program.cs:line 22
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Docs.Build.DependencySlotPool`1.<>c__DisplayClass3_0.<AcquireSlot>b__0() in D:\docfx\src\docfx\restore\index\DependencySlotPool.cs:line 138
   at Microsoft.Docs.Build.ProcessUtility.RunInsideMutex(String mutexName, Action action) in D:\docfx\src\docfx\lib\ProcessUtility.cs:line 314
   at Microsoft.Docs.Build.DependencySlotPool`1.AcquireSlot(String url, LockType type, Func`2 updateExistingSlot, Func`2 matchExistingSlot) in D:\docfx\src\docfx\restore\index\DependencySlotPool.cs:line 102
   at Microsoft.Docs.Build.RestoreMap.AcquireGit(String remote, String branch, String commit, LockType type) in D:\docfx\src\docfx\restore\RestoreMap.cs:line 247
   at Microsoft.Docs.Build.RestoreMap.AcquireExclusiveGit(String remote, String branch, String commit) in D:\docfx\src\docfx\restore\RestoreMap.cs:line 231
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_2.<Restore>b__8(String branch) in D:\docfx\src\docfx\restore\RestoreGit.cs:line 145
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\docfx\src\docfx\lib\ParallelUtility.cs:line 31
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.Docs.Build.ParallelUtility.ForEach[T](IEnumerable`1 source, Action`1 action, Action`2 progress) in D:\docfx\src\docfx\lib\ParallelUtility.cs:line 34
   at Microsoft.Docs.Build.ProcessUtility.RunInsideMutex(String mutexName, Action action) in D:\docfx\src\docfx\lib\ProcessUtility.cs:line 314
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_0.<Restore>g__RestoreGitRepo|3(IGrouping`2 group) in D:\docfx\src\docfx\restore\RestoreGit.cs:line 122
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_0.<Restore>b__2(IGrouping`2 group) in D:\docfx\src\docfx\restore\RestoreGit.cs:line 45
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\docfx\src\docfx\lib\ParallelUtility.cs:line 32
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Docs.Build.DependencySlotPool`1.<>c__DisplayClass3_0.<AcquireSlot>b__0() in D:\docfx\src\docfx\restore\index\DependencySlotPool.cs:line 138
   at Microsoft.Docs.Build.ProcessUtility.RunInsideMutex(String mutexName, Action action) in D:\docfx\src\docfx\lib\ProcessUtility.cs:line 314
   at Microsoft.Docs.Build.DependencySlotPool`1.AcquireSlot(String url, LockType type, Func`2 updateExistingSlot, Func`2 matchExistingSlot) in D:\docfx\src\docfx\restore\index\DependencySlotPool.cs:line 102
   at Microsoft.Docs.Build.RestoreMap.AcquireGit(String remote, String branch, String commit, LockType type) in D:\docfx\src\docfx\restore\RestoreMap.cs:line 247
   at Microsoft.Docs.Build.RestoreMap.AcquireExclusiveGit(String remote, String branch, String commit) in D:\docfx\src\docfx\restore\RestoreMap.cs:line 231
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_2.<Restore>b__8(String branch) in D:\docfx\src\docfx\restore\RestoreGit.cs:line 145
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\docfx\src\docfx\lib\ParallelUtility.cs:line 31
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
<---

```

## dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.202\

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.402 [C:\Program Files\dotnet\sdk]
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.500 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.505 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.2.101 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by OsmondJiang** [comment]
we can make sure that it's caused by inconsistent states between slots and lock, which is caused by docfx crashed or stroped manually.

Will fix it soon.
