### ISSUE TITLE
NullReferenceException when generating F# docs

### ISSUE THREAD

**Issue by Sharparam** [dotnet/docfx#4535]
**Operation System**: Windows

**DocFX Version Used**: 2.42.3.0 (installed with chocolatey)

**Template used**: `default`, `statictoc`, and [`material`](https://github.com/ovasquez/docfx-material/)

**Steps to Reproduce**:

1. Add one or more `fsproj` project files to the metadata source list.
2. Attempt to generate docs with DocFx

**Expected Behavior**: Documentation is generated. With F# support as mentioned in [the user manual](https://dotnet.github.io/docfx/tutorial/docfx.exe_user_manual.html).

**Actual Behavior**: Documentation fails with a `NullReferenceException` as below:

```
[19-05-13 01:34:35.916]Info:[ExtractMetadata]Using msbuild C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin as inner compiler.
[19-05-13 01:34:36.279]Info:[ExtractMetadata]Loading projects...
[19-05-13 01:34:42.011]Warning:[ExtractMetadata](C:/Users/<user>/Projects/csharp/cshrix-bot/Cshrix.Bot.sln)Workspace failed with: [Failure] Cannot open project 'C:\Users\<user>\Projects\csharp\cshrix-bot\test\Cshrix.FSharp.Tests\Cshrix.FSharp.Tests.fsproj' because the file extension '.fsproj' is not associated with a language.
[19-05-13 01:34:42.015]Warning:[ExtractMetadata](C:/Users/<user>/Projects/csharp/cshrix-bot/Cshrix.Bot.sln)Workspace failed with: [Failure] Cannot open project 'C:\Users\<user>\Projects\csharp\cshrix-bot\src\Cshrix.FSharp\Cshrix.FSharp.fsproj' because the file extension '.fsproj' is not associated with a language.
[19-05-13 01:34:43.711]Warning:[ExtractMetadata](C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix.FSharp/Cshrix.FSharp.fsproj)Error opening project C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix.FSharp/Cshrix.FSharp.fsproj: F# project C:\Users\<user>\Projects\csharp\cshrix-bot\src\Cshrix.FSharp\Cshrix.FSharp.fsproj has unsupported type.. Ignored.
[19-05-13 01:34:43.736]Error:Error extracting metadata for C:/Users/<user>/Projects/csharp/cshrix-bot/Cshrix.Bot.sln,C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix/Cshrix.csproj,C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix.Bot.Console/Cshrix.Bot.Console.csproj,C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix.FSharp/Cshrix.FSharp.fsproj: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
[19-05-13 01:34:43.743]Info:Completed in 7855.564 milliseconds


Build failed.
[19-05-13 01:34:43.757]Warning:[ExtractMetadata](C:/Users/<user>/Projects/csharp/cshrix-bot/Cshrix.Bot.sln)Workspace failed with: [Failure] Cannot open project 'C:\Users\<user>\Projects\csharp\cshrix-bot\test\Cshrix.FSharp.Tests\Cshrix.FSharp.Tests.fsproj' because the file extension '.fsproj' is not associated with a language.
[19-05-13 01:34:43.758]Warning:[ExtractMetadata](C:/Users/<user>/Projects/csharp/cshrix-bot/Cshrix.Bot.sln)Workspace failed with: [Failure] Cannot open project 'C:\Users\<user>\Projects\csharp\cshrix-bot\src\Cshrix.FSharp\Cshrix.FSharp.fsproj' because the file extension '.fsproj' is not associated with a language.
[19-05-13 01:34:43.759]Warning:[ExtractMetadata](C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix.FSharp/Cshrix.FSharp.fsproj)Error opening project C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix.FSharp/Cshrix.FSharp.fsproj: F# project C:\Users\<user>\Projects\csharp\cshrix-bot\src\Cshrix.FSharp\Cshrix.FSharp.fsproj has unsupported type.. Ignored.
[19-05-13 01:34:43.760]Error:Error extracting metadata for C:/Users/<user>/Projects/csharp/cshrix-bot/Cshrix.Bot.sln,C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix/Cshrix.csproj,C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix.Bot.Console/Cshrix.Bot.Console.csproj,C:/Users/<user>/Projects/csharp/cshrix-bot/src/Cshrix.FSharp/Cshrix.FSharp.fsproj: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
        3 Warning(s)
        1 Error(s)
```

## Links

[DocFx config file in my repo](https://github.com/Sharparam/cshrix-bot/blob/e6b8714cd2817d02f1edb277d0b3489dbfc84adc/docs/docfx.json)

[Failing AppVeyor build with complete logs](https://ci.appveyor.com/project/sharparam/cshrix-bot/builds/24504030)

**Comment by davidtgillard** [comment]
I experienced this same issue with v2.47, but it appears to now be fixed in the latest version (v2.48.1).

**Comment by pauldendulk** [comment]
For me 2.48 also solved the problem.

**Comment by FriedrichGretz** [comment]
I do not get the NullReference. But I believe the main issue of the original post is the part where it says:

> [Failure] Cannot open project 'C:\Users\<user>\Projects\csharp\cshrix-bot\test\Cshrix.FSharp.Tests\Cshrix.FSharp.Tests.fsproj' because the file extension '.fsproj' is not associated with a language.

It looks like F# is not supported. And that is the same for versions 2.47 and 2.48.1.
So the question is: is F# really not supported? (The website provides contradictory statments, cf. https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html and https://dotnet.github.io/docfx/tutorial/universalreference/intro_multiple_langs_support.html)
Or is F# actually supported but the JSON file has to be adapted somehow?

**Comment by davidtgillard** [comment]
You have to add the fsproj the metadata source list. However, there are additional issues for modern F# language features (see [issue 3679](https://github.com/dotnet/docfx/issues/3679)). 

You'll likely have better luck with FSharp.Formatting in the short-term (I'm currently using this), although the documentation is not up-to-date.

**Comment by davidtgillard** [comment]
[Version 2.52.0](https://github.com/dotnet/docfx/releases/tag/v2.52) released yesterday incorporates the latest Fsharp.Compiler.Service. FWIW I'm now able to generate docs for Fsharp projects where I wasn't before, provided the source doesn't trigger [issue 5760](https://github.com/dotnet/docfx/issues/5760).
