### ISSUE TITLE
RestoreGitWorkTrees failed occasionally.

### ISSUE THREAD

**Issue by yufeih** [dotnet/docfx#4542]
https://dev.azure.com/ceapex/Engineering/_build/results?buildId=55061

Building files: 100% (1/1), 00:00:05 
Failed   Microsoft.Docs.Build.RestoreTest.RestoreGitWorkTrees
Error Message:
 Assert.Equal() Failure
Expected: 5
Actual:   4
Stack Trace:
   at Microsoft.Docs.Build.RestoreTest.RestoreGitWorkTrees() in D:\a\1\s\test\docfx.Test\restore\RestoreTest.cs:line 117

**Comment by OsmondJiang** [comment]
Here is the detail log:

```
Microsoft.Docs.Build.DocfxException: Cloning git repository 'https://github.com/docascode/docfx-test-dependencies-clean' ('test-4-clean') failed. ---> System.InvalidOperationException: '"git" -c core.longpaths=true worktree add D:/a/1/s/test/docfx.Test/bin/Debug/netcoreapp2.2/appdata/git2/github.com+docascode+docfx-te..es-clean+0336104e/5 01fa8106eb0b1de66fa75fefe49f1ce35cb239de --force' failed in directory 'D:\a\1\s\test\docfx.Test\bin\Debug\netcoreapp2.2\appdata\git2\github.com+docascode+docfx-te..es-clean+0336104e\.git' with exit code 128: 
STDOUT:''
   at Microsoft.Docs.Build.ProcessUtility.Execute(String fileName, String commandLineArgs, String cwd, Boolean stdout)
   at Microsoft.Docs.Build.GitUtility.Execute(String cwd, String commandLineArgs, Boolean stdout)
   at Microsoft.Docs.Build.GitUtility.ExecuteNonQuery(String cwd, String commandLineArgs)
   at Microsoft.Docs.Build.GitUtility.AddWorkTree(String cwd, String committish, String path)
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_1.<Restore>b__8(String branch)
   --- End of inner exception stack trace ---
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_1.<Restore>b__8(String branch)
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()

Seems folder are not cleaned up before work tree added
```

**Comment by yufeih** [comment]
https://dev.azure.com/ceapex/Engineering/_build%2Fresults?buildId=55042&_a=summary

Failed   Microsoft.Docs.Build.RestoreTest.RestoreGitWorkTrees
Error Message:
 Assert.Equal() Failure
Expected: 4
Actual:   5
Stack Trace:
   at Microsoft.Docs.Build.RestoreTest.RestoreGitWorkTrees() in D:\work\11\docfx\test\docfx.Test\restore\RestoreTest.cs:line 106

**Comment by OsmondJiang** [comment]
```
Microsoft.Docs.Build.DocfxException: Cloning git repository 'https://github.com/docascode/docfx-test-dependencies-clean' ('test-2-clean', 'test-3-clean') failed. ---> System.InvalidOperationException: '"git" -c core.longpaths=true worktree add D:/work/11/docfx/test/docfx.Test/bin/Debug/netcoreapp2.2/appdata/git2/github.com+docascode+docfx-te..es-clean+0336104e/2 01fa8106eb0b1de66fa75fefe49f1ce35cb239de --force' failed in directory 'D:\work\11\docfx\test\docfx.Test\bin\Debug\netcoreapp2.2\appdata\git2\github.com+docascode+docfx-te..es-clean+0336104e\.git' with exit code 128: 
STDOUT:''
   at Microsoft.Docs.Build.ProcessUtility.Execute(String fileName, String commandLineArgs, String cwd, Boolean stdout)
   at Microsoft.Docs.Build.GitUtility.Execute(String cwd, String commandLineArgs, Boolean stdout)
   at Microsoft.Docs.Build.GitUtility.ExecuteNonQuery(String cwd, String commandLineArgs)
   at Microsoft.Docs.Build.GitUtility.AddWorkTree(String cwd, String committish, String path)
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_1.<Restore>b__8(String branch)
   --- End of inner exception stack trace ---
   at Microsoft.Docs.Build.RestoreGit.<>c__DisplayClass1_1.<Restore>b__8(String branch)
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by OsmondJiang** [comment]
The root cause is Directory.Delete() will not immediately delete all files/directories in this directory on Windows platform, referencing:  // https://stackoverflow.com/questions/24265481/after-directory-delete-the-directory-exists-returning-true-sometimes

That's the reason why it only failed on Windows platform, always success on Linux and Mac.

I added an debug assert for that, to identify the root cause for that, and also change some logic to reduce the Directorty.Delete calls. Let's see the result.

cc @yufeih  @herohua  @mingwli  @live1206

**Comment by yufeih** [comment]
Still failing https://dev.azure.com/ceapex/Engineering/_build/results?buildId=56721

```
Failed   Microsoft.Docs.Build.RestoreTest.RestoreGitWorkTrees
Error Message:
 Assert.Equal() Failure
Expected: 0
Actual:   1
Stack Trace:
   at Microsoft.Docs.Build.RestoreTest.RestoreGitWorkTrees() in D:\a\1\s\test\docfx.Test\restore\RestoreTest.cs:line 116
--- End of stack trace from previous location where exception was thrown ---
Build done in 14.51s
```

**Comment by OsmondJiang** [comment]
> Still failing https://dev.azure.com/ceapex/Engineering/_build/results?buildId=56721
> 
> ```
> Failed   Microsoft.Docs.Build.RestoreTest.RestoreGitWorkTrees
> Error Message:
>  Assert.Equal() Failure
> Expected: 0
> Actual:   1
> Stack Trace:
>    at Microsoft.Docs.Build.RestoreTest.RestoreGitWorkTrees() in D:\a\1\s\test\docfx.Test\restore\RestoreTest.cs:line 116
> --- End of stack trace from previous location where exception was thrown ---
> Build done in 14.51s
> ```
Because this PR #4566 is not merged.

**Comment by OsmondJiang** [comment]
PR #4566 has been merged, let's see what happens then.

**Comment by yufeih** [comment]
Still failing: https://dev.azure.com/ceapex/Engineering/_build/results?buildId=57183

**Comment by OsmondJiang** [comment]
we finally got the error:

![image](https://user-images.githubusercontent.com/19990166/58298598-ac7c9b00-7e0e-11e9-8337-fe9c72bd0b21.png)

**Comment by yufeih** [comment]
Still failing: https://dev.azure.com/ceapex/Engineering/_build/results?buildId=57739&view=logs&jobId=a29a2371-0793-5e14-39b9-20eb0beef0db

**Comment by yufeih** [comment]
Still failing: https://dev.azure.com/ceapex/Engineering/_build/results?buildId=58055

**Comment by OsmondJiang** [comment]
still failing: https://dev.azure.com/ceapex/Engineering/_build/results?buildId=58194

**Comment by yufeih** [comment]
Close as this test has been removed.
