### ISSUE TITLE
output file can't be accessed when redirection and file shared the same publish url

### ISSUE THREAD

**Issue by OsmondJiang** [dotnet/docfx#4550]
```
Failed   Microsoft.Docs.Build.E2ETest.Run(name: "legacy/03. Produce deterministic result when redir"...)
Error Message:
 System.IO.IOException : The process cannot access the file 'D:\a\1\s\test\docfx.Test\bin\Release\netcoreapp2.2\specs-drop\legacy 03. Produce determinist-a7be9\_site\docs\a.raw.page.json' because it is being used by another process.
Stack Trace:
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.Docs.Build.Output.WriteText(String text, String destRelativePath)
   at Microsoft.Docs.Build.BuildRedirection.Build(Context context, Document file)
   at Microsoft.Docs.Build.Build.BuildFile(Context context, Document file, TableOfContentsMap tocMap, MonikerMap monikerMap, Action`1 buildChild)
   at Microsoft.Docs.Build.Build.<>c__DisplayClass2_0.<<BuildFiles>g__BuildOneFile|3>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Docs.Build.Build.<>c__DisplayClass2_1.<<BuildFiles>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass3_0`1.<<ForEach>g__Run|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Docs.Build.ParallelUtility.ForEach[T](IEnumerable`1 source, Func`3 action, Func`2 predicate, Action`2 progress)
   at Microsoft.Docs.Build.Build.BuildFiles(Context context, Docset docset, TableOfContentsMap tocMap)
   at Microsoft.Docs.Build.Build.Run(String docsetPath, Repository repository, String locale, CommandLineOptions options, ErrorLog errorLog, RestoreMap restoreMap, Repository fallbackRepo)
   at Microsoft.Docs.Build.Build.Run(String docsetPath, CommandLineOptions options, ErrorLog errorLog)
   at Microsoft.Docs.Build.Program.Run(String[] args)
   at Microsoft.Docs.Build.E2ETest.RunCore(String docsetPath, E2ESpec spec) in D:\a\1\s\test\docfx.Test\e2e\E2ETest.cs:line 106
   at Microsoft.Docs.Build.E2ETest.Run(String name) in D:\a\1\s\test\docfx.Test\e2e\E2ETest.cs:line 86
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by OsmondJiang** [comment]
https://dev.azure.com/ceapex/Engineering/_build/results?buildId=55322

**Comment by yufeih** [comment]
This should be resolved now.
