### ISSUE TITLE
docfx 3 crash in TableOfContentsParser

### ISSUE THREAD

**Issue by fr0** [dotnet/docfx#4577]
🚘💥🚗 docfx has crashed 🚘💥🚗
Help us improve by creating an issue at https://github.com/dotnet/docfx:

# docfx crash report: System.AggregateException

docfx: `3.0.0-beta-00912-731f8ea3f`
x64: `True`
cmd: `/Users/crfrolik/.dotnet/tools/.store/docfx/3.0.0-beta-00912-731f8ea3f/docfx/3.0.0-beta-00912-731f8ea3f/tools/netcoreapp2.2/any/docfx.dll build`
cwd: `/Users/crfrolik/Documents/atlas-client-dotnet/AtlasClientDocumentation`
git: `git version 2.14.1`

## callstack

```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Docs.Build.TableOfContentsParser.GetFirstItemWithHref(List`1 nestedTocItems) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 270
   at Microsoft.Docs.Build.TableOfContentsParser.GetFirstItemWithHref(List`1 nestedTocItems) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 270
   at Microsoft.Docs.Build.TableOfContentsParser.<ResolveTocModelItems>g__ProcessTocHref|9_2(SourceInfo`1 tocHref, <>c__DisplayClass9_0& ) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 214
   at Microsoft.Docs.Build.TableOfContentsParser.ResolveTocModelItems(Context context, List`1 tocModelItems, List`1 parents, Document filePath, Document rootPath, ResolveContent resolveContent, ResolveHref resolveHref, ResolveXref resolveXref) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 129
   at Microsoft.Docs.Build.TableOfContentsParser.LoadInternal(Context context, Document file, Document rootPath, ResolveContent resolveContent, ResolveHref resolveHref, ResolveXref resolveXref, List`1 parents, String content) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 93
   at Microsoft.Docs.Build.BuildTableOfContents.Load(Context context, Document fileToBuild) in D:\work\1\s\src\docfx\build\toc\BuildTableOfContents.cs:line 115
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Docs.Build.Cache.LoadTocModel(Context context, Document file)
   at Microsoft.Docs.Build.TableOfContentsMap.<>c__DisplayClass9_0.<Create>g__BuildTocMap|0(Document fileToBuild, TableOfContentsMapBuilder tocMapBuilder) in D:\work\1\s\src\docfx\build\toc\TableOfContentsMap.cs:line 107
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 32
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.Docs.Build.ParallelUtility.ForEach[T](IEnumerable`1 source, Action`1 action, Action`2 progress) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 34
   at Microsoft.Docs.Build.TableOfContentsMap.Create(Context context, Docset docset) in D:\work\1\s\src\docfx\build\toc\TableOfContentsMap.cs:line 97
   at Microsoft.Docs.Build.Build.Run(String docsetPath, Repository repository, String locale, CommandLineOptions options, ErrorLog errorLog, RestoreMap restoreMap, Repository fallbackRepo) in D:\work\1\s\src\docfx\build\Build.cs:line 57
   at Microsoft.Docs.Build.Build.Run(String docsetPath, CommandLineOptions options, ErrorLog errorLog) in D:\work\1\s\src\docfx\build\Build.cs:line 26
   at Microsoft.Docs.Build.Program.Run(String[] args) in D:\work\1\s\src\docfx\cli\Program.cs:line 79
   at Microsoft.Docs.Build.Program.Main(String[] args) in D:\work\1\s\src\docfx\cli\Program.cs:line 22
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Docs.Build.TableOfContentsParser.GetFirstItemWithHref(List`1 nestedTocItems) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 270
   at Microsoft.Docs.Build.TableOfContentsParser.GetFirstItemWithHref(List`1 nestedTocItems) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 270
   at Microsoft.Docs.Build.TableOfContentsParser.<ResolveTocModelItems>g__ProcessTocHref|9_2(SourceInfo`1 tocHref, <>c__DisplayClass9_0& ) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 214
   at Microsoft.Docs.Build.TableOfContentsParser.ResolveTocModelItems(Context context, List`1 tocModelItems, List`1 parents, Document filePath, Document rootPath, ResolveContent resolveContent, ResolveHref resolveHref, ResolveXref resolveXref) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 129
   at Microsoft.Docs.Build.TableOfContentsParser.LoadInternal(Context context, Document file, Document rootPath, ResolveContent resolveContent, ResolveHref resolveHref, ResolveXref resolveXref, List`1 parents, String content) in D:\work\1\s\src\docfx\build\toc\parser\TableOfContentsParser.cs:line 93
   at Microsoft.Docs.Build.BuildTableOfContents.Load(Context context, Document fileToBuild) in D:\work\1\s\src\docfx\build\toc\BuildTableOfContents.cs:line 115
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Docs.Build.Cache.LoadTocModel(Context context, Document file)
   at Microsoft.Docs.Build.TableOfContentsMap.<>c__DisplayClass9_0.<Create>g__BuildTocMap|0(Document fileToBuild, TableOfContentsMapBuilder tocMapBuilder) in D:\work\1\s\src\docfx\build\toc\TableOfContentsMap.cs:line 107
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass1_0`1.<ForEach>b__0(T item) in D:\work\1\s\src\docfx\lib\ParallelUtility.cs:line 32
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

```

## dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.107
 Commit:    2212cac826

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.13-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.2.107/

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.401 [/usr/local/share/dotnet/sdk]
  2.1.504 [/usr/local/share/dotnet/sdk]
  2.1.505 [/usr/local/share/dotnet/sdk]
  2.2.104 [/usr/local/share/dotnet/sdk]
  2.2.107 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by OsmondJiang** [comment]
@fr0 , would you mind to attach your TOC.md or TOC.yml file in this issue thread to help us identity our problem?
