### ISSUE TITLE
System.ArgumentException: String cannot be of zero length

### ISSUE THREAD

**Issue by sandersaares** [dotnet/docfx#462]
When generating documentation for my project, the latest version of docfx 2.1.0.0 crashes with the following exception. It used to work with a previous build (1.6.2.0).

```
Error: System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"c:\\Source\\Toolkit\\Resources\\Documentation\\api":["c:/Source/Toolkit/Core/Core.csproj","c:/Source/Toolkit/DotNet/DotNet.csproj","c:/Source/Toolkit/DotNet.Jose/DotNet.Jose.csproj","c:/Source/Toolkit/DotNet.NLog/DotNet.NLog.csproj","c:/Source/Toolkit/Uwp/Uwp.csproj"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"UseCompatibilityFileName":false}: System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.GetXmlValue(XPathNavigator node)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.<GetMultipleExampleNodes>d__60.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel..ctor(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.CreateModel(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.VisitorHelper.FeedComments(MetadataItem item, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.DefaultVisit(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext() ---> System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.GetXmlValue(XPathNavigator node)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.<GetMultipleExampleNodes>d__60.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel..ctor(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.CreateModel(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.VisitorHelper.FeedComments(MetadataItem item, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.DefaultVisit(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"c:\\Source\\Toolkit\\Resources\\Documentation\\api":["c:/Source/Toolkit/Core/Core.csproj","c:/Source/Toolkit/DotNet/DotNet.csproj","c:/Source/Toolkit/DotNet.Jose/DotNet.Jose.csproj","c:/Source/Toolkit/DotNet.NLog/DotNet.NLog.csproj","c:/Source/Toolkit/Uwp/Uwp.csproj"]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"UseCompatibilityFileName":false}: System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.GetXmlValue(XPathNavigator node)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.<GetMultipleExampleNodes>d__60.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel..ctor(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.CreateModel(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.VisitorHelper.FeedComments(MetadataItem item, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.DefaultVisit(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext() ---> System.ArgumentException: String cannot be of zero length.
Parameter name: oldValue
   at System.String.ReplaceInternal(String oldValue, String newValue)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.GetXmlValue(XPathNavigator node)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.<GetMultipleExampleNodes>d__60.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel..ctor(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.TripleSlashCommentModel.CreateModel(String xml, SyntaxLanguage language, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.VisitorHelper.FeedComments(MetadataItem item, ITripleSlashCommentParserContext context)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.DefaultVisit(ISymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__34`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext()<---
```

I can privately share the project files if a member of this project can provide a private communication channel. Here is my documentation project file:

```
{
  "metadata": [
    {
      "src": [
        {
		  "cwd": "../..",
          "files": [
            "Core/Core.csproj",
			"DotNet/DotNet.csproj",
			"DotNet.NLog/DotNet.NLog.csproj",
			"Uwp/Uwp.csproj"
          ]
        }
      ],
      "dest": "api"
    }
  ],
  "build": {
    "content": [
      {
        "files": [
          "api/**.yml",
          "api/index.md"
        ]
      },
      {
        "files": [
          "articles/**.md",
          "articles/**/toc.yml",
          "toc.yml",
          "*.md"
        ],
        "exclude": [
          "_site/**"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**"
        ],
        "exclude": [
          "_site/**"
        ]
      }
    ],
    "overwrite": [
      {
        "files": [
          "apidoc/**.md"
        ],
        "exclude": [
          "_site/**"
        ]
      }
    ],
    "dest": "_site",
    "template": [
      "default"
    ]
  }
}
```

Basically, it is API documentation for a set of related .NET libraries plus a little bit of custom content added as a quick start/welcome page.

The critical input appears to be `Uwp/Uwp.csproj` - removing this makes the build succeed. I will attach the project file and the generated XML documentation file: [uwp.zip](https://github.com/dotnet/docfx/files/346368/uwp.zip)

**Comment by ansyral** [comment]
this is already fixed in dev branch in #445
