### ISSUE TITLE
docfx restore crash report: System.ArgumentNullException

### ISSUE THREAD

**Issue by live1206** [dotnet/docfx#4717]
# docfx crash report: System.ArgumentNullException

docfx: `1.0.0`
x64: `True`
git: `git version 2.21.0.windows.1`
DOCFX_CACHE_PATH: `c:/docs\_cache`
DOCFX_REPOSITORY_URL: `https://github.com/OPS-E2E-PPE/docs`
DOCFX_GLOBAL_CONFIG_PATH: `C:\Users\huwe\AppData\Local\Temp\docfx.global.json`
DOCFX_REPOSITORY_BRANCH: `xref-test`

## repro steps

Run `C:\src\Docs.Build\src\docs-pipeline\bin\Debug\netcoreapp2.2\docfx.dll restore --output c:/docs\_site --legacy --verbose c:/docs` in `C:\src\Docs.Build\src\docs-pipeline\bin\Debug\netcoreapp2.2`

## callstack

```
System.ArgumentNullException: String reference not set to an instance of a String.
Parameter name: s
   at System.Text.Encoding.GetBytes(String s)
   at Microsoft.Docs.Build.HashUtility.GetMd5Hash(String input) in C:\src\docfx\src\docfx\lib\HashUtility.cs:line 21
   at Microsoft.Docs.Build.InterProcessMutex.Create(String mutexName) in C:\src\docfx\src\docfx\lib\process\InterProcessMutex.cs:line 27
   at Microsoft.Docs.Build.RestoreMap.TryGetRestoredFileContent(String url) in C:\src\docfx\src\docfx\restore\RestoreMap.cs:line 156
   at Microsoft.Docs.Build.RestoreFile.Restore(String url, Config config) in C:\src\docfx\src\docfx\restore\RestoreFile.cs:line 27
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass2_0`1.<<ForEach>g__Run|0>d.MoveNext() in C:\src\docfx\src\docfx\lib\ParallelUtility.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Docs.Build.ParallelUtility.ForEach[T](IEnumerable`1 source, Func`2 action, Action`2 progress) in C:\src\docfx\src\docfx\lib\ParallelUtility.cs:line 59
   at Microsoft.Docs.Build.Restore.<>c__DisplayClass0_0.<<Run>g__RestoreOneDocset|0>d.MoveNext() in C:\src\docfx\src\docfx\restore\Restore.cs:line 83
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Docs.Build.Restore.<>c__DisplayClass0_2.<<Run>b__2>d.MoveNext() in C:\src\docfx\src\docfx\restore\Restore.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Docs.Build.Restore.Run(String docsetPath, CommandLineOptions options, ErrorLog errorLog) in C:\src\docfx\src\docfx\restore\Restore.cs:line 25
   at Microsoft.Docs.Build.Docfx.Run(String[] args) in C:\src\docfx\src\docfx\cli\Docfx.cs:line 78
   at Microsoft.Docs.Build.Docfx.Main(String[] args) in C:\src\docfx\src\docfx\cli\Docfx.cs:line 24
```

## dotnet --info

```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.300
 Commit:    73efd5bd87

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18362
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.300\

Host (useful for support):
  Version: 2.2.5
  Commit:  0a3c9209c0

.NET Core SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.502 [C:\Program Files\dotnet\sdk]
  2.1.503 [C:\Program Files\dotnet\sdk]
  2.1.504 [C:\Program Files\dotnet\sdk]
  2.1.602 [C:\Program Files\dotnet\sdk]
  2.1.604 [C:\Program Files\dotnet\sdk]
  2.1.700 [C:\Program Files\dotnet\sdk]
  2.2.104 [C:\Program Files\dotnet\sdk]
  2.2.202 [C:\Program Files\dotnet\sdk]
  2.2.203 [C:\Program Files\dotnet\sdk]
  2.2.204 [C:\Program Files\dotnet\sdk]
  2.2.300 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by OsmondJiang** [comment]
Can't repro this issue locally, since there are some change in you local files and they are related to this stack, I assume that it's related to your change, so close this issue now.
