### ISSUE TITLE
Chocolatey Installation Throws UnauthorizedAccessException

### ISSUE THREAD

**Issue by weifenluo** [dotnet/docfx#4835]
**Operation System**: `Windows`

**DocFX Version Used**: 2.43.2

**Template used**: `default`

**Steps to Reproduce**:

1. Install DocFX via Chocolatey.
2. Run `docfx` at any docfx.json.
3. An `UnauthorizedAccessException` thrown:
```
[19-07-03 10:36:24.306]Error:System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\lib\docfx\tools\plugins_hkfrs545.bob\plugins' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Microsoft.DocAsCode.Build.Engine.TemplateManager.Copy(Action`1 streamHandler, String filePath, Boolean overwrite)
   at Microsoft.DocAsCode.Build.Engine.TemplateManager.TryExportResourceFiles(IEnumerable`1 resourceNames, String outputDirectory, Boolean overwrite, String regexFilter)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
        78 Warning(s)
        1 Error(s)
```

**Expected Behavior**:
No exception thrown, temporary directory should be created under directory returned by `Path.GetTempPath()`, not relative to the executing assembly.

**Comment by superyyrrzz** [comment]
Thank you for your feedback and this is a missing scenario when we design plugin locations. I agree your expected behavior is ideal.

The current workaround is to use docfx in a console with admin permission, or user docfx from [releases zip](https://github.com/dotnet/docfx/releases) to avoid authorization issue.
