### ISSUE TITLE
docfx crash report: System.InvalidOperationException

### ISSUE THREAD

**Issue by eduardoperez2151** [dotnet/docfx#4898]
# docfx crash report: System.InvalidOperationException

docfx: `3.0.0-beta-01112-c75ed4892`
dotnet: `2.2.301`
x64: `True`
git: `git version 2.17.1`

## repro steps

Run `/home/eduardo/.dotnet/tools/.store/docfx/3.0.0-beta-01112-c75ed4892/docfx/3.0.0-beta-01112-c75ed4892/tools/netcoreapp2.2/any/docfx.dll watch` in `/home/eduardo/ProjectTemplate`

## callstack

```
System.InvalidOperationException: No service for type 'Microsoft.AspNetCore.Hosting.Server.IServer' has been registered.
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureServer()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.StartAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token, String shutdownMessage)
   at Microsoft.AspNetCore.Hosting.WebHostExtensions.RunAsync(IWebHost host, CancellationToken token)
   at Microsoft.Docs.Build.Docfx.Run(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 89
   at Microsoft.Docs.Build.Docfx.Main(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 24
```

**Comment by yufeih** [comment]
Hi @eduardoperez2151 , 

Thank you for reporting this, `docfx watch` is currently not in an runable state, thus close as designed.
