### ISSUE TITLE
docfx crash report: System.IO.DirectoryNotFoundException

### ISSUE THREAD

**Issue by vermiculus** [dotnet/docfx#5165]
# docfx crash report: System.IO.DirectoryNotFoundException

docfx: `3.0.0-beta-01261-52746d1b2+52746d1b2731665a6b9b1220711d8ab87a3bbf5a`
dotnet: `2.2.103`
x64: `True`
git: `git version 2.22.0`

## repro steps

Run `/Users/sean/.dotnet/tools/.store/docfx/3.0.0-beta-01261-52746d1b2/docfx/3.0.0-beta-01261-52746d1b2/tools/netcoreapp2.2/any/docfx.dll build` in `/Users/sean/git/docfx-test`

## callstack

```
System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/sean/git/docfx-test/_themes/ContentTemplate/.html.liquid'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Microsoft.Docs.Build.LiquidTemplate.LoadTemplate(String fullPath) in D:\a\1\s\src\docfx\template\liquid\LiquidTemplate.cs:line 90
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Docs.Build.LiquidTemplate.Render(String templateName, JObject model)
   at Microsoft.Docs.Build.BuildPage.CreatePageOutput(Context context, Document file, JObject sourceModel) in D:\a\1\s\src\docfx\build\page\BuildPage.cs:line 114
   at Microsoft.Docs.Build.BuildPage.Build(Context context, Document file) in D:\a\1\s\src\docfx\build\page\BuildPage.cs:line 30
   at Microsoft.Docs.Build.Build.BuildFile(Context context, Document file) in D:\a\1\s\src\docfx\build\Build.cs:line 141
   at Microsoft.Docs.Build.Build.Run(Docset docset, Docset fallbackDocset, Dictionary`2 dependencyDocsets, CommandLineOptions options, ErrorLog errorLog, String outputPath, RestoreGitMap restoreGitMap) in D:\a\1\s\src\docfx\build\Build.cs:line 92
   at Microsoft.Docs.Build.Build.Run(String docsetPath, CommandLineOptions options, ErrorLog errorLog) in D:\a\1\s\src\docfx\build\Build.cs:line 37
   at Microsoft.Docs.Build.Docfx.Run(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 90
   at Microsoft.Docs.Build.Docfx.Main(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 25
```
---
I tried to re-create my understanding of the below spec by running:
```sh
mkdir docfx-test && cd docfx-test
touch docfx.yml
mkdir docs
echo 'Hello `docfx`!' >> docs/a.md
docfx build
```

https://github.com/dotnet/docfx/blob/bee9a6292c2ddab3e2f277874db820bd2c18316f/docs/specs/markdown.yml#L2-L8

I've probably misunderstood the spec (flying blind here), but nonetheless crashes are bad :-)

**Comment by live1206** [comment]
Hi @vermiculus, thanks for reporting the issue and even came up with a spec test 👍 
Working on a fix for it.

**Comment by live1206** [comment]
@vermiculus Just to clarify, docfx v3 is not ready for community usage yet.
But if you want to try things out, you can get json output instead of html output as below:
```yml
inputs: 
  docfx.yml: |
    output:
      json: true
  docs/a.md: Hello `docfx`! 
outputs: 
  docs/a.json: |
    {"conceptual": "<p>Hello <code>docfx</code>!</p>\n"}
```

**Comment by vermiculus** [comment]
Thanks!

> docfx v3 is not ready for community usage yet.

I understand 😄 I was only seeing if it was ready to play around with on my mac -- .NET Core is a lot easier to get working than Mono/etc. Just prototyping a few different solutions for now.

---

I'll give JSON output a shot, thanks!
