### ISSUE TITLE
FileNotFoundException when parser meets HTML-encoded characeter in name of ADO wiki artifcle

### ISSUE THREAD

**Issue by abatishchev** [dotnet/docfx#5174]
**Operation System**: Windows

**DocFX Version Used**: 2.40.1.0

**Template used**: default

**Steps to Reproduce**:

1. Create Wiki project in Azure DevOps
2. Create an article that contains dash, e.g. "On-call duties".
3. Observer it's encoded and saved into `On%252Dcall-duties.md`.
4. Clone project's Git repo
5. Use default docfx.json
6. Run docfx.exe

**Expected Behavior**:

HTML-escaped characters in files and directories are parsed accordingly

**Actual Behavior**:

```
[19-09-30 06:35:55.841]Info:[BuildCommand]6 plug-in(s) loaded.
[19-09-30 06:35:55.851]Info:[BuildCommand]Post processor ExtractSearchIndex loaded.
[19-09-30 06:35:56.016]Info:[BuildCommand]Markdown engine is markdig
[19-09-30 06:35:56.346]Info:[BuildCommand]Cannot load build info: 'build.info' not found under 'D:\Projects\MyWiki\obj\.cache\build'
[19-09-30 06:35:56.371]Info:[BuildCommand.BuildCore.Build Document]Max parallelism is 8.
[19-09-30 06:35:56.411]Info:[BuildCommand.BuildCore.Build Document.Prepare.CreateIncrementalBuildContext]Build strategy: IsFullBuild
[19-09-30 06:35:56.511]Info:[BuildCommand]Completed building documents in 657.4191 milliseconds.
[19-09-30 06:35:56.511]Info:[BuildCommand]Completed Scope:BuildCommand in 838.2291 milliseconds.
[19-09-30 06:35:56.521]Error:System.IO.FileNotFoundException: Could not find file 'D:\Projects\MyWiki\MyWiki\Articles\On-call duties.md'.
File name: 'D:\Projects\MyWiki\MyWiki\Articles\On-call duties.md'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Microsoft.DocAsCode.Build.Engine.Incrementals.IncrementalBuildContext.InitFileAttributes()
   at Microsoft.DocAsCode.Build.Engine.Incrementals.IncrementalBuildContext.Create(DocumentBuildParameters parameters, BuildInfo cb, BuildInfo lb, String intermediateFolder, String markdownServiceContextHash)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.Prepare(DocumentBuildParameters parameters, DocumentBuildContext context, TemplateProcessor templateProcessor, String markdownServiceContextHash, IHostServiceCreator& hostServiceCreator, PhaseProcessor& phaseProcessor)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.Build(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
[19-09-30 06:35:56.521]Info:Completed in 849.6556 milliseconds
```

**Comment by cmossell** [comment]
Anyone know a workaround for this issue? Other than renaming the original wiki articles?

**Comment by yufeih** [comment]
The exception does not raise in the latest version yet links to the output page is wrong.
