### ISSUE TITLE
docfx crash report: System.IO.IOException

### ISSUE THREAD

**Issue by pluskal** [dotnet/docfx#5208]
# docfx crash report: System.IO.IOException

docfx: `3.0.0-beta-01308-110a493ce+110a493ce8ac20451aacadc24f8f11d8bd8112ae`
dotnet: `3.0.100`
x64: `True`
git: `git version 2.23.0.windows.1`

## repro steps

Run `C:\XXX\.dotnet\tools\.store\docfx\3.0.0-beta-01308-110a493ce\docfx\3.0.0-beta-01308-110a493ce\tools\netcoreapp2.2\any\docfx.dll restore .\docfx.json` in `C:\XXX\source\repos\YYY\docs\ZZZ.Docs`

## callstack

```
System.IO.IOException: The parameter is incorrect : 'C:\Users\pluskal.NESAD\source\repos\enneract\docs\Enneract.Docs\docfx.json'
   at System.IO.Enumeration.FileSystemEnumerator`1.GetData()
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Docs.Build.ConfigLoader.FindDocsets(String workingDirectory, CommandLineOptions options) in D:\a\1\s\src\docfx\config\ConfigLoader.cs:line 42
   at Microsoft.Docs.Build.Restore.Run(String workingDirectory, CommandLineOptions options) in D:\a\1\s\src\docfx\restore\Restore.cs:line 16
   at Microsoft.Docs.Build.Docfx.Run(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 76
   at Microsoft.Docs.Build.Docfx.Main(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 25
```

**Comment by pluskal** [comment]
Automatically opened by crashed `docfx restore` ... closing.
