### ISSUE TITLE
docfx crash report: System.InvalidOperationException

### ISSUE THREAD

**Issue by cillroy** [dotnet/docfx#5466]
# docfx crash report: System.InvalidOperationException

docfx: `3.0.0-beta-01460-4f008e94d+4f008e94dfb5f46b15bb40485bc6d5dc8e1b5032`
dotnet: `3.1.100`
x64: `True`
git: `git version 2.25.0.rc2.windows.1`
DOCFX_REPOSITORY_BRANCH: `docs-build-v3`
DOCFX_REPOSITORY_URL: `https://github.com/MicrosoftDocs/azure-docs-pr`

## repro steps

Run `C:\Users\cucullen\.vscode\extensions\ceapex.docs-build-0.1.8\.docfx\docfx.dll build c:\repos\azure-docs-pr --legacy --output c:\repos\azure-docs-pr\_site` in `C:\Users\cucullen\.vscode\extensions\ceapex.docs-build-0.1.8\.docfx`

## callstack

```
System.InvalidOperationException: The view 'LandingData' was not found. The following locations were searched:
/Views/Template/LandingData.cshtml
/Views/Shared/LandingData.cshtml
/Pages/Shared/LandingData.cshtml
   at Microsoft.AspNetCore.Mvc.ViewEngines.ViewEngineResult.EnsureSuccessful(IEnumerable`1 originalLocations)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.TestHost.HttpContextBuilder.<>c__DisplayClass10_0.<<SendAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.TestHost.TestServer.SendAsync(Action`1 configureContext, CancellationToken cancellationToken)
   at Microsoft.Docs.Build.RazorTemplate.Render(String template, Object model) in D:\a\1\s\src\docfx\template\RazorTemplate.cs:line 28
   at Microsoft.Docs.Build.BuildPage.LoadSchemaDocument(Context context, List`1 errors, JToken token, Document file) in D:\a\1\s\src\docfx\build\page\BuildPage.cs:line 274
   at Microsoft.Docs.Build.BuildPage.LoadYaml(Context context, Document file) in D:\a\1\s\src\docfx\build\page\BuildPage.cs:line 229
   at Microsoft.Docs.Build.BuildPage.Load(Context context, Document file) in D:\a\1\s\src\docfx\build\page\BuildPage.cs:line 187
   at Microsoft.Docs.Build.BuildPage.Build(Context context, Document file) in D:\a\1\s\src\docfx\build\page\BuildPage.cs:line 22
   at Microsoft.Docs.Build.Build.BuildFile(Context context, FilePath path) in D:\a\1\s\src\docfx\build\Build.cs:line 169
   at Microsoft.Docs.Build.Build.Run(Docset docset, Docset fallbackDocset, CommandLineOptions options, ErrorLog errorLog, String outputPath, Input input, RepositoryProvider repositoryProvider, LocalizationProvider localizationProvider) in D:\a\1\s\src\docfx\build\Build.cs:line 115
   at Microsoft.Docs.Build.Build.BuildDocset(String docsetPath, String outputPath, CommandLineOptions options) in D:\a\1\s\src\docfx\build\Build.cs:line 61
   at Microsoft.Docs.Build.Build.Run(String workingDirectory, CommandLineOptions options) in D:\a\1\s\src\docfx\build\Build.cs:line 24
   at Microsoft.Docs.Build.Docfx.Run(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 82
   at Microsoft.Docs.Build.Docfx.Main(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 26
```

**Comment by 928PJY** [comment]
Hi Curt, this is a known issue, and it has been fixed now. Please try the latest version of `Docs validation`(v0.1.9).
