### ISSUE TITLE
ArgumentNullException in newer version of docfx NuGet (2.49)

### ISSUE THREAD

**Issue by wiwei** [dotnet/docfx#5536]
**Operation System**: Windows

**DocFX Version Used**: 2.49

**Template used**: `default`

**Steps to Reproduce**:
Run docfx docfx.json -f on the following project:

https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/docfx.json

https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=9516&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=a4822bc1-f3a9-5984-c941-6c1b7aa2ab81

Note that this seems to be a regression in the latest docfx NuGet package. We previously were using the latest (2.48.1) which was working fine, and after pulling the newer package (2.49) this issue started happening. To work around this we're forcing our infrastructure to use an older version (i.e. 2.48.1) which is still working fine for us.

**Expected Behavior**:
No exception

**Actual Behavior**:
2020-02-18T18:04:54.4278760Z Parameter name: key
2020-02-18T18:04:54.4279171Z    at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
2020-02-18T18:04:54.4279350Z    at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
2020-02-18T18:04:54.4279504Z    at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
2020-02-18T18:04:54.4279710Z    at Microsoft.DocAsCode.Metadata.ManagedReference.CopyInherited.Copy(MetadataItem dest, String srcName, ResolverContext context)
2020-02-18T18:04:54.4279934Z    at Microsoft.DocAsCode.Metadata.ManagedReference.CopyInherited.InheritDoc(MetadataItem dest, ResolverContext context)
2020-02-18T18:04:54.4280101Z    at Microsoft.DocAsCode.Metadata.ManagedReference.CopyInherited.<>c__DisplayClass0_0.<Run>b__1(MetadataItem current, MetadataItem parent)
2020-02-18T18:04:54.4280283Z    at Microsoft.DocAsCode.Common.TreeIterator.Preorder[T](T current, T parent, Func`2 childrenGetter, Func`3 action)
2020-02-18T18:04:54.4280473Z    at Microsoft.DocAsCode.Common.TreeIterator.Preorder[T](T current, T parent, Func`2 childrenGetter, Func`3 action)
2020-02-18T18:04:54.4280633Z    at Microsoft.DocAsCode.Common.TreeIterator.Preorder[T](T current, T parent, Func`2 childrenGetter, Func`3 action)
2020-02-18T18:04:54.4280870Z    at Microsoft.DocAsCode.Common.TreeIterator.Preorder[T](T current, T parent, Func`2 childrenGetter, Func`3 action)
2020-02-18T18:04:54.4281192Z    at Microsoft.DocAsCode.Metadata.ManagedReference.CopyInherited.Run(MetadataModel yaml, ResolverContext context)
2020-02-18T18:04:54.4281410Z    at Microsoft.DocAsCode.Metadata.ManagedReference.YamlMetadataResolver.ExecutePipeline(MetadataModel yaml, ResolverContext context)
2020-02-18T18:04:54.4281664Z    at Microsoft.DocAsCode.Metadata.ManagedReference.YamlMetadataResolver.ResolveMetadata(Dictionary`2 allMembers, Dictionary`2 allReferences, Boolean preserveRawInlineComments)
2020-02-18T18:04:54.4281929Z    at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ResolveAndExportYamlMetadata>d__19.MoveNext()
2020-02-18T18:04:54.4282140Z    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
2020-02-18T18:04:54.4282329Z    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
2020-02-18T18:04:54.4282543Z    at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
2020-02-18T18:04:54.4282833Z --- End of stack trace from previous location where exception was thrown ---
2020-02-18T18:04:54.4282986Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2020-02-18T18:04:54.4283139Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2020-02-18T18:04:54.4283291Z    at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
2020-02-18T18:04:54.4283488Z 	0 Warning(s)
2020-02-18T18:04:54.4283593Z 	1 Error(s)

**Comment by tstivers1990** [comment]
Also experiencing this issue.

**Comment by nike4613** [comment]
Also experiencing this issue with DocFX 2.49 from Chocolatey.

**Comment by wiwei** [comment]
@yufeih @mingwli have you guys considered rolling back the latest version? It seems like it's causing trouble for a lot of consumers out there judging by the number of duplicate issues and other confirmations.

**Comment by superyyrrzz** [comment]
@wiwei #5561 should fix this. Could you try DocFX >= 2.50?
