### ISSUE TITLE
docfx crash report: System.InvalidOperationException

### ISSUE THREAD

**Issue by 928PJY** [dotnet/docfx#5635]
# docfx crash report: System.InvalidOperationException

docfx: `1.0.0+fbb9d2d585952542e6940371b77f885ace71831f`
dotnet: `3.1.200`
x64: `True`
git: `git version 2.21.0.windows.1`
DOCFX_REPOSITORY_URL: `https://github.com/MicrosoftDocs/OfficeDocs-OfficeUpdates-pr`
DOCFX_GLOBAL_CONFIG_PATH: `C:\Users\jipe\Desktop\docfx.global.json`

## repro steps

Run `E:\docfx\src\docfx\bin\Debug\netcoreapp3.1\docfx.dll build D:\docs-repos\OfficeDocs-OfficeUpdates-pr --legacy` in `E:\docfx\src\docfx\bin\Debug\netcoreapp3.1`

## callstack

```
System.InvalidOperationException: Error reading 'common/Office/media/icons/Small-business.svg [common]'
   at Microsoft.Docs.Build.Input.ReadStream(FilePath file) in E:\docfx\src\docfx\build\context\Input.cs:line 136
   at Microsoft.Docs.Build.Output.Copy(Document file, String destRelativePath) in E:\docfx\src\docfx\build\context\Output.cs:line 62
   at Microsoft.Docs.Build.BuildResource.Build(Context context, Document file) in E:\docfx\src\docfx\build\resource\BuildResource.cs:line 43
   at Microsoft.Docs.Build.Build.BuildFile(Context context, FilePath path) in E:\docfx\src\docfx\build\Build.cs:line 150
   at Microsoft.Docs.Build.Build.Run(Config config, Docset docset, Docset fallbackDocset, CommandLineOptions options, ErrorLog errorLog, String outputPath, Input input, RepositoryProvider repositoryProvider, LocalizationProvider localizationProvider, PackageResolver packageResolver) in E:\docfx\src\docfx\build\Build.cs:line 93
   at Microsoft.Docs.Build.Build.BuildDocset(String docsetPath, String outputPath, CommandLineOptions options) in E:\docfx\src\docfx\build\Build.cs:line 60
   at Microsoft.Docs.Build.Build.Run(String workingDirectory, CommandLineOptions options) in E:\docfx\src\docfx\build\Build.cs:line 25
   at Microsoft.Docs.Build.Docfx.Run(String[] args) in E:\docfx\src\docfx\cli\Docfx.cs:line 82
   at Microsoft.Docs.Build.Docfx.Main(String[] args) in E:\docfx\src\docfx\cli\Docfx.cs:line 26
```

**Comment by yufeih** [comment]
The `dependencyName` should be `OfficeUpdates/common` but somehow it becomes `common`.

**Comment by yufeih** [comment]
@928PJY , Can you double check with the repo owner that they indeed want to publish the dependency content? I looked at the dependency repo, the files seems to be for include only.

**Comment by 928PJY** [comment]
@yufeih I can confirm with the repo owner, but are we supposed to support the CRR content?

**Comment by yufeih** [comment]
Yes, and I'm fixing it 👍
