### ISSUE TITLE
YamlException building docs

### ISSUE THREAD

**Issue by grokys** [dotnet/docfx#570]
### Title
When I try to build the docs for the Avalonia project, a `YamlException` is thrown.

### Minimal repro steps
1. Check out https://github.com/AvaloniaUI/Avalonia/commit/5b26034de0844681a7a9d9615dbc523e2a204be0
2. Go to the docs folder
3. Run docfx (version 2.2.2)

### Result

The following exception is thrown:

```
Error: System.AggregateException: One or more errors occurred. ---> YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): No node deserializer was able to deserialize the node into type Microsoft.DocAsCode.DataContracts.ManagedReference.PageViewModel, Microsoft.DocAsCode.DataContracts.ManagedReference, Version=2.2.2.0, Culture=neutral, PublicKeyToken=null
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(EventReader reader, Type type, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
   at Microsoft.DocAsCode.Build.ManagedReference.ManagedReferenceDocumentProcessor.Load(FileAndType file, ImmutableDictionary`2 metadata)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.Load(IDocumentProcessor processor, ImmutableDictionary`2 metadata, FileMetadata fileMetadata, FileAndType file)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   at System.Collections.Immutable.ImmutableList`1.FillFromEmpty(IEnumerable`1 items)
   at Microsoft.DocAsCode.Build.Engine.HostService.LoadCore(IEnumerable`1 models)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.<>c__DisplayClass48_0.<GetInnerContexts>b__11(IGrouping`2 item)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
   at System.Linq.Parallel.AsynchronousChannelMergeEnumerator`1.MoveNextSlowPath()
   at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(DocumentBuildParameters parameters)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) YamlDotNet.Core.YamlException: (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): No node deserializer was able to deserialize the node into type Microsoft.DocAsCode.DataContracts.ManagedReference.PageViewModel, Microsoft.DocAsCode.DataContracts.ManagedReference, Version=2.2.2.0, Culture=neutral, PublicKeyToken=null
   at YamlDotNet.Serialization.ValueDeserializers.NodeValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.LooseAliasValueDeserializer.DeserializeValue(EventReader reader, Type expectedType, SerializerState state, IValueDeserializer nestedObjectDeserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize(EventReader reader, Type type, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.YamlSerialization.YamlDeserializer.Deserialize[T](TextReader input, IValueDeserializer deserializer)
   at Microsoft.DocAsCode.Common.YamlUtility.Deserialize[T](String path)
   at Microsoft.DocAsCode.Build.ManagedReference.ManagedReferenceDocumentProcessor.Load(FileAndType file, ImmutableDictionary`2 metadata)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.Load(IDocumentProcessor processor, ImmutableDictionary`2 metadata, FileMetadata fileMetadata, FileAndType file)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableExtensions.FallbackWrapper`1.get_Count()
   at System.Collections.Immutable.ImmutableList`1.FillFromEmpty(IEnumerable`1 items)
   at Microsoft.DocAsCode.Build.Engine.HostService.LoadCore(IEnumerable`1 models)
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.<>c__DisplayClass48_0.<GetInnerContexts>b__11(IGrouping`2 item)
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorEnumerator`1.MoveNext(TOutput& currentElement, TKey& currentKey)
   at System.Linq.Parallel.PipelineSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.Tasks.Task.Execute()<---

        4 Warning(s)
        1 Error(s)
```

**Comment by vwxyzh** [comment]
Please remove "filterConfig.yml" from content.
E.g.:
> "exclude": [ "filterConfig.yml" ]

Hint:
Also exclude your output folder from content.

**Comment by vwxyzh** [comment]
If it does not work, please reopen the issue.

**Comment by grokys** [comment]
`"filterConfig.yml" ` is not in the content at the revision I specified - 5b26034. At that revision the `docfx.json` file looks like this: https://github.com/AvaloniaUI/Avalonia/blob/5b26034de0844681a7a9d9615dbc523e2a204be0/docs/docfx.json

**Comment by grokys** [comment]
Also @vwxyzh I cannot reopen this issue. Can you do it for me?

**Comment by vwxyzh** [comment]
>    "content":
>     [
>        {
>          "files": [___"\*\*/\*.yml"___, "index.md", "tutorial/*.md", "guidelines/*.md", "spec/*.md"],
>        }
>      ],
