### ISSUE TITLE
docfx crash report: System.AggregateException

### ISSUE THREAD

**Issue by KuriharaJun** [dotnet/docfx#5759]
# docfx crash report: System.AggregateException

docfx: `3.0.0-beta-01668-b003f1871+b003f1871ab83add50b1630cc4fc00cde922d2dc`
dotnet: `3.1.102`
x64: `True`
git: `git version 2.25.1`
operatig system: WSL2(WLinux)

## repro steps

Run `/home/xxxx/.dotnet/tools/.store/docfx/3.0.0-beta-01668-b003f1871/docfx/3.0.0-beta-01668-b003f1871/tools/netcoreapp3.1/any/docfx.dll build` in `/home/xxxx/projects/foo-project`

## callstack

```
System.AggregateException: One or more errors occurred. (The type initializer for 'Microsoft.Docs.Build.LibGit2' threw an exception.)
 ---> System.TypeInitializationException: The type initializer for 'Microsoft.Docs.Build.LibGit2' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'git2-ef5a385' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-ef5a385: cannot open shared object file: No such file or directory
   at Microsoft.Docs.Build.LibGit2.git_libgit2_init()
   at Microsoft.Docs.Build.LibGit2..cctor() in D:\a\1\s\src\docfx\lib\git\LibGit2.cs:line 19
   --- End of inner exception stack trace ---
   at Microsoft.Docs.Build.LibGit2.git_repository_open(IntPtr& repo, String path)
   at Microsoft.Docs.Build.GitUtility.IsGitRepository(String path) in D:\a\1\s\src\docfx\lib\git\GitUtility.cs:line 42
   at Microsoft.Docs.Build.GitUtility.FindRepository(String path) in D:\a\1\s\src\docfx\lib\git\GitUtility.cs:line 23
   at Microsoft.Docs.Build.Repository.Create(String path, String branch, String repoUrl) in D:\a\1\s\src\docfx\lib\git\Repository.cs:line 44
   at Microsoft.Docs.Build.Repository.Create(String path) in D:\a\1\s\src\docfx\lib\git\Repository.cs:line 32
   at Microsoft.Docs.Build.ConfigLoader.Load(String docsetPath, String outputPath, CommandLineOptions options) in D:\a\1\s\src\docfx\config\ConfigLoader.cs:line 51
   at Microsoft.Docs.Build.Restore.RestoreDocset(String docsetPath, String outputPath, CommandLineOptions options) in D:\a\1\s\src\docfx\restore\Restore.cs:line 47
   at Microsoft.Docs.Build.Build.<>c__DisplayClass0_0.<Run>b__0(ValueTuple`2 docset) in D:\a\1\s\src\docfx\build\Build.cs:line 26
   at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker[TLocal](Int32 fromInclusive, Int32 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](TSource[] array, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
   at Microsoft.Docs.Build.Build.Run(String workingDirectory, CommandLineOptions options) in D:\a\1\s\src\docfx\build\Build.cs:line 37
   at Microsoft.Docs.Build.Docfx.Run(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 76
   at Microsoft.Docs.Build.Docfx.Main(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 25
```

**Comment by yufeih** [comment]
dup of #5816
