### ISSUE TITLE
docfx crash report: System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by jamarw** [dotnet/docfx#6317]
# docfx crash report: System.IO.FileNotFoundException

docfx: `3.0.0-beta1.227+3372d2cce4`
dotnet: `3.1.302`
x64: `True`
os: `Microsoft Windows 10.0.19041`
git: `git version 2.23.0.windows.1`

## repro steps

Run `C:\GitHub\jamarw\docfx\src\docfx\bin\Debug\netcoreapp3.1\docfx.dll build C:\GitHub\azure-docs-pr -v` in `C:\GitHub\jamarw\docfx\src\docfx\bin\Debug\netcoreapp3.1`

## callstack

```
System.IO.FileNotFoundException: Could not find file 'C:\Users\jamarw\.docfx\git6\github.com+Microsoft+template..ocs.msft+95403dd1-master\ContentTemplate\toc.html.tmpl.tmpl.partial'.
File name: 'C:\Users\jamarw\.docfx\git6\github.com+Microsoft+template..ocs.msft+95403dd1-master\ContentTemplate\toc.html.tmpl.tmpl.partial'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at Microsoft.Docs.Build.MustacheTemplate.<>c__DisplayClass12_0.<GetTemplate>b__1() in C:\GitHub\jamarw\docfx\src\docfx\template\MustacheTemplate.cs:line 200
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at Microsoft.Docs.Build.MustacheTemplate.GetTemplate(String name) in C:\GitHub\jamarw\docfx\src\docfx\template\MustacheTemplate.cs:line 192
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at Microsoft.Docs.Build.MustacheTemplate.Render(String templateFileName, JToken model, FilePath file) in C:\GitHub\jamarw\docfx\src\docfx\template\MustacheTemplate.cs:line 41
   at Microsoft.Docs.Build.TemplateEngine.RunMustache(String templateName, JToken pageModel, FilePath file) in C:\GitHub\jamarw\docfx\src\docfx\template\TemplateEngine.cs:line 86
   at Microsoft.Docs.Build.BuildTableOfContents.Build(Context context, Document file) in C:\GitHub\jamarw\docfx\src\docfx\build\toc\BuildTableOfContents.cs:line 50
   at Microsoft.Docs.Build.Build.BuildFile(Context context, FilePath path) in C:\GitHub\jamarw\docfx\src\docfx\build\Build.cs:line 130
   at Microsoft.Docs.Build.Build.<>c__DisplayClass2_0.<Run>b__12(FilePath file) in C:\GitHub\jamarw\docfx\src\docfx\build\Build.cs:line 87
   at Microsoft.Docs.Build.ParallelUtility.<>c__DisplayClass3_0`1.<ForEach>b__0(T item) in C:\GitHub\jamarw\docfx\src\docfx\lib\ParallelUtility.cs:line 40
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by yufeih** [comment]
Yep, this is a known issue of the current static rendering implementation. Thanks for bring it up 👍

**Comment by yufeih** [comment]
Just to unblock you, if you are building against a Microsoft Docs repo, adding a `--legacy` option would workaround the problem.

**Comment by jamarw** [comment]
> Just to unblock you, if you are building against a Microsoft Docs repo, adding a `--legacy` option would workaround the problem.

Thanks @yufeih !
