### ISSUE TITLE
NullReferenceException: CSharpNameVisitor.VisitNamedType

### ISSUE THREAD

**Issue by Jcouls29** [dotnet/docfx#648]
### Title

When generating metadata for a large solution (16 projects including test projects and web applications and class libraries) I get the exception below. There isn't any clear idea what to fix it. Any ideas?
### Functional impact

Cannot complete the metadata step
### Expected result

Finish the metadata output
### Actual result

Exception:

```
"System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: 
Error extracting metadata for 
{
    "Items":{
        "api":[
            {Project List}
        ]
        },
        "ApiFolderName":"",
        "TocFileName":"toc.yml",
        "IndexFileName":".manifest",
        "PreserveRawInlineComments":false,
        "ForceRebuild":false,
        "UseCompatibilityFileName":false
    }: 
System.NullReferenceException: Object reference not set to an instance of an object.   
at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.NameVisitorCreator.GetName(ISymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.CSReferenceItemVisitor.AddLinkItems(INamedTypeSymbol symbol, Boolean withGenericeParameter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ReferenceItemVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ReferenceItemVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateReferenceInternal(ISymbol symbol, ReferenceItem reference, SymbolVisitorAdapter adapter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.YamlModelGenerator.AddSpecReference(ISymbol symbol, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters, Dictionary`2 references, SymbolVisitorAdapter adapter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.AddMethodSyntax(IMethodSymbol symbol, MetadataItem result, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitMethod(IMethodSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext() 
---> System.NullReferenceException: Object reference not set to an instance of an object.   
at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.NameVisitorCreator.GetName(ISymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.CSReferenceItemVisitor.AddLinkItems(INamedTypeSymbol symbol, Boolean withGenericeParameter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ReferenceItemVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ReferenceItemVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateReferenceInternal(ISymbol symbol, ReferenceItem reference, SymbolVisitorAdapter adapter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.YamlModelGenerator.AddSpecReference(ISymbol symbol, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters, Dictionary`2 references, SymbolVisitorAdapter adapter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.AddMethodSyntax(IMethodSymbol symbol, MetadataItem result, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitMethod(IMethodSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext()   
--- End of inner exception stack trace ---   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext()   
--- End of inner exception stack trace ---   
at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)   
at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)   
at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)   
at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
---> (Inner Exception #0) Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for 
{
    "Items":
    {
        "api":[
            {Project List}
        ]
    },
    "ApiFolderName":"",
    "TocFileName":"toc.yml",
    "IndexFileName":".manifest",
    "PreserveRawInlineComments":false,
    "ForceRebuild":false,
    "UseCompatibilityFileName":false
}: 
System.NullReferenceException: Object reference not set to an instance of an object.   
at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.NameVisitorCreator.GetName(ISymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.CSReferenceItemVisitor.AddLinkItems(INamedTypeSymbol symbol, Boolean withGenericeParameter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ReferenceItemVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ReferenceItemVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateReferenceInternal(ISymbol symbol, ReferenceItem reference, SymbolVisitorAdapter adapter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.YamlModelGenerator.AddSpecReference(ISymbol symbol, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters, Dictionary`2 references, SymbolVisitorAdapter adapter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.AddMethodSyntax(IMethodSymbol symbol, MetadataItem result, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitMethod(IMethodSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext() 
---> System.NullReferenceException: Object reference not set to an instance of an object.   
at Microsoft.DocAsCode.Metadata.ManagedReference.CSharpNameVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.NameVisitorCreator.GetName(ISymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.CSReferenceItemVisitor.AddLinkItems(INamedTypeSymbol symbol, Boolean withGenericeParameter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ReferenceItemVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ReferenceItemVisitor.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateReferenceInternal(ISymbol symbol, ReferenceItem reference, SymbolVisitorAdapter adapter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.YamlModelGenerator.AddSpecReference(ISymbol symbol, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters, Dictionary`2 references, SymbolVisitorAdapter adapter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.AddMethodSyntax(IMethodSymbol symbol, MetadataItem result, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitMethod(IMethodSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)   
at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<GetMetadataFromProjectLevelCacheAsync>d__36`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---   
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)   
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext()   
--- End of inner exception stack trace ---   
at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__16.MoveNext()<---",
"date_time":"2016-08-30T15:59:49.752919Z","message_severity":"error"
}
```

**Comment by Jcouls29** [comment]
Meant to add I'm working with DocFX v2.4.0.60829

**Comment by vwxyzh** [comment]
@Jcouls29 We have add more information in exception, can you run your project with our newest dev branch version? You can download it from [here](https://myget.org/feed/docfx-dev/package/nuget/docfx.msbuild).

**Comment by Jcouls29** [comment]
{"message":"System.AggregateException: One or more errors occurred. ---> Microsoft.DocAsCode.Exceptions.ExtractMetadataException: Error extracting metadata for {"Items":{"api":[{projects}]},"ApiFolderName":"","TocFileName":"toc.yml","IndexFileName":".manifest","PreserveRawInlineComments":false,"ForceRebuild":false,"UseCompatibilityFileName":false}: Microsoft.DocAsCode.Exceptions.DocfxException: Unable to generate spec reference for T:System.Collections.Generic.IEnumerable{MyClassName} ---> System.NullReferenceException: Object reference not set to an instance of an object.

Yes this is better. At least it tells me what class is having the issue. I can then go through and investigate.

As it turns out, an orphaned project was in the folder structure and docfx picked it up based on my docfx configuration (""**.vbproj", "**.csproj").  Not sure why the error occurred overall, but after removing the orphaned projects, it seemed to work just fine. 

It would be helpful in the future to know exactly what was being analyzed in this case (i.e. the project being analyzed) but this was much more helpful.  Thanks

I would think this issue is good to go.
