### ISSUE TITLE
docfx crash report: System.TypeInitializationException

### ISSUE THREAD

**Issue by eduardoperez2151** [dotnet/docfx#6544]
# docfx crash report: System.TypeInitializationException

docfx: `3.0.0-beta1.372+248100f4b9`
dotnet: `3.1.402`
x64: `True`
os: `Linux 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020`
git: `git version 2.25.1`

## repro steps

Run `/home/edu/.dotnet/tools/.store/docfx/3.0.0-beta1-0372-g248100f4b9/docfx/3.0.0-beta1-0372-g248100f4b9/tools/netcoreapp3.1/any/docfx.dll build docs/docfx.json` in `/home/edu/Escritorio/UCU/PII_ProjectTemplate`

## callstack

```
System.TypeInitializationException: The type initializer for 'Microsoft.Docs.Build.LibGit2' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'git2-ef5a385' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libgit2-ef5a385: cannot open shared object file: No such file or directory
   at Microsoft.Docs.Build.LibGit2.git_libgit2_init()
   at Microsoft.Docs.Build.LibGit2..cctor() in D:\a\1\s\src\docfx\lib\git\LibGit2.cs:line 20
   --- End of inner exception stack trace ---
   at Microsoft.Docs.Build.LibGit2.git_repository_open(IntPtr& repo, String path)
   at Microsoft.Docs.Build.GitUtility.IsGitRepository(String path) in D:\a\1\s\src\docfx\lib\git\GitUtility.cs:line 42
   at Microsoft.Docs.Build.GitUtility.FindRepository(String path) in D:\a\1\s\src\docfx\lib\git\GitUtility.cs:line 23
   at Microsoft.Docs.Build.Repository.Create(String path, String branch, String repoUrl) in D:\a\1\s\src\docfx\lib\git\Repository.cs:line 46
   at Microsoft.Docs.Build.Repository.Create(String path) in D:\a\1\s\src\docfx\lib\git\Repository.cs:line 32
   at Microsoft.Docs.Build.ConfigLoader.Load(ErrorBuilder errors, DisposableCollector disposables, String docsetPath, String outputPath, CommandLineOptions options, FetchOptions fetchOptions) in D:\a\1\s\src\docfx\config\ConfigLoader.cs:line 55
   at Microsoft.Docs.Build.Build.BuildDocset(ErrorBuilder errors, String workingDirectory, String docsetPath, String outputPath, CommandLineOptions options) in D:\a\1\s\src\docfx\build\Build.cs:line 46
   at Microsoft.Docs.Build.Build.<>c__DisplayClass0_0.<Run>b__0(ValueTuple`2 docset) in D:\a\1\s\src\docfx\build\Build.cs:line 29
   at System.Threading.Tasks.Parallel.<>c__DisplayClass32_0`2.<ForEachWorker>b__0(Int32 i)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(Exception source)
   at System.Threading.Tasks.Parallel.<>c__DisplayClass19_0`1.<ForWorker>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
```

**Comment by yufeih** [comment]
Dup of #5816
