### ISSUE TITLE
docfx crash report: System.IO.IOException (v3)

### ISSUE THREAD

**Issue by SMartQi** [dotnet/docfx#6924]
Before reporting the crash, let me do a brief explanation about why and how did it happen.

At first, I followed the steps as Readme saying:

- Create a directory with a docfx.yml config file, markdown files and other contents. See examples in our specification.
- Run docfx restore to restore the dependencies of your docset.
- Run docfx build to build your docset.

But I couldn't write a valid docfx.yml. No matter how did I configure it, all .htmls files in _site folders were blank.

Then, based on the successful experience using the v2 command "docfx init -q", I thought the v3 command "docfx new" might do a similar job and give me a general idea about the config items. So I ran this command in an empty folder and get an error "config-not-found". That's when I put a .yml file into the folder and ran "docfx new --force", hence the crash.

And here's the major problem apart from the crash: How should I configure it? Is there a valid project to refer to? 

Thank you very much.

------------------------------------------------

# docfx crash report: System.IO.IOException

docfx: `3.0.0-beta1.629+3dc3c7cb91`
dotnet: `5.0.101`
x64: `True`
os: `Microsoft Windows 10.0.19042`
git: `git version 2.29.2.windows.3`

## repro steps

Run `C:\Users\xxx\.dotnet\tools\.store\docfx\3.0.0-beta1-0629-g3dc3c7cb91\docfx\3.0.0-beta1-0629-g3dc3c7cb91\tools\netcoreapp3.1\any\docfx.dll new --force` in `D:\testv3`

## callstack

```
System.IO.IOException: The process cannot access the file 'D:\testv3\docfx.yml' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Microsoft.Docs.Build.New.CreateFromTemplate(String type, CommandLineOptions options, Boolean dryRun) in D:\a\1\s\src\docfx\cli\New.cs:line 89
   at Microsoft.Docs.Build.New.Run(String type, CommandLineOptions options) in D:\a\1\s\src\docfx\cli\New.cs:line 25
   at Microsoft.Docs.Build.Docfx.Run(String[] args, Package package) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 81
   at Microsoft.Docs.Build.Docfx.Main(String[] args) in D:\a\1\s\src\docfx\cli\Docfx.cs:line 25
```

**Comment by yufeih** [comment]
Thanks for reporting! I believe this is a bug in our codebase.

**Comment by yufeih** [comment]
The fix will be available in the preview channel by the end of this month
