### ISSUE TITLE
Allow plugin cache directory to be specified

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#7062]
**Operating System**: Linux

**DocFX Version Used**: 2.56.1

**Template used**: default + custom with a plugin

**Steps to Reproduce**:

1. Install docfx in a read-only directory
2. Use a template that contains a plugin

**Expected Behavior**:

Successful build, including the use of the plugin

**Actual Behavior**:

An exception such as:

```text
[21-02-12 09:01:26.615]Error:System.UnauthorizedAccessException: Access to the path '/opt/docfx/plugins_tgwees4f.pjy/plugins' is denied. ---> System.IO.IOException: Permission denied
```

Currently, docfx expects to be able to create a plugin directory underneath `AppDomain.CurrentDomain.BaseDirectory` (in `BuildCommand.BuildDocument(string baseDirectory, string outputDirectory`). That only works if docfx is installed in a user-writable directory, which isn't an ideal situation in general.

Ideally docfx would pick a temporary directory rather than one under the installation directory by default - but even if it can't do that, could we specify a directory on the command line or in docfx.json?

**Comment by paynecrl97** [comment]
I've just ran in to this issue on Windows too. Steps to reproduce:

- Install docfx via chocolatey
- Create a project, and add a template with a plugin. Add the template to your docfx.json file
- Run `docfx build docfx.json --serve`

Expected: successful build, including calling in to the plugin

Actual: build fail, output:

```
Build failed.
[21-02-27 11:41:18.035]Error:System.UnauthorizedAccessException: Access to the path 'C:\ProgramData\chocolatey\lib\docfx\tools\plugins_5zcz34z0.tpv\plugins' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at Microsoft.DocAsCode.Build.Engine.TemplateManager.Copy(Action`1 streamHandler, String filePath, Boolean overwrite)
   at Microsoft.DocAsCode.Build.Engine.TemplateManager.TryExportResourceFiles(IEnumerable`1 resourceNames, String outputDirectory, Boolean overwrite, String regexFilter)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)
        0 Warning(s)
        1 Error(s)
The terminal process "C:\Windows\System32\cmd.exe /d /c docfx build docfx.json --serve --force --exportViewModel" terminated with exit code: 1.
```

**Comment by yufeih** [comment]
This is resolved in the latest version with a new library based extensibility model, see [this sample](https://github.com/dotnet/docfx/tree/main/samples/extensions) on using the member page plugin with the new approach.
