### ISSUE TITLE
NullReferenceException crashing docfx build on Azure DevOps

### ISSUE THREAD

**Issue by CodeBlanch** [dotnet/docfx#7101]
**Operating System**: Windows

**DocFX Version Used**: 2.56.6

**Template used**: default

**Expected Behavior**:

No errors.

**Actual Behavior**:

A bunch of LoaderExceptions and then a NullReferenceException.

[21-02-26 05:24:16.951]Warning:[MetadataCommand.ExtractMetadata](C:/vsts-agent-win-x64-2.172.2/_work/19/s/Project.csproj)Error opening project C:/vsts-agent-win-x64-2.172.2/_work/19/s/Project.csproj: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.. Ignored.

[21-02-26 05:24:16.951]Error:Error extracting metadata for C:/vsts-agent-win-x64-2.172.2/_work/19/s/Project.csproj: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()

**Analysis:**

I did a bunch of digging on this and tried what was suggested on #4869 & #4782, but I think this is something different. With verbose logging turned on:

[21-02-26 05:24:15.831]Info:[MetadataCommand.ExtractMetadata]Using msbuild C:\Program Files (x86)\Microsoft Visual Studio\2019\ **TestAgent** \MSBuild\Current\Bin as inner compiler.

Notice the highlight there, the test version of VS is being selected.

It looks like this was a bug fixed in MSBuildLocator: https://github.com/microsoft/MSBuildLocator/issues/73

A possible fix is to update the dependency docfx has to >=1.3.2?

**Comment by filzrev** [comment]
I thought this issue can be closed by following reasons
- docfx `v2.59.4` is using bug fixed version ([`MSBuildLocator 1.41`](https://github.com/dotnet/docfx/blob/v2.59.4/src/Microsoft.DocAsCode.Metadata.ManagedReference/Microsoft.DocAsCode.Metadata.ManagedReference.csproj#L24))
- Recent version of docfx has no VS instance dependencies
-
