### ISSUE TITLE
docfx fails on Fshap.core assembly

### ISSUE THREAD

**Issue by vDonGlover** [dotnet/docfx#7109]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Window 10
**DocFX Version Used**: 
Version 2.56.6
**Template used**: (`default` or `statictoc` or contain custom template)
default
**Steps to Reproduce**:

1. Download zip file from github and extract into fold
2. initialize a project
3. run docfx to build proct

**Expected Behavior**:
builds new site
**Actual Behavior**:
Fails with the following error.

Build failed.
[21-03-01 11:27:54.495]Error:System.IO.FileLoadException: Could not load file or assembly 'FSharp.Core, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'FSharp.Core, Version=4.6.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.DocAsCode.Metadata.ManagedReference.FSharp.FSharpProjectLoader..ctor(IDictionary`2 msbuildProps)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker..ctor(ExtractMetadataInputModel input)
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.ExecCore()
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

        0 Warning(s)
        1 Error(s)

**Comment by vDonGlover** [comment]
I cleaned the folder, rebooted, and reinstalled. It now works. Not sure what caused the issue.
