### ISSUE TITLE
Unable to run docfx metadata after VS 16.10 installation

### ISSUE THREAD

**Issue by jskeet** [dotnet/docfx#7406]
**Operating System**: Windows

**DocFX Version Used**: 2.57.2

**Template used**: default

**Steps to Reproduce**:

Environmental: Visual Studio 16.10 installed

1. Create a class library project
2. Edit Class1.cs to have a public XML comment
3. Create minimal docfx.json file
4. Run `docfx metadata -f docfx.json`

Zip file with all relevant files: [Metadata.zip](https://github.com/dotnet/docfx/files/6607702/Metadata.zip)

**Expected Behavior**:

Generation of metadata files

**Actual Behavior**:

Warnings:

```text
[21-06-07 09:30:05.829]Info:[ExtractMetadata]Using msbuild C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin as inner compiler.
[21-06-07 09:30:06.054]Info:[ExtractMetadata]Loading projects...
[21-06-07 09:30:07.232]Warning:[ExtractMetadata](C:/Users/jonskeet/Issues/docfx/Metadata/Metadata.csproj)Workspace failed with: [Failure] Msbuild failed when processing the file 'C:\Users\jonskeet\Issues\docfx\Metadata\Metadata.csproj' with message: The SDK 'Microsoft.NET.Sdk' specified could not be found.  C:\Users\jonskeet\Issues\docfx\Metadata\Metadata.csproj                                                                                                                    
[21-06-07 09:30:07.356]Warning:[ExtractMetadata]Project 'C:\Users\jonskeet\Issues\docfx\Metadata\Metadata.csproj' does not contain any documents.
[21-06-07 09:30:07.383]Info:[ExtractMetadata]Generating metadata for each project...
[21-06-07 09:30:07.701]Warning:[ExtractMetadata]No metadata is generated for Metadata.
[21-06-07 09:30:07.705]Info:Completed in 1906.7008 milliseconds
Build succeeded with warning.
```

**Comment by jskeet** [comment]
(There have been several similar issues over the years with the error message of "The SDK 'Microsoft.NET.Sdk' specified could not be found" but they all seem subtly different.)

**Comment by jskeet** [comment]
It looks like [this PR](https://github.com/dotnet/docfx/pull/7384) fixes the issue... so please could we have a new docfx 2.x release, given that VS 16.10 is going to become increasingly prevalent?

Workaround for now:

- Download the nupkg for [Microsoft.Build.Locator 1.4.1](https://www.nuget.org/packages/Microsoft.Build.Locator/1.4.1)
- Open it up as a zip file
- Copy the `lib/net46/Microsoft.Build.Locator.dll` file into the docfx installation

**Comment by wheeler1818** [comment]
We have the same problem with AzureDev Ops. The PR you mentioned fixes the problem. I'm also waiting for a new release.

**Comment by tibel** [comment]
@superyyrrzz Can we get a new release, please?

**Comment by superyyrrzz** [comment]
> @superyyrrzz Can we get a new release, please?

Sure. I will release a new version tomorrow.

**Comment by dotMorten** [comment]
Thank you! Been scratching me head all day on this one. v2.58 fixed it for me.

**Comment by dotMorten** [comment]
So this fixed it for me locally, but my build server now does this after moving to 2.58. Did some requirements change?
```
[21-06-10 09:42:00.317]Info:Plug-in directory: C:\docfx\v2.58\plugins_ruxc5oiu.xnb\plugins, configuration file: C:\docfx\v2.58\plugins_ruxc5oiu.xnb\plugins\docfx.plugins.config
[21-06-10 09:42:01.329]Info:[ImportPlugins]Searching custom plugins in directory C:\docfx\v2.58\plugins_ruxc5oiu.xnb\plugins...

[21-06-10 09:42:02.048]Error:[ImportPlugins]Error when get composition container: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information., loader exceptions: Could not load file or assembly 'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
[21-06-10 09:42:02.160]Info:Cleaning up temporary plugin folder "C:\docfx\v2.58\plugins_ruxc5oiu.xnb"

[21-06-10 09:42:02.174]Error:System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at System.Composition.Hosting.ContainerConfiguration.<>c.<WithAssemblies>b__16_0(Assembly a)
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Composition.TypedParts.TypedPartExportDescriptorProvider..ctor(IEnumerable`1 types, AttributedModelProvider attributeContext)
   at System.Composition.Hosting.ContainerConfiguration.CreateContainer()
   at Microsoft.DocAsCode.Common.CompositionContainer.GetContainer(IEnumerable`1 assemblies)
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder..ctor(IEnumerable`1 assemblies, ImmutableArray`1 postProcessorNames, String templateHash, String intermediateFolder, String commitFromSHA, String commitToSHA, Boolean cleanupCacheHistory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument()
[21-06-10 09:42:02.174]Info:Completed in 2865.5381 milliseconds
```

**Comment by bart-degreed** [comment]
I'm experiencing the same problem but I'm using Chocolatey in our build scripts. Can you please publish the new version through that channel too?

**Comment by superyyrrzz** [comment]
@bart-degreed Sure. We are working on it.

**Comment by superyyrrzz** [comment]
@bart-degreed 2.58 released on chocolatey: https://community.chocolatey.org/packages/docfx/2.58

**Comment by bart-degreed** [comment]
@superyyrrzz Works great, thanks a lot!
