### ISSUE TITLE
DocFX can't find MSBuild when Visual Studio is not installed

### ISSUE THREAD

**Issue by JulianBirch** [dotnet/docfx#7662]
**Operating System**: (`Windows` or `Linux` or `MacOS`)

Windows

**DocFX Version Used**: 

`2.58.4`

**Template used**: (`default` or `statictoc` or contain custom template)

Default. Using docfx through the package reference in csproj.

**Steps to Reproduce**:

Build project with no Visual Studio on the machine.

**Expected Behavior**:

DocFX should attempt to generate documentation.

**Actual Behavior**:

```
PS C:\Users\me\Petaurus.Functional> dotnet build
Microsoft (R) Build Engine version 17.0.0-preview-21460-01+8f208e609 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  You are using a preview version of .NET. See: https://aka.ms/dotnet-core-preview
  Petaurus.Functional -> C:\Users\me\Petaurus.Functional\src\Petaurus.Functional\bin\Debug\net6.0\Petaurus.Functional.dll
  [21-10-16 04:56:44.150]Warning:[MetadataCommand.ExtractMetadata]Fail to find MSBuild >= 15.0 on machine. Please install Visual Studio 2017 or above with MSBuild >= 15.0: https://visualstudio.microsoft.com/vs/
 project C:/Users/me/Petaurus.Functional/src/Petaurus.Functional/Petaurus.Functional.csproj: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.. Ignored.
  [21-10-16 04:56:47.310]Error:Error extracting metadata for C:/Users/me/Petaurus.Functional/src/Petaurus.Functional/Petaurus.Functional.csproj: System.NullReferenceException: Object reference not set to an instance of an object.
     at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()


  Build failed.
  [21-10-16 04:56:47.323]Warning:[MetadataCommand.ExtractMetadata]Fail to find MSBuild >= 15.0 on machine. Please install Visual Studio 2017 or above with MSBuild >= 15.0: https://visualstudio.microsoft.com/vs/
  [21-10-16 04:56:47.323]Warning:[MetadataCommand.ExtractMetadata](C:/Users/me/Petaurus.Functional/src/Petaurus.Functional/Petaurus.Functional.csproj)Error opening project C:/Users/me/Petaurus.Functional/src/Petaurus.Functional/Petaurus.Functional.csproj: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.. Ignored.
  [21-10-16 04:56:47.323]Error:Error extracting metadata for C:/Users/me/Petaurus.Functional/src/Petaurus.Functional/Petaurus.Functional.csproj: System.NullReferenceException: Object reference not set to an instance of an object.
     at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
  --- End of stack trace from previous location where exception was thrown ---
     at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
     at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
     at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
        2 Warning(s)
        1 Error(s)
C:\Users\me\.nuget\packages\docfx.console\2.58.4\build\docfx.console.targets(59,5): error MSB3073: The command ""C:\Users\me\.nuget\packages\docfx.console\2.58.4\build\..\tools\docfx.exe" "C:\Users\me\Petaurus.Functional\src\Petaurus.Functional/docfx.json" -o "" -l "log.txt" --logLevel "Warning"" exited with code 1. [C:\Users\me\Petaurus.Functional\src\Petaurus.Functional\Petaurus.Functional.csproj]

Build FAILED.

C:\Users\me\.nuget\packages\docfx.console\2.58.4\build\docfx.console.targets(59,5): error MSB3073: The command ""C:\Users\me\.nuget\packages\docfx.console\2.58.4\build\..\tools\docfx.exe" "C:\Users\me\Petaurus.Functional\src\Petaurus.Functional/docfx.json" -o "" -l "log.txt" --logLevel "Warning"" exited with code 1. [C:\Users\me\Petaurus.Functional\src\Petaurus.Functional\Petaurus.Functional.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:09.09
```

Luckily, the entire (small) project is OSS, so you can see the failing project here: https://github.com/JulianBirch/Petaurus.Functional/tree/doc-fx-error

But I suspect it'll only fail if you don't have Visual Studio on your machine.

**Comment by JulianBirch** [comment]
Turns out this is documented somewhere very obvious, but I'd still like fixing it to be considered: https://dotnet.github.io/docfx/tutorial/docfx_getting_started.html.

**Comment by sakno** [comment]
> Visual Studio on your machine.

I'm using Build Tools for Visual Studio instead of complete MSVS installation as a workaround.

**Comment by yufeih** [comment]
Docfx uses `MSBuildWorkspace` to analyze projects. There is a good [article](https://gist.github.com/DustinCampbell/32cd69d04ea1c08a16ae5c4cd21dd3a3#setting-up-msbuild) on how `MsBuildWorkspace` works and how to prepare an environment:

> The recommended way to set up MSBuild is to install [Visual Studio 2017](https://www.visualstudio.com/downloads/) (or newer) or the [Build Tools for Visual Studio 2017](https://www.visualstudio.com/downloads/#build-tools-for-visual-studio-2017) (or newer) on the machine that MSBuildWorkspace will run on. The important detail is to ensure that the installation has the necessary workloads and components to support the projects you'll be loading. For example, if C# is not installed, you will not be able to load C# projects. Similarly, if a project targets .NET Framework 4.7.3, that targeting pack must be installed. A good rule of thumb is, if you can build the project with MSBuild at the command-line, MSBuildWorkspace should be able to load it.

If the target is .NET Core, then only the corresponding .NET Core SDK is required in the latest version.
