### ISSUE TITLE
"System.ArgumentNullException: Value cannot be null." on create metadata

### ISSUE THREAD

**Issue by Cruncher999** [dotnet/docfx#7880]
**Operating System**: (`Windows` or `Linux` or `MacOS`)
Windows 10 19044

**DocFX Version Used**: 
v2.59.0

**other versions/tools**:
cygwin 2917
visual studio community 16.11.9

**Template used**: (`default` or `statictoc` or contain custom template)
default

**Steps to Reproduce**:

1. extract attached testcase
2. run "docfx.exe metadata docfx.json"

**Notes**:
- test class JSONObject.cs has been stripped to minimal reproducible case, note it may no longer compile without errors in VS. but even the fully implemented class throws the error.
- arbitrary testing: error does not occur when removing "using System.Collections;"
- arbitrary testing: error does not occur when changing "IEnumerator IEnumerable.GetEnumerator()" to just "IEnumerator GetEnumerator()"

**Expected Behavior**:
Documentation is generated.

**Actual Behavior**:
Output:
$ /cygdrive/c/Users/wkresse/Downloads/docfx/docfx.exe metadata docfx.json
[22-02-09 04:45:03.629]Info:[ExtractMetadata]Using msbuild C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin as inner compiler.
[22-02-09 04:45:03.796]Info:[ExtractMetadata]Loading projects...
[22-02-09 04:45:03.818]Info:[ExtractMetadata]Generating metadata for each project...
[22-02-09 04:45:04.713]Error:Error extracting metadata for C:/Users/wkresse/Desktop/projects/RepoCollector_Packages - Unity2021.2/NNN Packages/_Documentation/do
cfx_nullref_testcase/src/JSONObject.cs: System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.CodeAnalysis.Text.SourceText.From(String text, Encoding encoding, SourceHashAlgorithm checksumAlgorithm)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MakeSourceText(String text, Int32 offset)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseName(String text, Int32 offset, Boolean consumeFullText)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetMethodSyntax(IMethodSymbol symbol, IFilterVisitor filterVisitor)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetSyntaxContent(MemberType typeKind, ISymbol symbol, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisit
orAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitMethod(IMethodSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.RoslynMetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.GetMetadataFromProjectLevelCache(IBuildController controller, IInputParameters key)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
[22-02-09 04:45:04.715]Info:Completed in 1107,8578 milliseconds

Build failed.
[22-02-09 04:45:04.719]Error:Error extracting metadata for C:/Users/wkresse/Desktop/projects/RepoCollector_Packages - Unity2021.2/NNN Packages/_Documentation/do
cfx_nullref_testcase/src/JSONObject.cs: System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.CodeAnalysis.Text.SourceText.From(String text, Encoding encoding, SourceHashAlgorithm checksumAlgorithm)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MakeSourceText(String text, Int32 offset)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseName(String text, Int32 offset, Boolean consumeFullText)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetMethodSyntax(IMethodSymbol symbol, IFilterVisitor filterVisitor)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetSyntaxContent(MemberType typeKind, ISymbol symbol, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisit
orAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitMethod(IMethodSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.RoslynMetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.GetMetadataFromProjectLevelCache(IBuildController controller, IInputParameters key)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
        0 Warning(s)
        1 Error(s)

[docfx_nullref_testcase.zip](https://github.com/dotnet/docfx/files/8034650/docfx_nullref_testcase.zip)

**Comment by Cruncher999** [comment]
Further Info:
Even the original, non-stripped source file from https://github.com/mtschoen/JSONObject results in the same error, both with cygwin, and with WSL (same Windows as above, up-to-date Ubuntu 20.04.3 LTS).

Interestingly, it works with no errors on a native Linux machine with Ubuntu 20.04.

Here is that testcase with the functional, unstripped code from github, causing the same System.ArgumentNullException
[docfx_nullref_testcaseCurrent.zip](https://github.com/dotnet/docfx/files/8060539/docfx_nullref_testcaseCurrent.zip)

**Comment by Cruncher999** [comment]
Further Info:
Interestingly, that same, unmodified testcase in the previous comment works flawlessly on a native Linux machine!

Ubuntu 20.04.3 LTS
docfx v2.59.0
mono 6.12.0.122-0xamarin1+ubuntu2004b1
msbuild 1:16.6+xamarinxplat.2021.01.15.16.11-0xamarin1+ubuntu2004b1

`[hobbes->docfx_nullref_testcaseCurrent] 729 :) mono ~/inst/docfx/docfx.exe metadata docfx.json 
[22-02-14 08:49:05.654]Info:[ExtractMetadata]Using mono /usr/lib/mono/msbuild/15.0/bin/MSBuild.dll as inner compiler.
[22-02-14 08:49:05.878]Info:[ExtractMetadata]Loading projects...
[22-02-14 08:49:05.887]Info:[ExtractMetadata]Generating metadata for each project...
[22-02-14 08:49:08.059]Info:Completed in 2445.8847 milliseconds


Build succeeded.
	0 Warning(s)
	0 Error(s)
`

**Comment by bertiewooster** [comment]
@Cruncher999 Did you ever get docfx to build the documentation on a Windows computer? I'm experiencing the same issue.

I have a project with both C# (.csproj) and VB (.vbproj) files. In my `docfx.json` file, if `metadata`: `src`: `files`: includes only `"src/**.csproj"`, I get no errors. When I add `"src/**.vbproj"`:

```
{
  "metadata": [
    {
      "src": [
        {
          "files": [
            "src/**.csproj",
            "src/**.vbproj"
          ]
        }
      ],
      "dest": "api",
      "disableGitFeatures": false,
      "disableDefaultFilter": false
    }
  ],
```

, I get the error

```
Error:Error extracting metadata for foo.vbproj, bar.csproj,...: System.ArgumentNullException: Value cannot be null.
Parameter name: text
   at Microsoft.CodeAnalysis.Text.SourceText.From(String text, Encoding encoding, SourceHashAlgorithm checksumAlgorithm)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.MakeSourceText(String text, Int32 offset)
   at Microsoft.CodeAnalysis.CSharp.SyntaxFactory.ParseName(String text, Int32 offset, Boolean consumeFullText)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetPropertySyntax(IPropertySymbol symbol, IFilterVisitor filterVisitor)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CSYamlModelGenerator.GetSyntaxContent(MemberType typeKind, ISymbol symbol, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.CompositeYamlModelGenerator.GenerateSyntax(MemberType type, ISymbol symbol, SyntaxDetail syntax, SymbolVisitorAdapter adapter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitProperty(IPropertySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter)
   at Microsoft.DocAsCode.Metadata.ManagedReference.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol)
   at Microsoft.DocAsCode.Metadata.ManagedReference.RoslynMetadataExtractor.Extract(ExtractMetadataOptions options)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.GetMetadataFromProjectLevelCache(IBuildController controller, IInputParameters key)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<SaveAllMembersFromCacheAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.DocAsCode.Metadata.ManagedReference.ExtractMetadataWorker.<ExtractMetadataAsync>d__11.MoveNext()
        26 Warning(s)
        1 Error(s)
```

It's surprising that both .csproj and .vbproj files give that error because the .csproj files build fine when I ask docfx to build only them and not the .vbproj files.

**Comment by Cruncher999** [comment]
@bertiewooster no, for now I just excluded the namespace of JSONObject.cs
