### ISSUE TITLE
System.Memory mismatch with Microsoft.DocAsCode.Plugin

### ISSUE THREAD

**Issue by RobJessop** [dotnet/docfx#8247]
**Operating System**: `Windows`

**DocFX Version Used**: 2.59.4

**Template used**: custom template + custom plugin

**Steps to Reproduce**:

1. Create a plugin with Microsoft.DocAsCode.Plugin 2.59.4 nuget package
2. Use it in a project with C# API

**Expected Behavior**:
Plugin is loaded and executed

**Actual Behavior**:
An exception is raised about an unexpected System.Memory.dll version e.g.:
```
[22-11-17 12:03:17.070]Error:System.IO.FileLoadException: Could not load file or assembly 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at Newtonsoft.Json.Serialization.DefaultContractResolver.GetCallbackMethodsForType(Type type, List`1& onSerializing, List`1& onSerialized, List`1& onDeserializing, List`1& onDeserialized, List`1& onError)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveCallbackMethods(JsonContract contract, Type t)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.CreateArrayContract(Type objectType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Newtonsoft.Json.Serialization.DefaultContractResolver.ResolveContract(Type type)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(JsonWriter writer, Object value, JsonContainerContract contract, JsonProperty member, JsonProperty property, JsonContract& memberContract, Object& memberValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeObject(JsonWriter writer, Object value, JsonObjectContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonConvert.SerializeObjectInternal(Object value, Type type, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.JsonConvert.SerializeObject(Object value, JsonSerializerSettings settings)
   at Microsoft.DocAsCode.Build.Engine.Incrementals.IncrementalBuildContext.ComputeConfigHash(DocumentBuildParameters parameter, String markdownServiceContextHash) in C:\Users\RobertJessop\Work\docfx\src\Microsoft.DocAsCode.Build.Engine\Incrementals\IncrementalBuildContext.cs:line 609
   at Microsoft.DocAsCode.Build.Engine.Incrementals.IncrementalBuildContext.Create(DocumentBuildParameters parameters, BuildInfo cb, BuildInfo lb, String intermediateFolder, String markdownServiceContextHash) in C:\Users\RobertJessop\Work\docfx\src\Microsoft.DocAsCode.Build.Engine\Incrementals\IncrementalBuildContext.cs:line 86
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.Prepare(DocumentBuildParameters parameters, DocumentBuildContext context, TemplateProcessor templateProcessor, String markdownServiceContextHash, IHostServiceCreator& hostServiceCreator, PhaseProcessor& phaseProcessor) in C:\Users\RobertJessop\Work\docfx\src\Microsoft.DocAsCode.Build.Engine\SingleDocumentBuilder.cs:line 244
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.BuildCore(DocumentBuildParameters parameters) in C:\Users\RobertJessop\Work\docfx\src\Microsoft.DocAsCode.Build.Engine\SingleDocumentBuilder.cs:line 105
   at Microsoft.DocAsCode.Build.Engine.SingleDocumentBuilder.Build(DocumentBuildParameters parameters) in C:\Users\RobertJessop\Work\docfx\src\Microsoft.DocAsCode.Build.Engine\SingleDocumentBuilder.cs:line 75
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.BuildCore(DocumentBuildParameters parameter, IMarkdownServiceProvider markdownServiceProvider, BuildInfo currentBuildInfo, BuildInfo lastBuildInfo) in C:\Users\RobertJessop\Work\docfx\src\Microsoft.DocAsCode.Build.Engine\DocumentBuilder.cs:line 363
   at Microsoft.DocAsCode.Build.Engine.DocumentBuilder.Build(IList`1 parameters, String outputDirectory) in C:\Users\RobertJessop\Work\docfx\src\Microsoft.DocAsCode.Build.Engine\DocumentBuilder.cs:line 309
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory) in C:\Users\RobertJessop\Work\docfx\src\docfx\SubCommands\DocumentBuilderWrapper.cs:line 148
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument() in C:\Users\RobertJessop\Work\docfx\src\docfx\SubCommands\DocumentBuilderWrapper.cs:line 84
=== Pre-bind state information ===
LOG: DisplayName = System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
 (Fully-specified)
LOG: Appbase = file:///C:/Users/RobertJessop/Work/docfx/src/docfx/bin/Debug/net472/
LOG: Initial PrivatePath = C:\Users\RobertJessop\Work\docfx\src\docfx\bin\Debug\net472\;C:\Users\RobertJessop\Work\docfx\src\docfx\bin\Debug\net472\plugins_dvkvvyml.i13\plugins
Calling assembly : System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.
===
LOG: This bind starts in default load context.
LOG: No application configuration file found.
LOG: Using host configuration file:
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework64\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Memory, Version=4.0.1.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
LOG: Attempting download of new URL file:///C:/Users/RobertJessop/Work/docfx/src/docfx/bin/Debug/net472/System.Memory.DLL.
WRN: Comparing the assembly name resulted in the mismatch: Revision Number
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.
```

Reverting this change alleviates this particular problem but would obviously reintroduce the problem it solved: https://github.com/dotnet/docfx/pull/8135

Alternatives I tried that didn't seem to work:
* Manually adding a reference to System.Memory 4.5.5 to my plugin project (4.5.4 still seemed to be expected in the DocFX build)

**Comment by RobJessop** [comment]
I expect it would then fall through to checking the temporary `plugins_<blah>` path (the second part of the `PrivatePath` in the log) which does have the expected version. I'm not confident that there won't be side effects of removing that DLL though.

**Comment by nprorekhin** [comment]
Hi, I confirm this behavior with the [memberpage](https://www.nuget.org/packages/memberpage) 2.59.4 plugin.
It looks like the **memberpage** plugin uses _System.Memory, Version=4.0.1.1_ while DocFX uses _System.Memory, Version=4.0.1.2_
If you delete System.Memory.dll from the DocFX, the  **memberpage** plugin loads the required DLL from it's own folder and it works. However _docfx pdf_ command stops working , since it doesn't use the **memberpage** plugin and fails to find the deleted System.Memory.dll

**Comment by ZP-ZPanda** [comment]
Me too. 2.59.3 works fine.

**Comment by yufeih** [comment]
This is resolved in the latest version with a new library based plugin model, see [this sample](https://github.com/dotnet/docfx/tree/main/samples/extensions) on using the member page plugin with the new approach.
