### ISSUE TITLE
Explicit interface implementation

### ISSUE THREAD

**Issue by eriksorngard** [dotnet/docfx#8253]
Can DocFx be instructed to ignore explicit interface implementation methods?

I am hoping to avoid drawing attention to these parts of my API by not making them visible in the documentation.

**Comment by eriksorngard** [comment]
I have experimented by adding XML documentation to these methods, but apparently they are not picked up by DocFX, so the resulting documentation page still only shows a "placeholder" for them that I can not fill with content, and can not remove.

How is DocFX expected to handle explicit interface implementation documentation?

**Comment by paulushub** [comment]
Have you tried the [memberpage](https://www.nuget.org/packages/memberpage/) plugin to documents the members?

**Comment by eriksorngard** [comment]
Thank you for suggesting the memberpage plugin.

I am not familiar with it, and have to study what it actually does. The description [here](https://dotnet.github.io/docfx/templates-and-plugins/plugins-dashboard.html) does not appear to make it relevant for this case, but maybe there is more to learn.

I am only trying to insert additional text in for "undocumented" methods, because DocFX is not picking up the XML comments that are already there for explicit interface implementation methods.

**Comment by yufeih** [comment]
Hiding explicit interface implementations and overrides by default unless explicitly documented feels the reasonable default to me.

**Comment by mikernet** [comment]
@yufeih I am no longer seeing any explicit interface implementations, documented or not.

**Comment by yufeih** [comment]
Right. EIIs are hidden by default unless `includePrivateMembers` is on, do you see a need for an option to show EIIs without turn on `includePrivateMembers`?

**Comment by mikernet** [comment]
Yeah, I like my docs to look like MS docs, and I also often comment explicit interface implementations to explain how a type implements (or doesn't implement and throws NotSupportedException) the interface methods. As part of our SingulinkFX template I have an optional `memberpage-extras` plugin that groups them like the MS docs do:

![image](https://user-images.githubusercontent.com/1700111/221187369-d8eefb66-279b-4a49-abc3-1e802df48b6a.png)

Would be nice if it did that in the memberpage plugin as well though, it's a 2 line change.

**Comment by yufeih** [comment]
> Would be nice if it did that in the memberpage plugin as well though, it's a 2 line change.

Would you like to send a pull request?

**Comment by mikernet** [comment]
Yup :)

**Comment by mikernet** [comment]
Hmmm...I tried setting `includePrivateMembers` on 3 different projects and they all fail with:

```
Unhandled exception. System.IO.IOException: The filename, directory name, or volume label syntax is incorrect. : 'C:\Projects\SL\Singulink.Collections\Docs\api\Singulink.Collections.HashSetDictionary-2.<System-Collections-Generic-IEnumerable<System-Collections-Generic-KeyValuePair<TKey,System-Collections-Generic-ISet<TValue>>>-GetEnumerator>d__60.yml'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.Create(String path)
   at Microsoft.DocAsCode.Plugins.RootedFileAbstractLayer.Create(String file)
   at Microsoft.DocAsCode.Plugins.FileAbstractLayerExtensions.CreateText(IFileAbstractLayer fal, String file)
   at Microsoft.DocAsCode.Common.YamlUtility.Serialize(String path, Object graph, String comments)
   at Microsoft.DocAsCode.Dotnet.ExtractMetadataWorker.ResolveAndExportYamlMetadata(Dictionary`2 allMembers, Dictionary`2 allReferences)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.DocAsCode.Dotnet.ExtractMetadataWorker.ExtractMetadataAsync()
   at Microsoft.DocAsCode.Dotnet.DotnetApiCatalog.Exec(MetadataJsonConfig config, DotnetApiOptions options, String configDirectory, String outputDirectory)
   at Microsoft.DocAsCode.Dotnet.DotnetApiCatalog.GenerateManagedReferenceYamlFiles(String configPath, DotnetApiOptions options)
   at Program.<Main>$(String[] args) in C:\Projects\docfx-custom\docfxc\Program.cs:line 4
   at Program.<Main>(String[] args)
   ```
   
   So it's a bit hard for me to test my changes, haha.

**Comment by yufeih** [comment]
Maybe enable a new `includeExplicitInterfaceImplementations` options that affects the behavior [here](https://github.com/dotnet/docfx/blob/main/src/Microsoft.DocAsCode.Dotnet/SymbolFilter.cs#L97)?

**Comment by mikernet** [comment]
This is the PR for the memberpage changes that *should* work as those are the 2 lines I changed for 2.59.4 and it looks like everything important is the same in the current version, but as per the above, I can't get something with explicit interface implementations included to build.

https://github.com/dotnet/docfx/pull/8445

**Comment by mikernet** [comment]
Confirmed working:
![image](https://user-images.githubusercontent.com/1700111/221196985-52c89b3e-f19f-4a4f-bb15-0dc06f00218f.png)

![image](https://user-images.githubusercontent.com/1700111/221197081-36e5d717-80ce-4188-86e7-8a9532ba5fef.png)

**Comment by mikernet** [comment]
@KalleOlaviNiemitalo No, those are just the bits that do the grouping. I'm not sure where or how to fix the file name issue.

**Comment by mikernet** [comment]
Why are some member paths being cleaned but others, like the one above, aren't?  Where is the spot where the others get cleaned up?

Navigating and familiarizing myself with all this and setting up an environment where I can properly test the changes might be a little much for me at the moment, to be honest.

**Comment by mikernet** [comment]
> Maybe enable a new includeExplicitInterfaceImplementations options that affects the behavior [here](https://github.com/dotnet/docfx/blob/main/src/Microsoft.DocAsCode.Dotnet/SymbolFilter.cs#L97)?

Something like this? https://github.com/dotnet/docfx/pull/8446

**Comment by mikernet** [comment]
> but I don't know whether web servers can then serve the files.
For what it's worth, IIS on WinServer2019 doesnt seem to have any issues with the reaaaally long paths I just tested.
