### ISSUE TITLE
Invalid URI exception when running docfx.exe from bash shell under WSL

### ISSUE THREAD

**Issue by jasonzio** [dotnet/docfx#8308]
**Describe the bug**
Invoking the docfx.exe program from a Linux shell prompt running within WSL, targeting a docfx.json file within the WSL filesystem, doesn't work.

**To Reproduce**
1. Install docfx via chocolatey
2. `$ PATH="$PATH:/mnt/c/ProgramData/chocolatey/bin"`
3. `$ docfx.exe docfx.json --serve`

**Context (please complete the following information):**
- OS: Windows 10
- Docfx version: 2.59.4.0
- dotnet version: 5.0.415

- `docfx.json` config

```json
{
  "build": {
    "content": [
      {
        "files": [ "**/*.yml", "**/*.md" ]
      },
      {
        "files": [
          ".{md,yml}"
        ]
      }
    ],
    "resource": [
      {
        "files": [
          "images/**",
          "**/*.{png,PNG}",
          "**/*.{jpg,JPG}",
          "Scripts/**"
        ]
      }
    ],
    "dest": "_site",
    "markdownEngineName": "markdig",
    "globalMetadata": {
      "_appTitle": "PMC - packages.microsoft.com",
      "_enableSearch": "true",
      "_enableNewTab": "true",
      "_gitContribute": {
        "branch": "main"
      }
      },
    "fileMetadataFiles": [],
    "template": [
      "default",
      "_templates/last-modified"
    ],
    "postProcessors": [ "LastModifiedPostProcessor" ],
    "noLangKeyword": false,
    "keepFileLink": false,
    "cleanupCacheHistory": false,
    "disableGitFeatures": false
  }
}
```

- Exceptions

```csharp
Error:System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Microsoft.DocAsCode.Common.PathUtility.MakeRelativePath(String basePath, String absolutePath)
   at Microsoft.DocAsCode.Build.Engine.FileCollection.ToRelative(String file, String rootedBaseDir)
   at Microsoft.DocAsCode.Build.Engine.FileCollection.<>c__DisplayClass10_0.<Add>b__0(String f)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at Microsoft.DocAsCode.Build.Engine.FileCollection.Add(DocumentType type, String baseDir, IEnumerable`1 files, String
 sourceDir, String destinationDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.AddFileMapping(FileCollection fileCollection, DocumentType
type, FileMapping mapping)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.GetFileCollectionFromFileMapping(String baseDirectory, File
Mapping articles, FileMapping overwrites, FileMapping resources)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.ConfigToParameter(BuildJsonConfig config, TemplateManager t
emplateManager, ChangeList changeList, String baseDirectory, String outputDirectory, String templateDir)
   at Microsoft.DocAsCode.SubCommands.DocumentBuilderWrapper.BuildDocument(BuildJsonConfig config, TemplateManager templ
ateManager, String baseDirectory, String outputDirectory, String pluginDirectory, String templateDirectory)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.BuildDocument(String baseDirectory, String outputDirectory)
   at Microsoft.DocAsCode.SubCommands.BuildCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context)
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args)```

- Errors and warnings

```csharp
[22-12-22 01:38:20.080]Warning:[BuildCommand]Can't import: LastModifiedPostProcessor, System.Composition.Hosting.Composi
tionFailedException: No export was found for the contract 'IPostProcessor "LastModifiedPostProcessor"'.
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at Microsoft.DocAsCode.Common.CompositionContainer.GetExport(CompositionHost container, Type type, String name)
[22-12-22 01:38:20.081]Warning:[BuildCommand]Can't find the post processor: LastModifiedPostProcessor
[22-12-22 01:38:20.082]Error:System.UriFormatException: Invalid URI: The hostname could not be parsed.
```

- .NET info

```csharp
.NET SDK (reflecting any global.json):
 Version:   5.0.415
 Commit:    9d49d168b8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.415\

global.json file:
  Not found

Host:
  Version:      6.0.12
  Architecture: x64
  Commit:       02e45a41b7

.NET SDKs installed:
  3.1.426 [C:\Program Files\dotnet\sdk]
  5.0.415 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Additional context**
Issue #8206 addresses half the problem (invoking docfx.exe from Windows against content living in the WSL container filesystem), but that is not a sufficient solution; integration with Linux-based makefiles and scripts, as well as with vscode run within WSL, requires one to be able to invoke docfx.exe from a Linux executable running within WSL.

**Comment by yufeih** [comment]
Does the [v2.60.0](https://github.com/dotnet/docfx/discussions/8334) release address the problem? I am able to build our sample project in WSL with that version.

**Comment by jasonzio** [comment]
Yes, release 2.60.0 addresses the issue when I install the dotnet sdk within WSL and then use `dotnet tool install docfx -g` as the updated documentation suggests.

This is great stuff - thanks!
