### ISSUE TITLE
[Bug] 🪲 - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by VaclavElias** [dotnet/docfx#8653]
**Describe the bug**

I run `docfx en/docfx.json` and get this error below. It might be some edge case related with my solution. It shows up only if I include specific project (`sources/core/Stride.Core/Stride.Core.csproj`) in src files section.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.AddNameAndTypeArgumentsOrParameters(INamedTypeSymbol symbol, Boolean noEscaping)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.MinimallyQualify(INamedTypeSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.AddTypeArguments(ImmutableArray`1 typeArguments, INamedTypeSymbol modifiersSource)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.AddNameAndTypeArgumentsOrParameters(INamedTypeSymbol symbol, Boolean noEscaping)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplayVisitor.VisitNamedType(INamedTypeSymbol symbol)
   at Microsoft.CodeAnalysis.VisualBasic.SymbolDisplay.ToDisplayParts(ISymbol symbol, SemanticModel semanticModelOpt, Int32 positionOpt, SymbolDisplayFormat format, Boolean minimal)
   at Microsoft.DocAsCode.Dotnet.SymbolFormatter.GetDisplayParts(ISymbol symbol, SyntaxLanguage language, Boolean nullableReferenceType, Boolean overload, SymbolDisplayFormat format) in /_/src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.cs:line 182
   at Microsoft.DocAsCode.Dotnet.SymbolFormatter.GetNameParts(ISymbol symbol, SyntaxLanguage language, Boolean nullableReferenceType, Boolean overload) in /_/src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.cs:line 58
   at Microsoft.DocAsCode.Dotnet.YamlModelGenerator.GenerateReference(ISymbol symbol, ReferenceItem reference, Boolean asOverload) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/YamlModelGenerator.cs:line 56
   at Microsoft.DocAsCode.Dotnet.YamlModelGenerator.AddSpecReference(ISymbol symbol, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters, Dictionary`2 references, SymbolVisitorAdapter adapter) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/YamlModelGenerator.cs:line 144
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.GenerateInheritance(INamedTypeSymbol symbol, MetadataItem item) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 561
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 152
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NamedTypeSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 507
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 136
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NamespaceSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 507
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 120
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.AssemblySymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.DocAsCode.Dotnet.ExtractMetadataWorker.ExtractMetadataAsync() in /_/src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs:line 150
   at Microsoft.DocAsCode.Dotnet.DotnetApiCatalog.Exec(MetadataJsonConfig config, DotnetApiOptions options, String configDirectory, String outputDirectory) in /_/src/Microsoft.DocAsCode.Dotnet/DotnetApiCatalog.cs:line 72
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context) in /_/src/docfx/SubCommands/MetadataCommand.cs:line 29
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context) in /_/src/docfx/SubCommands/CompositeCommand.cs:line 46
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args) in /_/src/docfx/Program.cs:line 69
```

**To Reproduce**
It happens with my project https://github.com/VaclavElias/stride-docs-next, I can provide the steps, if it will be necessary.

**Expected behavior**
Probably not crashing or just saying some meaningful error if it is something I can fix.

**Context:**
- OS: Windows 11
- Docfx version: **2.65.3**

**Additional context**
<img width="1551" alt="image" src="https://user-images.githubusercontent.com/4528464/232805948-0fc43db7-9a4c-4458-8975-a91b066ca9a6.png">

**Comment by VaclavElias** [comment]
I think, with the recent commits, it is now this line

https://github.com/dotnet/docfx/blob/42185e39920c4bd825893fd813497c55ae23bac9/src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.cs#L156

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/4528464/233208418-ef1975ce-8808-4f9c-a438-194d228be3d2.png">

**Comment by yufeih** [comment]
It seems we can relax line 165 to catch all exceptions, would you like to send a PR for a fix?
