### ISSUE TITLE
[Bug] Unknown comment id ! on Ubuntu

### ISSUE THREAD

**Issue by DarkLiKally** [dotnet/docfx#8702]
**Describe the bug**
When I try generation the docfx docs on my Ubuntu build agents in a Azure VM Scaling Set I get the error `Error: Unknown comment ID format '!` from docfx.
The same execution with identical config and identical commit / code base generates just fine on my local Windows machine.
The project is .NET6

Execution in both machines using Powershell `docfx` command.

Second test:  local Docker container with Ubuntu results in the same error.
Sadly I can't share the code base - also it's huge - and sadly the error message does not give any further information where the error could be located or originate from.
I just found out so far that the error is raised from `Miscellaneous Files\SymbolUrlResolver.cs:37` of docfx. but not yet what exact member / element of my code base causes it.

**To Reproduce**
1. Try generating a docfx on Ubuntu
2. Error occurs

Here a screenshot of the docfx command output:
![grafik](https://user-images.githubusercontent.com/630466/235200894-8ca284c5-4c2c-46fd-9177-786ceb814305.png)

**Expected behavior**
The docs should generate just fine like on the Windows machine.

**Context (please complete the following information):**
- OS: Windows 10 / Ubuntu 22
- Docfx version: 2.66.2

Build Agent: Ubuntu 22, Net SDKs 5, 6 and 7 are installed.
Local machine: Windows 10, Same SDKs are installed.

**Comment by yufeih** [comment]
The error is thrown from [here](https://github.com/dotnet/docfx/blob/main/src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.cs#L37). It is weird that line 32 wasn't hit? Are you able to debug it somehow to pinpoint the problem?

**Comment by OskarKlintrot** [comment]
I hit this on Windows 10 as well. I tried to pin point the exact version that broke stuff and `2.63.1` still works but `2.64.0` throws:

```
Unable to generate spec reference for !:Microsoft.ApplicationInsights.Extensibility.ITelemetryInitializer
```
I see that there's at least 2 breaking changes in `2.64.0`, personally I would assume that breaking changes only would occur in major versions but I guess you don't use semantic versioning?

Anyway, that error is consistent up to `2.65.2`, then in `2.65.3` I instead get this:

```
System.NotSupportedException: Unknown comment ID format '!
   at Microsoft.DocAsCode.Dotnet.SymbolUrlResolver.GetMicrosoftLearnUrl(String commentId, Boolean isEnumMember, Boolean hasOverloads, String baseUrl) in /_/src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.MSLearn.cs:line 42
   at Microsoft.DocAsCode.Dotnet.SymbolUrlResolver.GetMicrosoftLearnUrl(ISymbol symbol) in /_/src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.MSLearn.cs:line 21
   at Microsoft.DocAsCode.Dotnet.SymbolUrlResolver.GetSymbolUrl(ISymbol symbol, Compilation compilation, MemberLayout memberLayout, HashSet`1 allAssemblies) in /_/src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.cs:line 12
   at Microsoft.DocAsCode.Dotnet.SymbolFormatter.<ToLinkItems>g__ToLinkItem|17_0(SymbolDisplayPart part, <>c__DisplayClass17_0&) in /_/src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.cs:line 133
   at Microsoft.DocAsCode.Dotnet.SymbolFormatter.ToLinkItems(ImmutableArray`1 parts, Compilation compilation, MemberLayout memberLayout, HashSet`1 allAssemblies, Boolean overload) in /_/src/Microsoft.DocAsCode.Dotnet/SymbolFormatter.cs:line 117
   at Microsoft.DocAsCode.Dotnet.YamlModelGenerator.GenerateReference(ISymbol symbol, ReferenceItem reference, Boolean asOverload) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/YamlModelGenerator.cs:line 42
   at Microsoft.DocAsCode.Dotnet.YamlModelGenerator.AddSpecReference(ISymbol symbol, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters, Dictionary`2 references, SymbolVisitorAdapter adapter) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/YamlModelGenerator.cs:line 135
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.AddSpecReference(ISymbol symbol, IReadOnlyList`1 typeGenericParameters, IReadOnlyList`1 methodGenericParameters) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 419
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.<>c__DisplayClass25_0.<GenerateInheritance>b__1(INamedTypeSymbol t) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 577
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.GenerateInheritance(INamedTypeSymbol symbol, MetadataItem item) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 575
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitNamedType(INamedTypeSymbol symbol) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 152
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NamedTypeSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 509        
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitNamespace(INamespaceSymbol symbol) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 136
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.NamespaceSymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitDescendants[T](IEnumerable`1 children, Func`2 getChildren, Func`2 filter) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 509        
   at Microsoft.DocAsCode.Dotnet.SymbolVisitorAdapter.VisitAssembly(IAssemblySymbol symbol) in /_/src/Microsoft.DocAsCode.Dotnet/Visitors/SymbolVisitorAdapter.cs:line 120
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.AssemblySymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.CodeAnalysis.CSharp.Symbols.PublicModel.Symbol.Microsoft.CodeAnalysis.ISymbol.Accept[TResult](SymbolVisitor`1 visitor)
   at Microsoft.DocAsCode.Dotnet.ExtractMetadataWorker.ExtractMetadataAsync() in /_/src/Microsoft.DocAsCode.Dotnet/ExtractMetadata/ExtractMetadataWorker.cs:line 150
   at Microsoft.DocAsCode.Dotnet.DotnetApiCatalog.Exec(MetadataJsonConfig config, DotnetApiOptions options, String configDirectory, String outputDirectory) in /_/src/Microsoft.DocAsCode.Dotnet/DotnetApiCatalog.cs:line 72
   at Microsoft.DocAsCode.SubCommands.MetadataCommand.Exec(SubCommandRunningContext context) in /_/src/docfx/SubCommands/MetadataCommand.cs:line 29
   at Microsoft.DocAsCode.SubCommands.CompositeCommand.Exec(SubCommandRunningContext context) in /_/src/docfx/SubCommands/CompositeCommand.cs:line 46
   at Microsoft.DocAsCode.Program.ExecSubCommand(String[] args) in /_/src/docfx/Program.cs:line 69
```

Then in `2.66.1` the stack trace disappears:

```
Error: Unknown comment ID format '!
```

**Comment by OskarKlintrot** [comment]
> The error is thrown from [here](https://github.com/dotnet/docfx/blob/main/src/Microsoft.DocAsCode.Dotnet/SymbolUrlResolver.cs#L37). It is weird that line 32 wasn't hit? Are you able to debug it somehow to pinpoint the problem?

It returns `null` as expected, then it goes into `GetMicrosoftLearnUrl(ISymbol)`:
```csharp
        return GetDocfxUrl(symbol, memberLayout, allAssemblies) // <-- returns null
            ?? GetMicrosoftLearnUrl(symbol) // <-- throws
            ?? GetPdbSourceLinkUrl(compilation, symbol);
```

**Comment by tisonkun** [comment]
Here is a reproduce repo: https://github.com/tisonkun/pulsar-dotpulsar/tree/docfx

```
$ dotnet build
$ docfx docfx.json
Using .NET Core SDK 7.0.203
Loading assembly /Users/chenzili/Brittani/pulsar-dotpulsar/src/DotPulsar/bin/Debug/netstandard2.0/DotPulsar.dll
Unable to resolve assembly reference Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Unable to resolve assembly reference protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67
Unable to resolve assembly reference Microsoft.Bcl.HashCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
Unable to resolve assembly reference HashDepot, Version=2.0.3.0, Culture=neutral, PublicKeyToken=null
Unable to resolve assembly reference protobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67
Loading assembly /Users/chenzili/Brittani/pulsar-dotpulsar/src/DotPulsar/bin/Debug/net6.0/DotPulsar.dll
Loading assembly /Users/chenzili/Brittani/pulsar-dotpulsar/src/DotPulsar/bin/Debug/netstandard2.1/DotPulsar.dll
Unable to resolve assembly reference protobuf-net.Core, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67
Unable to resolve assembly reference HashDepot, Version=2.0.3.0, Culture=neutral, PublicKeyToken=null
Unable to resolve assembly reference protobuf-net, Version=3.0.0.0, Culture=neutral, PublicKeyToken=257b51d87d2e4d67
Loading assembly /Users/chenzili/Brittani/pulsar-dotpulsar/src/DotPulsar/bin/Debug/net7.0/DotPulsar.dll
Processing DotPulsar
Completed in 1106.2687 milliseconds
Error: Unknown comment ID format '!
```
