### ISSUE TITLE
Help with custom PostProcessor

### ISSUE THREAD

**Issue by Lulalaby** [dotnet/docfx#8740]
Hello there!

I'm in need of help for custom post processors.

I'm switching to the latest release rn and none of the post processors can be loaded anymore.

```
Post processor ExtractSearchIndex loaded.
Can't import: CustomMemberIndexer, System.Composition.Hosting.CompositionFailedException: No export was found for the contract 'IPostProcessor "CustomMemberIndexer"'.
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport(Type exportType, String contractName)
   at Microsoft.DocAsCode.Common.CompositionContainer.GetExport(CompositionHost container, Type type, String name) in /_/src/Microsoft.DocAsCode.Build.Engine/CompositionContainer.cs:line 50
Can't find the post processor: CustomMemberIndexer
Can't import: DescriptionGenerator, System.Composition.Hosting.CompositionFailedException: No export was found for the contract 'IPostProcessor "DescriptionGenerator"'.
   at System.Composition.CompositionContext.GetExport(CompositionContract contract)
   at System.Composition.CompositionContext.GetExport(Type exportType, String contractName)
   at Microsoft.DocAsCode.Common.CompositionContainer.GetExport(CompositionHost container, Type type, String name) in /_/src/Microsoft.DocAsCode.Build.Engine/CompositionContainer.cs:line 50
Can't find the post processor: DescriptionGenerator
```

What changed since the last releases (before the net6 upgrade).

I can't find any useful information in the releases, issues and docs.

Does the plugin needs to have a special name when generated?

I would be happy about any info pointing me in the right direction.

Regards Lala ❤️

**Comment by InFTord** [comment]
Yes, local postprocessors currently don't work. I can try to fix it, but no promises.

**Comment by Lulalaby** [comment]
Thank you! I'm going to look into it as well a bit, at least I try.

**Comment by Lulalaby** [comment]
Ya it seems like the plugins for template folders are ignored completely.
Dunno how to fix tho

**Comment by Lulalaby** [comment]
The issue seems to be here:

https://github.com/dotnet/docfx/blob/main/src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs#L22

**Comment by filzrev** [comment]
Current implementation seems DLL  plugins are loaded from  `.exe` exists directory only.    

Additionary, LoadPluginAssemblies` methods loads unnecessary DLLs everytimes. 

https://github.com/dotnet/docfx/blob/d5606f5e75a99f0d1783185b2416581a5ea7c9df/src/Microsoft.DocAsCode.App/Helpers/DocumentBuilderWrapper.cs#L51

This behavihor can be confirms with following command.

> docfx build --logLevel Verbose

In my environment, DLLs processing wasted about 500ms on every startup. (On `Release` build)

---

Related documents needs to fixed.

https://dotnet.github.io/docfx/tutorial/howto_build_your_own_type_of_documentation_with_custom_plug-in.html#enable-plug-in
https://dotnet.github.io/docfx/tutorial/howto_add_a_customized_post_processor.html#step4-build-your-project-and-copy-the-output-dll-files-to
https://dotnet.github.io/docfx/tutorial/advanced_support_hyperlink.html#test-and-verify
