### ISSUE TITLE
DocFx is not building pdf in azure server agent

### ISSUE THREAD

**Issue by gitsourabhmishranotes** [dotnet/docfx#8992]
Error happen when converting pdf/toc.json to Pdf. Details: System.NullReferenceException: Object reference not set to an instance of an object.
     at UglyToad.PdfPig.Writer.PdfDocumentBuilder.CompleteDocument()
     at UglyToad.PdfPig.Writer.PdfDocumentBuilder.Dispose()
     at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.WriteOutlines(MemoryStream input, Stream output) in /_/src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs:line 301
     at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.SaveCore(Stream stream) in /_/src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs:line 267
     at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.Save(String outputFileName) in /_/src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs:line 91
     at Microsoft.DocAsCode.HtmlToPdf.ConvertWrapper.ConvertCore(String basePath, String pdfFileName, IList`1 htmlModels) in /_/src/Microsoft.DocAsCode.HtmlToPdf/ConvertWrapper.cs:line 342
     at Microsoft.DocAsCode.HtmlToPdf.ConvertWrapper.<>c__DisplayClass7_0.<ConvertCore>b__1(ManifestItem tocFile) in /_/src/Microsoft.DocAsCode.HtmlToPdf/ConvertWrapper.cs:line 166

**Comment by yufeih** [comment]
Seems like a dup of #8987
