### ISSUE TITLE
[Bug] PDF generation fails with System.Collections.Generic.KeyNotFoundException and creates corrupt pdf file

### ISSUE THREAD

**Issue by merlinschumacher** [dotnet/docfx#8994]
**Describe the bug**
Creating a PDF fails, with the generator yielding an exception. The PDF is broken. This is similar to #8987, but the exception is different.

```
Start generating PDF files...
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Loading pages (1/6)
Counting pages (2/6)
Resolving links (4/6)
Loading headers and footers (5/6)
Printing pages (6/6)
Done
Error happen when converting pdf/toc.json to Pdf. Details: System.Collections.Generic.KeyNotFoundException: Page 0 was not found in the source document.
   at UglyToad.PdfPig.Writer.PdfDocumentBuilder.CreateExplicitDestinationToken(ExplicitDestination destination, Dictionary`2 pageReferences)
   at UglyToad.PdfPig.Writer.PdfDocumentBuilder.CreateBookmarkTree(IReadOnlyList`1 nodes, Dictionary`2 pageReferences, IndirectReferenceToken parent)
   at UglyToad.PdfPig.Writer.PdfDocumentBuilder.CompleteDocument()
   at UglyToad.PdfPig.Writer.PdfDocumentBuilder.Dispose()
   at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.WriteOutlines(MemoryStream input, Stream output) in /_/src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs:line 301
   at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.SaveCore(Stream stream) in /_/src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs:line 267
   at Microsoft.DocAsCode.HtmlToPdf.HtmlToPdfConverter.Save(String outputFileName) in /_/src/Microsoft.DocAsCode.HtmlToPdf/HtmlToPdfConverter.cs:line 91
   at Microsoft.DocAsCode.HtmlToPdf.ConvertWrapper.ConvertCore(String basePath, String pdfFileName, IList`1 htmlModels) in /_/src/Microsoft.DocAsCode.HtmlToPdf/ConvertWrapper.cs:line 342
   at Microsoft.DocAsCode.HtmlToPdf.ConvertWrapper.<>c__DisplayClass7_0.<ConvertCore>b__1(ManifestItem tocFile) in /_/src/Microsoft.DocAsCode.HtmlToPdf/ConvertWrapper.cs:line 166
Completed Scope:PDF in 6901,0609 milliseconds.
```

**To Reproduce**
1. Create a project with the following PDF settings:
```json 
    "pdf": {
        "content": [
            {
                "files": [
                    "pdf/toc.yml"
                ]
            }
        ],
        "wkhtmltopdf": {
            "additionalArguments": "--enable-local-file-access"
        }
    }
```
2. Run the conversion

**Expected behavior**
A working PDF to be generated containing the files 

**Context (please complete the following information):**
- OS: Windows
- Docfx version: 2.67.5

**Additional context**
The issue happens with different markdown files. They're all syntactically correct

**Comment by Lagann311** [comment]
I could reproduce the error and what worked for me was changing the "files" value to `"**/*.{md,yml}"` like in the PDF part of the docfx documentation https://dotnet.github.io/docfx/docs/pdf.html:

  "pdf": {
    "content": [
      {
        "files": [ "**/*.{md,yml}" ]
      }
    ]
  }

**Comment by yufeih** [comment]
@merlinschumacher Do you happened to know what was the docfx version that used to work?

**Comment by merlinschumacher** [comment]
I just started to use docfx this week, so I didn't test older versions.

**Comment by yufeih** [comment]
Is there a minimal repo project publicly available?

**Comment by filzrev** [comment]
I've tested `docfx pdf` command on supplied minimal test contents.
And following warning is reported.

> pdf\toc.yml(0,1): warning InvalidFileLink: Invalid file link:(~/pdf/README.MD).

It seems pdf generation error is occurred because `content` don't includes `*.md` files.
If  `"pdf/**.md",` entry is added to `docfx.json`.  pdf build is succeed without warning/error.
