### ISSUE TITLE
[Bug] DocfxException: Cannot find .NET Core SDK to compile the project (but .net core 8.0.300 sdk is installed)

### ISSUE THREAD

**Issue by waldobronchart** [dotnet/docfx#9946]
**Describe the bug**

Running `docfx` on our build machine produces this error. It appears I do have the appropriate sdk/tools installed. 

How do I help docfx to find the sdk?

```
root@Ubuntu-2204-jammy-amd64-base ~/myagent/_work/34/s/apps/creator-toolkit-docs # docfx --verbose
System.IO.DirectoryNotFoundException: Could not find a part of the path '/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.DirectoryInfo.GetDirectories(String searchPattern, EnumerationOptions enumerationOptions)
   at Docfx.Dotnet.CompilationHelper.GetDefaultMetadataReferences(String language) in /_/src/Docfx.Dotnet/CompilationHelper.cs:line 145
DocfxException: Cannot find .NET Core SDK to compile the project.
  at IEnumerable<MetadataReference> GetDefaultMetadataReferences(string language) in CompilationHelper.cs:157                                                                         
  at Compilation CreateCompilationFromCSharpFiles(IEnumerable<string> files, IDictionary<string, string> msbuildProperties, MetadataReference[] references) in CompilationHelper.cs:62
  at async (List<ValueTuple<IAssemblySymbol, Compilation>> symbol) Compile(ExtractMetadataConfig config, DotnetApiOptions options) in DotnetApiCatalog.Compile.cs:101                 
  at async Task <Exec>g__Build|5_0(ExtractMetadataConfig config, DotnetApiOptions options) in DotnetApiCatalog.cs:86                                                                  
  at async Task Exec(MetadataJsonConfig config, DotnetApiOptions options, string configDirectory, string outputDirectory) in DotnetApiCatalog.cs:72                                   
  at void <Execute>b__0() in DefaultCommand.cs:45                                                                                                                                     
  at int Run(LogOptions options, Action run) in CommandHelper.cs:48                                                                                                                   
  at int Execute(CommandContext context, Options options) in DefaultCommand.cs:31                                                                                                     
  at Task<int> Execute(CommandContext context, CommandSettings settings) in CommandOfT.cs:40                                                                                          
  at Task<int> Execute(CommandTree leaf, CommandTree tree, CommandContext context, ITypeResolver resolver, IConfiguration configuration) in CommandExecutor.cs:144                    
  at async Task<int> Execute(IConfiguration configuration, IEnumerable<string> args) in CommandExecutor.cs:83                                                                         
  at async Task<int> RunAsync(IEnumerable<string> args) in CommandApp.cs:84    
```

It appears that I do have the sdk installed correctly
```
root@Ubuntu-2204-jammy-amd64-base ~/myagent/_work/34/s/apps/creator-toolkit-docs # dotnet --info
.NET SDK:
 Version:           8.0.300
 Commit:            326f6e68b2
 Workload version:  8.0.300-manifests.c1c70047
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /usr/share/dotnet/sdk/8.0.300/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.5
  Architecture: x64
  Commit:       087e15321b

.NET SDKs installed:
  8.0.300 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

path environment variable:
```
root@Ubuntu-2204-jammy-amd64-base ~/myagent/_work/34/s/apps/creator-toolkit-docs # echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/root/.dotnet/tools:/usr/share/dotnet/:/usr/share/dotnet/sdk/
```

Not sure why I don't have the expected `packs` directory:
```
root@Ubuntu-2204-jammy-amd64-base ~/myagent/_work/34/s/apps/creator-toolkit-docs # ls /usr/share/dotnet
dotnet  host  LICENSE.txt  metadata  sdk  sdk-manifests  shared  templates  ThirdPartyNotices.txt
```

**To Reproduce**
I'm not sure if this is reproducible 

**Expected behavior**
docfx can find the sdk

**Context:**
- OS: Ubuntu
- Docfx version: `2.76.0+0f6435902a0c6d9769124d00532bba32c80740e0`

**Comment by waldobronchart** [comment]
Reinstalling dotnet appears to fix it 🤦 

https://stackoverflow.com/a/73315318/448679
